### ISSUE TITLE
Ads not displaying on sample app

### ISSUE THREAD

**Issue by matganine** [prebid/prebid-mobile-android#100]
Hi everyone,

I tried the new sample app (API1.0), however ads are not displaying on DFP and I can only see the default DFP line item ("PriceCheck line item didn't serve"). 
This is awkward as I am getting the successful bids from prebid-server and in the logs, the correct targeting keys seem to be set. So I can only see two reasons for the ads failing to display:
1. Either, there is something wrong with the line items configured with the associated adunit ids "/19968336/PriceCheck_300x250" and "/19968336/PriceCheck_Interstitial"
2. Or, there is an issue while forwarding the targeting keys in the Google Ad Manager ad request

Does anyone have an idea what's the issue here? Is this happening to anyone else?
Thank you

**Comment by yoalex5** [comment]
For demo purposes you can try using:
 
AdServer name: AdManager 
PrebidServer host: AppNexus
AdType: Banner
AdSize: 300x250
AdUnit id: "/19968336/PrebidMobileValidator_Banner_All_Sizes" 

AdServer name: AdManager 
PrebidServer host: AppNexus
AdType: Interstitial
AdUnit id: "/19968336/PrebidMobileValidator_Interstitial"

**Comment by anwzhang** [comment]
Hi @matganine,

I'll double check if the sample placement in the demo app works.
In the mean time, if you're wondering if prebid mobile is doing the right thing, you can use Dr.Prebid (an iOS app) to test with your own configs.

**Comment by bszekely1** [comment]
I am closing this issue since it has been validated with two independent parties and no responses have been made since.

**Comment by gvan** [comment]
I faced with the same issue. I launch Java example app under both master branch or fixDemoApp branch and there is an empty screen when I try to see a banner ad.
![Screenshot_1584540136](https://user-images.githubusercontent.com/3866569/77051731-72e7d280-69d4-11ea-889d-b34373774621.png)
I try to use the following configuration:
- PBS Host: AppNexus/Rubicon
- Ad Type: Banner
- Ad Server: AdManager
- Ad Size: 300x250
Can you, please, review your example app and setup it to working state?
