### ISSUE TITLE
How to initialize post data before the first request?

### ISSUE THREAD

**Issue by kdravolin** [prebid/prebid-mobile-android#101]
This is method of getting post data in PrebidServerAdapter:
```
        private JSONObject getPostData() throws NoContextException {
            Context context = PrebidMobile.getApplicationContext();
            if (context != null) {
                AdvertisingIDUtil.retrieveAndSetAAID(context);
                PrebidServerSettings.update(context);
            }
            ...
```
According the code, `AdvertisingIDUtil.retrieveAndSetAAID` and `PrebidServerSettings.update` methods are called asynchronously during a request. So the first request doesn't contain some data e.g. "ifa" and "ua".

Is there any way to initialize this params before the first request?

**Comment by derN3rd** [comment]
Hey, we are having the same issues and seeing that most of our prebid-mobile requests are missing ifa and ua (therefore we don't get any bids).

Are they any news/workarounds for this?

Thanks in advance

**Comment by anwzhang** [comment]
@derN3rd are you seeing missing ifa and ua only in the first calls or most calls?

**Comment by derN3rd** [comment]
Sorry for the late response.

We only see this missing in the first calls.

**Comment by anwzhang** [comment]
Hi @derN3rd @yoalex5 ,

I think there're two solutions:
1. consolidate the following methods into one `initSDK()` method (with parameters)
```
PrebidMobile.setPrebidServerHost(Host.APPNEXUS);
PrebidMobile.setPrebidServerAccountId(Constants.PBS_ACCOUNT_ID);
PrebidMobile.setShareGeoLocation(true);
PrebidMobile.setApplicationContext(getApplicationContext());
```
Then do the initial setup of aaid inside the `initSDK()`, thus we can provide a callback to the user that SDK is ready, but this requires API breaking changes.
2. When a user uses PrebidMobile.setApplicationContext(getApplicationContext()), we immediately starts fetching aaid, etc. This is only internal change.

Thoughts?

**Comment by yoalex5** [comment]
Hello @anwzhang,

I like the second variant because it is easy and does not require API changes
