### ISSUE TITLE
Prebid 1.0 does not accept FLUID ad size

### ISSUE THREAD

**Issue by jagrulez247** [prebid/prebid-mobile-android#107]
We have a requirement to show FLUID ad size with Prebid 1.0, but when we try to fetch a bid, we always get a INVALID_SIZE result code in the response. The ad unit used is BannerAdUnit. We get successful bids for other ad sizes like BANNER and exact sizes.

Prebid init -

```
PrebidMobile.setApplicationContext(context)
PrebidMobile.setPrebidServerAccountId(prebidConfig.getPrebidAccountId())
PrebidMobile.setShareGeoLocation(prebidConfig.shareGeoLocation)
PrebidMobile.setPrebidServerHost(Host.APPNEXUS)
```

BannerAdUnit creation - 

```
private fun getBannerAdUnit(placement: SponsoredAdPlacement): BannerAdUnit? {
        val adSizes = prebidConfig.getAdSize(placement)

        if (adSizes.isEmpty()) {
            return null
        }

        val bannerAdUnit = BannerAdUnit(prebidConfig.getConfigId(placement), adSizes.first().width, adSizes.first().height).also {
            it.setAutoRefreshPeriodMillis(prebidConfig.autoRefreshMillis)
        }
        adSizes.drop(1).forEach { size -> bannerAdUnit.addAdditionalSize(size.width, size.height) }

        return bannerAdUnit
    }
```

Attaching bids -

```
open fun attachBidsWhenReady(request: PublisherAdRequest) {
        val fetchCompleteListener = this
        getBannerAdUnit(paramData.sponsoredAdPlacement)?.let {
            PrebidRequestManager.fetchDemand(it, request, fetchCompleteListener)
        }
    }
```

**Comment by bszekely1** [comment]
Hi @jagrulez247, Prebid SDK does not support Fluid sizes per our [integration page](http://prebid.org/prebid-mobile/legacy/android/code-integration-android.html).  My understanding of fluid sizes is for native ad units (which is also not supported). Are you attempting to apply this to a native ad unit? if not, what is your use case?

**Comment by lilahunt** [comment]
Hi @jagrulez247 I am going to close this issue since Fluid is not currently supported. We do have plans to support native in our roadmap but that work hasn't yet been volunteered for by a development team.
