### ISSUE TITLE
Disable Circle CI Checks

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-android#109]
If take a look at #108 you will see a `ci/circleci: Build Error`. 

Since the repository does not support CicrleCI integration I propose to [disable it](https://circleci.com/docs/2.0/enable-checks/)

**Comment by yoalex5** [comment]
@ppuviarasu, could you please review this issue ?

**Comment by yoalex5** [comment]
@ppuviarasu, is it possible to switch off the circle CI checks ?

**Comment by yoalex5** [comment]
@ppuviarasu, are we going to remove CircleCI setup or we will support both systems ?

**Comment by anwzhang** [comment]
Hi @yoalex5 we'll remove CircleCI

**Comment by yoalex5** [comment]
I have disabled CircleCI for Android repository
