### ISSUE TITLE
cannot set timeout

### ISSUE THREAD

**Issue by theAtheA** [prebid/prebid-mobile-android#111]
In the pre 1.0 client version there was a way to set the client timeout. In the current version there is no public api to override/set the timeout. Could you please reintroduce this feature.
The [PrebidMobile](https://github.com/prebid/prebid-mobile-android/blob/22efd996cb2050b5b0a67dd609ecab38e5814400/PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidMobile.java) class already contains a timeout feature, but it's not public.

**Comment by bszekely1** [comment]
Hi @theAtheA, I will bring this topic back up within the Prebid org. This was talked about some time ago and it may warrant further discussion.

**Comment by AntoineJac** [comment]
@theAtheA , indeed the field should be public. I guess a small typo as be made as public is used for the variable which is useless as also declared as final. Here is the PR for the fix: #112 

For information you can use below code as workaround:


        try {
            Field timeoutMillisField = PrebidMobile.class.getDeclaredField("timeoutMillis");
            timeoutMillisField.setAccessible(true);
            timeoutMillisField.set(null, 3000);
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }

**Comment by theAtheA** [comment]
> Hi @theAtheA, I will bring this topic back up within the Prebid org. This was talked about some time ago and it may warrant further discussion.

As a note: My colleage requested the reimplementation for the same feature in the iOS sdk and it was already discussed and implemented there.

**Comment by bszekely1** [comment]
This will be released in 1.2
