### ISSUE TITLE
Compilation issue 

### ISSUE THREAD

**Issue by AntoineJac** [prebid/prebid-mobile-android#114]
I have an issue with the new version in my Android studio
I am receiving function connectedSourceCodeDebugAndroidTest is unknown.
By removing this from the gradle file all is working fine...

This change has been pushed with #106 

Should we remove it? Thanks,

**Comment by yoalex5** [comment]
```
project.gradle.taskGraph.whenReady {
    connectedSourceCodeDebugAndroidTest {
        ignoreFailures = true
    }
}
```
This code snippet was added to serve UI tests and do not fail the TravisCI if some of UI tests were not passed. 

`connectedSourceCodeDebugAndroidTest` it is result of `connected<BuildVariant>AndroidTest` (:API1.0Demo module). 

1. Do you have a `SourceCodeDebug` module ? 
2. Could you please explain how to reproduce this error ?

**Comment by yoalex5** [comment]
I am closing this issue due do inability to reproduce. 
Please reopen the issue if you have new details
