### ISSUE TITLE
1.1.1 Can't use TargetingParams.setGender through Public API

### ISSUE THREAD

**Issue by ptomasroos** [prebid/prebid-mobile-android#121]
There is no way to use the TargetingParams.GENDER since its not exposed through the API surface, most likely proguard stripped it very similar to #116 
![Screenshot 2019-07-03 at 17 14 27](https://user-images.githubusercontent.com/1064547/60603808-ba7eed80-9db6-11e9-96e2-bc342fcd9d02.png)

**Comment by yoalex5** [comment]
This issue is also relevant to previous versions.
GitHub PR https://github.com/prebid/prebid-mobile-android/pull/117#event-2458165709 should fix the issue

**Comment by bszekely1** [comment]
Hello @ptomasroos, version 1.1.1 has been re-released with the adjustment to the Proguard rules. Can you please test this again with the new release to validate the fix functions? I would like to close this ticket.

**Comment by ptomasroos** [comment]
I will check this tonight!

**Comment by bszekely1** [comment]
Hi @ptomasroos. If there is no status here, i will assume this issue is resolved and close the ticket. If you can please provide the status on your latest test.

**Comment by bszekely1** [comment]
This issue will assume to be resolved. No additional details provided if the user is still experiencing the same issue post 1.1.1 release. If the user is still experiencing this behavior we can re-evaluate this ticket again.

**Comment by ptomasroos** [comment]
Sorry for being slow on feedback vacation got inbetween, will report back when tested!
