### ISSUE TITLE
Advanced interstitial support

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-android#126]
1. Add support for the `minwidthperc` and `minheightperc` fields on the API side to the publisher:

2. From the SDK side make OpenRTB request to Prebid Server:

```
{
	"imp": [{
		...
		"banner": {
			"format": [{
				"w": 411,
				"h": 659
			}],
                 "instl":1
		}
	}],
	"device": {
		...
		"w": 411,
		"h": 659,
                 "ext":{
			"prebid":{
				"interstitial": {
					"minwidthperc": 50,
					"minheightperc": 40
				}
			}
		}
	}
}
```

**Comment by ppuviarasu** [comment]
Do we have the required support on prebid server to consume these changes?

**Comment by bszekely1** [comment]
Yes, this has been deployed per https://github.com/prebid/prebid-server/pull/797

The idea here was to use the existing interstitial solution in Prebid Server until it does not meet the needs of publishers. It's much easier from the start to use what we have.
