### ISSUE TITLE
Kotlin Sample apps for publisher

### ISSUE THREAD

**Issue by ppuviarasu** [prebid/prebid-mobile-android#129]
the publisher dev has gotten back with the following saying that the onComplete never gets called in the code

``` Kotlin 
bannerAdUnit.fetchDemand(request, OnCompleteListener { resultCode ->
    fun onComplete(resultCode: ResultCode) {
        publisherAdView.loadAd(request)
    }
})
```

he suspects that the auto conversion might not fit well in the following line of code:
 ```bannerAdUnit.fetchDemand(request, OnCompleteListener { resultCode ->```

**Comment by yoalex5** [comment]
Currently am working on iOS version and tomorrow I plan to start improving an Android version

**Comment by avohraa** [comment]
Hi,

The OnCompleteListener with the fetchDemand can be implemented using the following ways:

> Creating an object of that interface and define the override method right after.
```
bannerAdUnit!!.fetchDemand(request, object : OnCompleteListener {
        override fun onComplete(resultCode: ResultCode) {
                publisherAdView.loadAd(request)
        }
})
```
OR
> Lambdas
```
bannerAdUnit!!.fetchDemand(request) { resultCode ->
    publisherAdView.loadAd(request)
}
```

I have tested those and it works fine.

**Comment by yoalex5** [comment]
@ppuviarasu, do you have updated from the  publisher regarding this issue ?

**Comment by yoalex5** [comment]
GutHub PR with Kotlin sample #138
