### ISSUE TITLE
1.1.2 is not working in all api level

### ISSUE THREAD

**Issue by vishalvanpariya** [prebid/prebid-mobile-android#135]
Hello,
I am trying to implement prebid ad in android and using 1.1.2 version but it is not working lower than 21 Api level.

Please give us some solution

Thank you

**Comment by bszekely1** [comment]
Can you give more details please. What isn’t working? Have you implemented the resize feature in 1.1.2?

**Comment by vishalvanpariya** [comment]
yes i had implemented it but main problem is 
`bannerAdUnit.fetchDemand(request, new OnCompleteListener() {
            @Override

            public void onComplete(ResultCode resultCode) {
                Log.d("xxxx", "onComplete: " + resultCode);
                dfpAdView.loadAd(request);
            }
        });`

above function not calling in api 17 so without that we can not get ad.

Thank you

**Comment by yoalex5** [comment]
Hello @vishalvanpariya !

I have setup a configuration with Emulator API 17 and the method `OnCompleteListener.onComplete()` is called.

Could you please provide a Charles log and AndroidStudio log ?
Thanks

**Comment by vishalvanpariya** [comment]
Hello,
Thanks for Response,
in Charles request is coming with cust_params "excl_cat" and everytime it comes TIMEOUT.(it take too much time to response)
and it is working perfectly 21api and more than it.

**Comment by yoalex5** [comment]
If PrebidSDK does not retrieve a response, it throws `TIMEOUT` ResultCode in `OnCompleteListener.onComplete()` method. 

Could you please upload a Charles log ?

**Comment by bszekely1** [comment]
Hello @vishalvanpariya, if this is still an issue? If you can please provide more detail such as a charles log would be helpful.
