### ISSUE TITLE
NoSuchMethodFoundException when trying to call getCustomTargetting method

### ISSUE THREAD

**Issue by niranjannewscorp** [prebid/prebid-mobile-android#18]
Auction APIs never gets called when we try to load ads from views.

Prebid call dynamic methods from dynamic classes. In one of those instances it calls `getCustomTargetting` method and throws `NoSuchMethodFoundException`. This is happening because progaurd strips all public methods of PublisherAdRequest.

I had to add rules for only PublisherAdRequest and it has fixed the issue. Now, auction API gets hit for every ad.

**Solution:**
```
-keep class com.google.android.gms.ads.doubleclick.PublisherAdRequest {
   public *;
}
```

**Adding correct progaurd rules in documentation should help fellow developers.**

**Comment by anwzhang** [comment]
@niranjannewscorp Thanks for reporting this, I'll create a doc issue and update it asap.

**Comment by anwzhang** [comment]
Doc updated: http://prebid.org/prebid-mobile/code-integration-android.html
