### ISSUE TITLE
What Android SDK version is required for version 1.5?

### ISSUE THREAD

**Issue by JPapasian** [prebid/prebid-mobile-android#181]
I've been having some issues getting this up and running and my current suspicion is that I am not using a compatible SDK versions.

Is there some type of compatibility list somewhere?

Thanks

**Comment by bszekely1** [comment]
Hi @JPapasian, what issues are you having? Can you please describe the problem that is occurring.

**Comment by bszekely1** [comment]
I am closing this issue out. If you are able to provide further details, we can follow up then.
