### ISSUE TITLE
importing org.prebid:prebid-mobile-sdk:1.5 does not include latest changes within PrebidMobile.java

### ISSUE THREAD

**Issue by EugenioLopez1** [prebid/prebid-mobile-android#187]
importing `org.prebid:prebid-mobile-sdk:1.5` does not include fix as seen [here](https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java) for 1.5

1. import `org.prebid:prebid-mobile-sdk:1.5` 

2. within the project, paste the following snippet `PrebidMobile.setApplicationContext()`
3. view the source code for `setApplicationContext()`
4. source code implements the following:

 `public static void setApplicationContext(Context context) {
      applicationContextWeak = new WeakReference<Context>(context);
    }`

source code should instead implement the PrebidMobile.java class from 1.5 and reveal the following: 

`public static void setApplicationContext(Context context) {
        applicationContextWeak = new WeakReference<>(context);
        if (context != null) {
            AdvertisingIDUtil.retrieveAndSetAAID(context);
            PrebidServerSettings.update(context);
        }
    }`

Tested on a samsung s8 running Android 9.0

This is not allowing me to resolve issue [101](https://github.com/prebid/prebid-mobile-android/issues/101)

**Comment by yoalex5** [comment]
Hello @EugenioLopez1 
Thank you for reporting  the issue.

It will be fixed at the next release

**Comment by yoalex5** [comment]
Hello @EugenioLopez1

[Release 1.6](https://github.com/prebid/prebid-mobile-android/releases/tag/1.6) is ready
