### ISSUE TITLE
IllegalAccessError when NativeAsset's subclass is accessed from Kotlin class

### ISSUE THREAD

**Issue by Riabkov** [prebid/prebid-mobile-android#191]
**Describe the bug**
Application crashes when trying to add NativeAsset's subclass (for example NativeTitleAsset) to NativeAdUnit from Kotlin class. Integration code is used from http://prebid.org/prebid-mobile/pbm-api/android/pbm-nativeadunit-android.html . 

Possibly the issue connected to https://discuss.kotlinlang.org/t/kotlin-java-abstract-class-illegalaccesserror/2544

**To Reproduce**
Create empty Java and Kotlin applications with just that native ad unit integration from Prebid docs. Java - works fine, Kotlin - crashes.

**Expected behavior**
No crash happens.

**Screenshots**
Stacktrace: 
![image](https://user-images.githubusercontent.com/22525345/81415467-28234500-9151-11ea-9a36-511ae3005cc1.png)

Place in code:
![image](https://user-images.githubusercontent.com/22525345/81416721-c9f76180-9152-11ea-9b13-cb5a6f26093f.png)

**Desktop:**
 - OS: MacOS 10.15.14

**Smartphone:**
 - Device: Android Emulator Nexus 5X 
 - OS: Android API 29

**Additional context**
Can be temporary fixed by moving native ad unit initialisation to Java class.

**Comment by ValentinPostindustria** [comment]
It's problem of Kotlin SDK, not Prebid, you can track it on: https://youtrack.jetbrains.com/issue/KT-11700.
