### ISSUE TITLE
Make parameter for "test=1" value in request

### ISSUE THREAD

**Issue by DrMoriarty** [prebid/prebid-mobile-android#192]
**Is your feature request related to a problem? Please describe.**
The prebid server can response more debug data when request contains test=1 parameter.

**Describe the solution you'd like**
But this library doesn't allow me to set up this parameter in any way.

**Describe alternatives you've considered**
Of course I can set test=1 in stored_imps or stored_request. But it isn't very comfortable to change server side parameters when I want to check output in application side.

**Additional context**

**Comment by bszekely1** [comment]
This is not a bad idea. I will put it in the backlog of work. Today you can hack it using Charles Proxy but that is not clean. It makes more sense to just add it as a field.

**Comment by bszekely1** [comment]
We will be adding this into release 1.7. The description is documented here: https://github.com/prebid/prebid-mobile-ios/issues/301
