### ISSUE TITLE
PrebidServerAdapter Endpoint Change

### ISSUE THREAD

**Issue by sergiosrax** [prebid/prebid-mobile-android#20]
Hi guys

I want to implement my own Prebid Server instance but having troubles changed the endpoint on the class PrebidServerAdapter, so far I haven't found anything on the documentation to change it by code.

Can you guys advice?

**Comment by anwzhang** [comment]
Hi,

What is the trouble you're having?
To connect to your own Prebid Server, you would need to pass the correct url to post data to to ServerConnector class. 

Best,
Wei

**Comment by anwzhang** [comment]
@sergiosrax a solution is provided by changing the host in this PR: https://github.com/prebid/prebid-mobile-android/pull/30
If you would like to add your own host, please submit a PR.
