### ISSUE TITLE
No way to pass down buyerid from client (Android)?

### ISSUE THREAD

**Issue by StarWindMoonCloud** [prebid/prebid-mobile-android#200]
We are integration audience network via prebid mobile. buyeruid (BidderToken) is required for this bidder
https://developers.facebook.com/docs/audience-network/overview/in-house-mediation/server-to-server/integration.

After some research, it's found that cookie-syncs is the solution
https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#cookie-syncs.

But we couldn't find a way to set below payload. 
```
{
  "user": {
    "ext": {
      "prebid": {
        "buyeruids": {
          "appnexus": "some-appnexus-id",
          "rubicon": "some-rubicon-id"
        }
      }
    }
  }
}
```

Two problems here
1. extra "data" in the payload, given below code
https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java#L1034
The payload of above one will be like below, which is not recognized by prebid server
```
{
  "user": {
    "ext": {
      "data": {
        "prebid": {
          "buyeruids": {
            "appnexus": "some-appnexus-id",
            "rubicon": "some-rubicon-id"
          }
        }
      }
    }
  }
}
```

2. to add properties to user, addUserData is the exposed interface accepting key value of string, and value will be converted into a set, which will be JSON array after serialization, then how can we add cookie-syncs payload?
https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java#L363

Not sure it's an issue or we found a wrong method, please suggest

**Comment by bszekely1** [comment]
There is no need to pass buyeruids for Android or iOS integrations . In-App traffic takes advantage of Device IDs not cookie IDs. Prebid SDK should pass this automatically to Prebid Server: https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java#L826

**Comment by StarWindMoonCloud** [comment]
@bszekely1 The problem is that some bidder (e.g. audience network) requires this parameter, which is from their SDK (https://developers.facebook.com/docs/audience-network/overview/in-house-mediation/server-to-server/integration), and it's different from device id, if there's no such flexibility, how can we do that?

**Comment by bszekely1** [comment]
I see the dilemma now. This would require integrating the FB SDK, invoking the com.facebook.ads.BidderTokenProvider.getBidderToken() method, passing it to Prebid Server (via Prebid SDK somehow), where the Audience Network bid adapter would be required to read this signal. 

We can do this today using the Data object in prebid SDK for both iOS and Android without any changes to the Prebid SDK. Here is the Android version: http://prebid.org/prebid-mobile/pbm-api/android/pbm-targeting-params-android.html#first-party-user-data

Additionally we can wrap permissions around this so only Audience Network can read this and not any other bidder.

All changes will be in Prebid Server.
