### ISSUE TITLE
Cache bids not agreed between prebid server and mobile sdk

### ISSUE THREAD

**Issue by StarWindMoonCloud** [prebid/prebid-mobile-android#201]
Encountered one problem when testing with audienceNetwork, even if bidder returns some bids, it's treated as No Bids by SDK. 
It's found that when prebid cache is not set up, bid.ext.prebid.targeting won't have hb_cache_id in the response, thus response will be treated as no bid based on the sdk code here.
https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java#L296

But in "Cache bids" section of https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md, it says below: 
Clients should not assume that these keys will exist, just because they were requested, though. If they exist, the value will be a UUID which can be used to fetch Bid JSON from Prebid Cache. They may not exist if the host company's cache is full, having connection problems, or other issues like that.

**Comment by bszekely1** [comment]
Audience Network is not a supported demand source at this time. As we look further into providing support, we can provide more details in a new ticket.
