### ISSUE TITLE
Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377

### ISSUE THREAD

**Issue by indhusiya23** [prebid/prebid-mobile-android#202]
**LOCATION :
chromium-Monochrome.aab-stable-410410173 line 24 in org.chromium.android_webview.AwDataDirLock.b()**
**EXCEPTION
java.lang.RuntimeException**
**MESSAGE
Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Lock owner net.meradio (pid 27982)**

We are getting reports for this peculiar crash reports from user. All the crashes are  reported in devices above Android 9.0. It is unable to replicate the crash from our side.  Also the crash is occurring for some weird time interval usually for 1 hour.
The prebid sdk version used is  **implementation 'org.prebid:prebid-mobile-sdk:[1,2)'**

From the crash report the crash is pointing to this line:
**PrebidServerSettings.java** line **83** in **org.prebid.mobile.PrebidServerSettings$1.run()**

It seems to be related to the new behavioural changes introduced in Android 9.0. 
https://developer.android.com/about/versions/pie/android-9.0-changes-28

Please advise if anything to be handled from our side.

Thanks in Advance!!

**Comment by avohraa** [comment]
Hi, seems like you are trying to use the WebView from different processes. In that case, if you are `doing something` in Application's onCreate, which uses the WebView. Then the second process initialization will also go through the same Application's onCreate and will try to use the Webview in the second process (which is forbidden starting from API 28).

Thus you need to check in the Application's onCreate before `doing that something` (eg Mopub.initializeSdk) for the second process.

> Code example

    if (getProcessName().equals("YOUR_FIRST_PROCESS_NAME")) {
        // do something that uses WebView
    } else {
        WebView.setDataDirectorySuffix("dir_name_no_separator")
    }

getProcessName(): https://developer.android.com/reference/android/app/Application.html#getProcessName()

> The above solution applies to API 28 and above.

Can you please try this, and let us know if that works for you.

**Comment by yoalex5** [comment]
Take a look at #97

**Comment by bszekely1** [comment]
Hi @indhusiya23, if you can please refer to #97 as Yoalex has described to determine if the issue you are seeing the same. As was left off in that issue, the problem is not with the Prebid SDK. If you feel there are some improvements or errors with the Prebid SDK please let us know.
