### ISSUE TITLE
Difficulties setting op aliases/bidfactor

### ISSUE THREAD

**Issue by CurlyBracket1990** [prebid/prebid-mobile-android#206]
Not sure if this is the right place, but me and my team are having some difficulties to implement Aliases and Bidfactor/BidCpmAdjustment in Prebid mobile.

We are using Appnexus as prebid server host and created some configs.

Our request currently looks like this (removed some unrelated parts):

`{{
    "id": "d39345e4-5620-4890-8b24-fc98cbd81578",
    "source": {
        "tid": "d39345e4-5620-4890-8b24-fc98cbd81578"
    },
    "imp": [{
        "id": "PrebidMobile",
        "secure": 1,
        "banner": {
            "format": [{
                "w": 300,
                "h": 250
            }]
        },
        "ext": {
            "prebid": {
                "storedrequest": {
                    "id": "CONFIG_ID"
                }
            }
        }
    }],
    "ext": {
        "prebid": {
            "storedrequest": {
                "id": "ACCOUNT_ID"
            },
            "cache": {
                "bids": {}
            },
            "targeting": {}
        }
    }
}`

Looking at the error we get, Did you forget an alias in request.ext.prebid.aliases, it should be added somewhere in this part:

`{{
    "ext": {
        "prebid": {
            "storedrequest": {
                "id": "ACCOUNT_ID"
            },
            "cache": {
                "bids": {}
            },
            "targeting": {},
<<<---------HERE?------------->>>
        }
    }
}`

However i can't find a method in the docs that allow me to set aliases or append it to the request before sending it.

We have also tried expanding the server config like this (worked for AMP/RTC):

`{
    "imp": [
        {
            "ext": {
                "appnexus2": {
                    "placementId": XXXX
                },
                "rubicon": {
                    "zoneId": XXXX,
                    "siteId": XXXX,
                    "accountId": XXXX
                },
                "appnexus": {
                    "placementId": XXXX
                }
            },
            "banner": {
                "format": [
                    {
                        "h": 250,
                        "w": 300
                    }
                ]
            },
            "id": "test-imp-id"
        }
    ],
    "ext": {
        "prebid": {
            "targeting": {
                "pricegranularity": {
                    "ranges": [
                        {
                            "max": 2.5,
                            "increment": 0.01,
                            "min": 0.01
                        },
                        {
                            "max": 10,
                            "increment": 0.1,
                            "min": 2.5
                        },
                        {
                            "max": 20,
                            "increment": 0.2,
                            "min": 10
                        },
                        {
                            "max": 50,
                            "increment": 0.5,
                            "min": 20
                        }
                    ],
                    "precision": 2
                }
            },
            "bidadjustmentfactors": {
                "appnexus2": 2
            },
            "aliases": {
                "appnexus2": "appnexus"
            }
        }
    },
    "id": "test-request-id"
}`

But this seems to break the config, which makes it default to the last working version.

Help is much appreciated! :)

Cheers,

Stefan

**Comment by CurlyBracket1990** [comment]
Help is still much appreciated! :)

Cheers,

Stefan

**Comment by bszekely1** [comment]
Hi @CurlyBracket1990,

There is no method in the Prebid SDK to pass alias directly. It has to be configured in the stored request per: https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#bidder-aliases

If you set an alias in the impression level stored request in Prebid Server, the stored request can expand the JSON object and it should work. I have tested it several times in the past with success.

I apologize for the slow response here. This is a community supported forum, where we attempt to make every effort to respond as quickly as possible. We welcome participation on all levels to assist in addressing questions like these or even contribute ideas or even code.
