### ISSUE TITLE
IP field missing in request

### ISSUE THREAD

**Issue by Jobeso** [prebid/prebid-mobile-android#209]
**Describe the bug**
As described in the OpenRTB standard I expected to see the `ip` key being set when making a request to the prebid server. The `device` key contains several information like `ifa` but not the IP of the user. These are the values that are currently set by the SDK.

```json
{
...
  "device": {
    "ua": "a long user agent",
    "lmt": 0,
    "make": "samsung",
    "model": "SM-G930F",
    "os": "android",
    "osv": "26",
    "h": 616,
    "w": 360,
    "pxratio": 4,
    "language": "en",
    "mccmnc": "262-1",
    "connectiontype": 1,
    "ifa": "a nice idfa"
  }
...
}

``` 

**To Reproduce**
Log a request to the prebid-server with a proxy of your choice and check the "device" section of the payload.

**Expected behavior**
Setting the ip address of the users device in the `device` section of the payload when performing the request.

**Smartphone (please complete the following information):**
The device I used to test this
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0

**Additional context**
I'm happy to help fixing this bug with some guidance. Maybe I'm also just doing something wrong. Looking forward to get feedback on this and thanks for your work on this awesome technology.

**Comment by bszekely1** [comment]
Hi @Jobeso,

This is not a bug. The current architecture for Prebid SDK is to leverage Prebid Server's IP location based on the headers of the request for both IPv4 and IPv6. Prebid Server  also determines if the IP address if a valid public IP address as well, looking through the xForwarded header to find the last public IP address.

What is the use case for a publisher to supply the IP address? This is potentially a fraud risk to allow the supplier of inventory to self-declare IP. It would be possible for someone to provide an IP that is different from the origin IP address of the user.

**Comment by Jobeso** [comment]
Hey @bszekely1,
thanks a lot for the detailed explanation. I am trying to resolve an issue with tappx. I have them integrated in the prebid-server as a bidder and they are seeing the request but don't really bid because the IP address they receive is not the clients IP address but always the same one (I suppose the prebid-server IP address). Do you have anything to point me to so I can resolve this problem? 

I also see your point why this behaviour could be a fraud risk so this is not a problem with the prebid-mobile-android sdk.

**Comment by bszekely1** [comment]
Hey @Jobeso. If their app provides authorization to use Charles Proxy (or other proxy tool) to see the calls going out to PBS you can use the Prebid SKD pbsDebug flag: https://docs.prebid.org/prebid-mobile/pbm-api/ios/prebidmobile-object-ios.html

You can follow the path of where the IP comes from, what Prebid Server is doing and what the bid adapters see.

**Comment by bszekely1** [comment]
If you are able to reproduce this, what you can do is log a ticket in the PBS github page and I can follow up. I have not heard any reports from any of our partners having this issue, although we are using Prebid Server Java that hopefully does not have a different behavior from Prebid Server GO.

**Comment by Jobeso** [comment]
Hey @bszekely1,
thanks for giving some guidance. When debugging prebid-server I saw the "ip" field being set. The vendor still sees these errors. I'm trying to find out if they also cover the "ipv6" field. I don't see that this is a problem of the prebid-server. I'll open an issue when I find out otherwise.

Thanks a lot for your help.
