### ISSUE TITLE
Migrate annotations to AndroidX

### ISSUE THREAD

**Issue by Naitbit** [prebid/prebid-mobile-android#219]
**Is your feature request related to a problem? Please describe.**
Relates to https://github.com/prebid/prebid-mobile-android/issues/153

**Describe the solution you'd like**
Replace `com.android.support:support-annotations:28.0.0`
with `androidx.annotation:annotation:1.0.0`
https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/shared-build.gradle#L41

**Comment by yoalex5** [comment]
Hello @Naitbit 

The reason that we have not migrated to `AndroidX` is backward compatibility. 
If publisher's app uses `support` library it is not possible  use PrebidSDK with `AndroidX`

What do you think ?

**Comment by Naitbit** [comment]
Currently it seems that one cannot turn of Jetifier in Android project when using prebid dependency.
It is possible that slower build time is preferable to not being able to build project at all, but android.support libraries are not supported since [September 2018](https://developer.android.com/topic/libraries/support-library/revisions#september-21,-2018), so probably most projects have migrated already.

That said libraries that were migrating to AndroidX were often bumping the major version to indicate this incompatibility (fe: https://github.com/JakeWharton/RxBinding/blob/master/CHANGELOG.md#version-300-2019-07-23 )

**Comment by yoalex5** [comment]
Since Google doesn't force using AndroidX but only [recommend](https://developer.android.com/topic/libraries/support-library) it is still possible that some of publishers use `support` and want to have the latest updates of `PrebidSDK`

@bszekely1, what do you think ?

**Comment by bszekely1** [comment]
I would agree with @yoalex5 that publishers would build using the support library. This would be a breaking change for publishers with little gain in doing so.

**Comment by navigajesper** [comment]
Now that a year has passed, would it be possible to revisit this issue?

I would really like to be able to disable Jetifier.

**Comment by YuriyVelichkoPI** [comment]
@ValentinPostindustria, please, take a look at this request. Does the rendering codebase require AndroidX?
