### ISSUE TITLE
Demand Partner

### ISSUE THREAD

**Issue by annaadv7** [prebid/prebid-mobile-android#230]
Hi,

What does a demand partner need to implement in order to start using the header bidding with its suppliers in IOS Apps?

Thanks,

**Comment by bszekely1** [comment]
Hello @annaadv7,

You would need to add your company as a bidder in Prebid Server. You can follow the steps here:https://github.com/prebid/prebid-server-java/blob/master/docs/developers/add-new-bidder.md

This is the client-side code called prebid SDK to communicate with Prebid Server's bidder demand.
