### ISSUE TITLE
New Bidder

### ISSUE THREAD

**Issue by annaadv7** [prebid/prebid-mobile-android#232]
Hi,

Does a company need to pay a fee In order to be a bidder (Android/IOS apps)?

Thanks,

**Comment by bszekely1** [comment]
HI @annaadv7, there is no fee to build a bid adapter. Prebid SDK uses Prebid Server as a demand source. Here is the documentation for adding a Prebid Server bid adapter: https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html
