### ISSUE TITLE
Support Class renames for play-services-ads SDK v20

### ISSUE THREAD

**Issue by aielcbmDev** [prebid/prebid-mobile-android#235]
I am doing the changes required to [prepare for the update to play-services-ads SDK 20](https://developers.google.com/ad-manager/mobile-ads-sdk/android/migration). One of those changes involves replacing the following classes:

- com.google.android.gms.ads.doubleclick.PublisherAdRequest
- com.google.android.gms.ads.doubleclick.PublisherAdRequest$Builder

with these:

- com.google.android.gms.ads.admanager.AdManagerAdRequest
- com.google.android.gms.ads.admanager.AdManagerAdRequest$Builder

There is logic in the [Prebid SDK](https://github.com/prebid/prebid-mobile-android/releases/tag/1.9) that [checks what classes are used to load ads](https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java) (fetchDemand method) that returns ResultCode.INVALID_AD_OBJECT. 

That check is performed in the "[org.prebid.mobile.Util](https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java)" class, _supportedAdObject_ method, where those 2 classes full class name is hardcoded in "AD_MANAGER_REQUEST_CLASS" and "AD_MANAGER_REQUEST_BUILDER_CLASS".

Is there any plan to support this change in the near future?

Many thanks!

**Comment by aielcbmDev** [comment]
I have found that there is another fetchDemand method that uses OnCompleteListener2 that does not check the Ad Manager  classes names and now everything seems to work fine.

**Comment by yoalex5** [comment]
Hello @aielcbmDev,

Thanks for reporting this issue. You are right you can use `OnCompleteListener2` and manually set targeting keys into AdManager(or any others AdServer SDK). 

As for the issue, we know about breaking changes and we will start working on it when Google release v20
https://developers.google.com/ad-manager/mobile-ads-sdk/android/rel-notes
