### ISSUE TITLE
Could not resolve all artifacts for configuration

### ISSUE THREAD

**Issue by rochapablo** [prebid/prebid-mobile-android#239]
## Type of issue
Not exactly a issue. 

## Description
I'm building an Android Library and I'm trying to add Prebid as dependency. Since it's the first time, I'm not sure if I'm doing right, but this is what I'm trying to do:

**build.gradle**
```
buildscript {
    ...
    repositories {
        ...
    }
    dependencies {
        ...
        classpath 'org.prebid:prebid-mobile-sdk:1.10'
    }
}
```

```
A problem occurred configuring root project 'MyLib'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.prebid:prebid-mobile-sdk:1.10.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/prebid/prebid-mobile-sdk/1.10/prebid-mobile-sdk-1.10.pom
       - https://jcenter.bintray.com/org/prebid/prebid-mobile-sdk/1.10/prebid-mobile-sdk-1.10.pom
       - https://plugins.gradle.org/m2/org/prebid/prebid-mobile-sdk/1.10/prebid-mobile-sdk-1.10.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Due the error, I believe that I must add org.prebid:prebid-mobile-sdk repository inside `buildscript.repositories.maven.url`. If so, is that possible? Can I have the repo url?

**Comment by yoalex5** [comment]
Hello @rochapablo

Please use next code
```
dependencies {
    implementation 'org.prebid:prebid-mobile-sdk:1.10'
}
```

replace `classpath` by `implementation` in `dependencies` block

**Comment by rochapablo** [comment]
Hello @yoalex5 

I tried but got the following error

```
Build file 'mylib/build.gradle' line: 29

A problem occurred evaluating root project 'MyLib'.
> Could not find method implementation() for arguments [org.prebid:prebid-mobile-sdk:1.10] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**build.gradle (MyLib)**
```
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {        
        implementation 'org.prebid:prebid-mobile-sdk:1.10'
    }
}
```

**Comment by yoalex5** [comment]
There  are several `build.gradle` files in a project
I  suppose that  you try to modify a project one but you should add `implementation` inside  module `build.gradle`

Please take a look at [PrebidDemoJava](https://github.com/prebid/prebid-mobile-android/blob/master/Example/PrebidDemoJava/build.gradle) example

**Comment by rochapablo** [comment]
Yes, I have two `build.gradle`, one in the `root` and another one in the `MyLib` folder.

```
- root
-- build.gradle
- MyLib
-- build.gradle
```

Following the example I also get the following error

```
Could not resolve org.prebid:prebid-mobile-sdk:1.10.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Just to be clear, I know that adding `implementation` in the app (not in the lib) it will work, but the idea it's include Prebid as dependency of MyLib. I'm just saying this because I'm not sure it's the same type of implementation.

**Comment by yoalex5** [comment]
try to use 

```
implementation 'org.prebid:prebid-mobile-sdk:1.9'
```

**Comment by rochapablo** [comment]
I tried `implementation` in all possible ways, did not work. Then I tried `classpath 'org.prebid:prebid-mobile-sdk:1.9'` the build worked. I'm going to install MyLib in a demoApp and see if worked. Just a second

**Comment by rochapablo** [comment]
Unfortunately it didn't work. I see MyLib as External Libraries but nothing about `org.prebid`. Also following the example and importing `org.prebid.mobile.Host;` it says `package org.prebid.mobile does not exist`

**Comment by yoalex5** [comment]
If you have next chain 
```
App - library1 - library2
```

use `api` instead of `implementation`

**Comment by rochapablo** [comment]
Using `api` gives me the same errors. I'm thinking about create my own Pebid Artifact just to see if it will work.

**Comment by rochapablo** [comment]
After long hours now I can see `org.prebid.mobile` as dependency. Using the the following blocks did work.

```
dependencies {
    implementation 'org.prebid:prebid-mobile-sdk:1.9'
}
```

```
jar {
    from {
        configurations.runtimeClasspath.filter{ it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```
