### ISSUE TITLE
Crash reports java.lang.InternalError Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by vlastachu** [prebid/prebid-mobile-android#240]
Our users experiencing crashes, which looks like happens at the application close. Not sure if it is real crash or unavailability to correctly close the app.

There is stack trace:

```
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start (Thread.java:733)
java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1382)
android.os.AsyncTask$SerialExecutor.scheduleNext (AsyncTask.java:258)
android.os.AsyncTask$SerialExecutor.execute (AsyncTask.java:252)
android.os.AsyncTask.executeOnExecutor (AsyncTask.java:651)
android.os.AsyncTask.execute (AsyncTask.java:595)
org.prebid.mobile.PrebidServerAdapter.requestDemand (PrebidServerAdapter.java:73)
org.prebid.mobile.DemandFetcher$RequestRunnable$1.run (DemandFetcher.java:179)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:280)
android.os.HandlerThread.run (HandlerThread.java:65)
```

![users environment](https://user-images.githubusercontent.com/527307/109841701-fdf7c200-7c51-11eb-91ea-486c0ea637c5.png)

Crashes appear since prebid 1.4, our current version 1.6

**Comment by bszekely1** [comment]
Hi @vlastachu, do you have an app that can be downloaded and tested? Also, is this occurring every time the app is closed?

**Comment by yoalex5** [comment]
JFYI `AsyncTask` was  replaced by [executors](#228) in PrebidS SDK v1.10

**Comment by bszekely1** [comment]
@vlastachu , can you please retest this with executors and report back. We will be closing the issue if we no longer hear back.
