### ISSUE TITLE
AdViewUtils.findNativeInMoPubNativeAd reflection issues

### ISSUE THREAD

**Issue by KostiantynTselykh** [prebid/prebid-mobile-android#241]
**Describe the bug**
`AdViewUtils.findNativeInMoPubNativeAd` is using reflection to access MoPub Native Ad extras. See the following code snippet:
```
    private static void findNativeInMoPubNativeAd(@NonNull Object object, @NonNull PrebidNativeAdListener listener) {
        Object baseNativeAd = callMethodOnObject(object, "getBaseNativeAd");
        LogUtil.d("Prebid", "" + baseNativeAd);
        Boolean isPrebid = (Boolean) callMethodOnObject(baseNativeAd, "getExtra", "isPrebid");
        if (isPrebid != null && isPrebid) {
            String cacheId = (String) callMethodOnObject(baseNativeAd, "getExtra", "hb_cache_id_local");
            //.........
            }
     //.......
    }
```
However the baseNativeAd doesn't have the `getExtra` method which reflection is relying on. As a result `findNativeInMoPubNativeAd` will never determine if Prebid has won or not.

**To Reproduce**
You can write a unit test / run XandrNativeInAppMoPubDemoActivity example (with correct inventory setup) on an emulator to reproduce the mentioned behavior. 

**Expected behavior**
`findNativeInMoPubNativeAd` is properly determining that prebid has won and is returning a PrebidNativeAd (if cacheId is valid).

**Screenshots**
See MoPub NativeAd and BaseNativeAd class structure:
<img width="397" alt="Screenshot 2021-03-03 at 19 14 51" src="https://user-images.githubusercontent.com/79995965/109844716-13bab680-7c55-11eb-9a07-e847b3e28f4e.png">
<img width="401" alt="Screenshot 2021-03-03 at 19 15 05" src="https://user-images.githubusercontent.com/79995965/109844729-14ebe380-7c55-11eb-85a3-b90bc1ade513.png">

**Desktop:**
 - OS: macOS BigSur 11.2.1

**Smartphone:**
 - Any device or emulator

**Additional context**
I'm not sure how to access MoPub extras after receiving the nativeAd response. MoPub NativeAd doesn't store extras (even privately).

**Comment by ValentinPostindustria** [comment]
MoPub is no longer supported.
