### ISSUE TITLE
Inapp Header bidding 

### ISSUE THREAD

**Issue by annaadv7** [prebid/prebid-mobile-android#252]
Hi,

If our company can receive openrtb requests and send openrtb responses, do we need to implement the adaptor in the same way Or in a different way?

Thank you

**Comment by bszekely1** [comment]
Hello @annaadv7, 

Prebid SDK uses Prebid Server as a means for bidding (i.e. demand for ads). From your description, it sounds like you would like to build a bidder in Prebid Server. Prebid Server is built in two languages, Java and Go. For instructions to build a bid adapter, please reference the below links:

- [Java](https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html)
- [GO](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html)

**Comment by annaadv7** [comment]
Hi bszekely1,

Could you please confirm whether we still need to implement the Adaptor (if we can read openrtb Requests)or not?
if yes, Does this mean that we have the choice between implementing the Prebid Adaptor in Java Or Go?

Thanks,


> Hello @annaadv7,
> 
> Prebid SDK uses Prebid Server as a means for bidding (i.e. demand for ads). From your description, it sounds like you would like to build a bidder in Prebid Server. Prebid Server is built in two languages, Java and Go. For instructions to build a bid adapter, please reference the below links:
> 
>     * [Java](https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html)
> 
>     * [GO](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html)

**Comment by bszekely1** [comment]
Prebid Server supports OpenRTB with some custom extensions that are used for various features such as rewarded video and other items like bidder parameters. Yes, you can build an adapter in either Go or Java, or both. The advantage to doing both is that host providers in either platform can use your bid adapter for demand.

**Comment by annaadv7** [comment]
Hi,

We would like to implement the adaptor in java as per the specs that are in [](https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html). Could you please confirm that this adaptor(developed in java) will work with all the supply partners?

If we need to implement an additional part (except for the details of  https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html), could you please share with me the link to the specs?

Thanks,

**Comment by bszekely1** [comment]
> Could you please confirm that this adaptor(developed in java) will work with all the supply partners?

yes, Prebid Server will format the request it receives for an ad to bid adapters in the same method, so long as all your supply partners are able to a valid request to Prebid Server for a request. This is done by using either Prebid SDK or calling PBS directly.
