### ISSUE TITLE
GDPR Values issues

### ISSUE THREAD

**Issue by 3bdev** [prebid/prebid-mobile-android#262]
Hi prebid team.

We're facing an issue with SSPs regarding the GDPR values.

We use Iubenda as CMP on our mobile app, but even if Iubenda respect the IAB Framework and saves all the GDPR values in NSUserDefaults iOS and  default SharedPreferences on Android those SSPs tell us there's no sign of those values been sent.

But considering this documentation the PREBID SDK should do the job.
https://docs.prebid.org/prebid-mobile/privacy-regulation.html

We double checked both on iOS and Android and Iubenda saves those data correctly.
One of those SSPs is The Media Grid.

Is there a way to debug why the Prebid SDK cannot read the values from our CMP?

**Comment by TheMediaGrid** [comment]
Hi Prebid team,
Confirming there is an issue here. We're used to regularly getting consent (when the CMP is on the page) for our Prebid Server integrations however in this case we are not getting neither the regs object nor the consent string param at all.

**Comment by maddapper** [comment]
@3bdev as far as being able to read Prebid SDK GDPR values, those are accessible in the **_TargetingParams.getGDPRConsentString_** method.  I can add some unit testing around those GDPR methods to help with gaining more insight to what is happening on device.  Are you using **_TargetingParams.setGDPRConsentString_** or any setter related GDPR API methods on **_TargetingParams_**?   If so, I believe there could be potential for conflict between that and your CMP.  Specifically, if consent string is empty, Prebid SDK [falls back to](https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java#L134) using it's own internal custom keys based on values that were set via **_TargetingParams_** API which can lead to the kind of discrepancies you are seeing.

**Comment by andreapernici** [comment]
Yes those values are correctly populated when we check with getters.

Infact we don't set those cause they are already managed correctly on shared prefs by our CMP.

We consider our implementation right cause we followed the documentation the same way as iOs and on iOs looks like It Is working.

Maybe there is something missing on the SDK side or on the media grid side.

**Comment by 3bdev** [comment]
Just to be more clearer.
We simply do this 

```
private void prebid() {
        PublisherAdRequest request = adRequest.build();

        PrebidMobile.setPrebidServerAccountId(Const.PREBID_SERVER_ACCOUNT_ID);
        PrebidMobile.setPrebidServerHost(Host.APPNEXUS);
        PrebidMobile.setApplicationContext(App.getContext());

        //PreBID
        if (ArrayUtils.contains(adSizes, AdSize.MEDIUM_RECTANGLE) &&
                App.getSharedPrefs().getBoolean(Const.FIREBASE_ENABLE_PREBID, Const.FIREBASE_ENABLE_PREBID_DEFAULT)) {
            // Banner 300
            org.prebid.mobile.BannerAdUnit bannerAdUnit = new org.prebid.mobile.BannerAdUnit(Const.PREBID_300_CONFIG_ID, AdSize.MEDIUM_RECTANGLE.getWidth(), AdSize.MEDIUM_RECTANGLE.getHeight());
            bannerAdUnit.fetchDemand(request, resultCode ->
                    adView.loadAd(request)
            );
        } else if (ArrayUtils.contains(adSizes, AdSize.BANNER) &&
                App.getSharedPrefs().getBoolean(Const.FIREBASE_ENABLE_PREBID, Const.FIREBASE_ENABLE_PREBID_DEFAULT)) {
            // Banner sticky
            org.prebid.mobile.BannerAdUnit bannerAdUnit = new org.prebid.mobile.BannerAdUnit(Const.PREBID_320x50_CONFIG_ID, AdSize.BANNER.getWidth(), AdSize.BANNER.getHeight());
            bannerAdUnit.fetchDemand(request, resultCode ->
                    adView.loadAd(request)
            );
        }
        else {
            // Other cases
            adView.loadAd(request);
        }
    }
```

**Comment by 3bdev** [comment]
Hi all.

Do you have some feedback?

The media grid staff worte us this (now including also iOS app) and now suddenly without us doing anything seems they are missing only some parts of the hits.

`It seems to be that around half of the traffic from ios and still a sufficient part of one from android ends up in bad requests as we get an error when trying to parse your json. More precisely, we get the following error: "request has an app object but is lacking device.ifa field". This is a crucial field for us and we can't send over the requests to the advertisers without it. Can you please look into it and always send it to us?`

But I don't think the media grid team has a clear idea on how the SDK works. We have no way to force parameters or other stuff. The SDK behave on it's own based on the value saved by the CMP.

Can you please shed some light on how things work? Cause there's nothing we can do on the app side.

**Comment by maddapper** [comment]
@3bdev, the implementation code you shared looks correct, so assuming the CMP is writing values to the SharedPreferences, media grip should be seeing the GDPR consent string (v2) in the user object.  That's assuming the user is [subject to GDPR](https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java#L930), if the user isn't subject to GDPR then no consent string is sent in the request.  As far as IDFA, I believe Apple has deprecated that due to privacy reasons, so what you are seeing now on iOS might be the result of that [Apple's policy change](https://www.forbes.com/sites/johnkoetsier/2020/09/03/idfa-stay-of-execution-apple-delays-new-ios-14-privacy-measures-until-2021/?sh=7a7c63d1569f).  I suggest opening an issue with the [prebid mobile ios](https://github.com/prebid/prebid-mobile-ios/issues) to get a better understanding of the issues related to IDFA on iOS.  As far as IDFA on Android, I believe that depends on user consent, LMT and GDPR, so it is expected that some users will have opted out of sharing their device id.

**Comment by 3bdev** [comment]
Thanks @maddapper I also believe our implementation is correct. 

I think @TheMediaGrid issue is not related to the app not sending values. I also believe that it's ok to have a percentage of user not giving consent.

**Comment by maddapper** [comment]
I looked at a few other API's from different vendor(s) and it seems that most expect IFA field to be optional, see [here](https://developers.smaato.com/demand-partners/openrtb-2-4-specifications/) and [here](https://protocol.bidswitch.com/standards/device-object.html).  One other thing to keep in mind is that your PBS host (App Nexus?) has it's own server-side configuration on how it treats privacy related fields.  I wouldn't think your PBS host would strip out _ifa_ or _reg_ related fields in the client request, but it might be a good idea to validate up the food chain as well.    My expectation is that PBS should just pass through and enrich whatever is in the client bid request, not exclude or filter out those details.

**Comment by TheMediaGrid** [comment]
Team, I think it's wrong to mess up IFA and GDPR integrations. This ticket was initially open for GDPR issues on Android iOS for 3bmeteo app, let's keep it for this purposes. 

We have other app integrations and we're seeing consent signals being passed as part of regs object for PBS therefore we are sure there is something wrong with the consent is being passed from 3bmeteo to MediaGrid. 

To @maddapper's words- what is the easiest way to check whether regs object isn't stripped out of the request on the specific PBS' host side?

**Comment by andreapernici** [comment]
I'm not sure what is really happening here and I can only guess. From my point of view there's nothing more I can do if not follow the SDK specs.

It's not clear to me what's going on cause I don't know the full stack.

If there something more we can do to help please tell us what to do. Is in the interest of all to fix the issue if an issue exists.

We checked various times the CMP values and their always populated on various devices and OSs' versions. Both on Android and iOS.

**Comment by maddapper** [comment]
> We checked various times the CMP values and their always populated on various devices and OSs' versions. Both on Android and iOS.

Even in the case of user opt out?

**Comment by maddapper** [comment]
> I'm not sure what is really happening here and I can only guess. From my point of view there's nothing more I can do if not follow the SDK specs.

@andreapernici correct, based on the example code you shared, i don't see anything wrong with the client-side app or SDK.  In addition, i double checked the unit tests and it is generating GDPR signals, for example:  `  },
  "user": {
    "gender": "O",
    "ext": {
      "consent": "testconsent TCFv2"
    }
  },
  "regs": {
    "ext": {
      "gdpr": 1
    }
  },`

Are you sure your CMP is TCF v2 compliant?  Are you sure the user is, actually, being presented with a CMP UI?  On strange thing about the way Prebid Android SDK implemented CMP is that it first checks the values for PB GDPR rather than IAB GDPR, so if for some reason in the past, you had been setting PB GDPR values that would stay persistent and override IAB GDPR.  In addition, there is business logic that checks for IAB TCF v2 first, then TCF v1.  I'm going to assume your CMP writes both TCF v2 and TCF v1, if not there might be explanation for some of the inconsistent behavior you are seeing.

**Comment by 3bdev** [comment]
As far as I can tell you Iubenda is listed from IAB ![iubenda](https://user-images.githubusercontent.com/65214285/120603776-a6cddd00-c44c-11eb-87ad-44da340f9fbd.png).

Consider that not all the users update apps on Android. We have more than 3mln active users and only 2mln updated to the latest version. There are also version frozen at a versione with Android4 and other specific only for Huawei HMS.

I honestly don't know, but I think it's normal to have some faulty users considering the Android Ecosystem.

Maybe you should try to check in some way if those wrong request are coming from some specific category of devices or app versions.

I don't know the percentage of failing requests, but I think that 15% 20% should be pretty normal.

**Comment by 3bdev** [comment]
We made some more testing together with the Iubenda team and we can confirm that the CMP correctly set all the values even in case of partial consent or refusal.

**Comment by maddapper** [comment]
@3bdev and @andreapernici could you run a simple test and post the log info?  You will need to set the log level to debug, start your app, start the lubenda CMP and make the appropriate opt-ins, then run an ad request.  In the log you should see the auction payload.  If your auction payload contains this section, it means your consent string is being passed to the PB host: `}, "user": { "gender": "O", "ext": { "consent": "xxxxxxxxxxx" } }, "regs": { "ext": { "gdpr": 1 } }`

**Comment by 3bdev** [comment]
Here I simply opened the app without reinstalling. Looks like the consent is there

`2021-06-04 08:50:31.345 21753-23035/com.Meteosolutions.Meteo3b D/PrebidMobile: Sending request for auction 9a342a2e-2782-4628-8da7-c0c565ba2811 with post data: {"id":"c98cc24a-e0d1-44cf-b04d-eff3edbb1d23","source":{"tid":"c98cc24a-e0d1-44cf-b04d-eff3edbb1d23"},"imp":[{"id":"PrebidMobile","secure":1,"banner":{"format":[{"w":320,"h":50}]},"ext":{"prebid":{"storedrequest":{"id":"2594d8f2-76b3-4e5e-bdd0-83966b977409"}}}}],"device":{"make":"OnePlus","model":"IN2023","ua":"Mozilla\/5.0 (Linux; Android 11; IN2023 Build\/RP1A.201005.001; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/91.0.4472.77 Mobile Safari\/537.36","lmt":0,"ifa":"472e5d6c-0759-4c0b-9d26-3e7104266e5a","os":"android","osv":"30","language":"it","w":384,"h":807,"pxratio":2.8125,"mccmnc":"222-99","carrier":"WINDTRE","connectiontype":1},"app":{"bundle":"com.Meteosolutions.Meteo3b","ver":"4.4.6 debug","name":"3BMeteo","publisher":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"ext":{"prebid":{"source":"prebid-mobile","version":"1.11"}}},"user":{"gender":"O","ext":{**"consent"**:"CPGpBw9PGw7ZSB7D9CITBaCsAP_AAH_AAAAAH0Nf_X__b39j-_59__t0eY1f9_7_v-wzjhfdt-8N2PvX_L8X42M7PF36pq4KuR4Eu3LBIQNlHOHUTUmw6okVrTPsak2Mr7NKJ7LEinMbe2dYGHtfn91TuZKY7_78_9fz__-v_v___9f3r-3_3__59X---_e_V399zLv9__3__A-UAkw1L4ALsSxwZJo0qhRAhCsJDoBQAUUAwtE1hAwsCnZXAR6ggYAITUBGBECDEFGLAIABAIAkIiAkAPBAIgCIBAACAFSAhAARMAgsALAwCAAUA0LECKAIQJCDI4KjlMCAiRaKCeysASi72NMIQyiwAoFH9FRgIlCCBYGQkLAA"}},"regs":{"ext":{"gdpr":1}},"ext":{"prebid":{"storedrequest":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"cache":{"bids":{}},"targeting":{}}}}`


`2021-06-04 08:50:31.352 21753-23032/com.Meteosolutions.Meteo3b D/PrebidMobile: Sending request for auction 624a1c6d-7d20-434b-9fb1-c4b511e43a69 with post data: {"id":"8753eb6d-05f5-4e11-8593-c7132f1b0a74","source":{"tid":"8753eb6d-05f5-4e11-8593-c7132f1b0a74"},"imp":[{"id":"PrebidMobile","secure":1,"banner":{"format":[{"w":300,"h":250}]},"ext":{"prebid":{"storedrequest":{"id":"9ff87393-7e46-4e20-aa8d-8b9a2bcc129c"}}}}],"device":{"make":"OnePlus","model":"IN2023","ua":"Mozilla\/5.0 (Linux; Android 11; IN2023 Build\/RP1A.201005.001; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/91.0.4472.77 Mobile Safari\/537.36","lmt":0,"ifa":"472e5d6c-0759-4c0b-9d26-3e7104266e5a","os":"android","osv":"30","language":"it","w":384,"h":807,"pxratio":2.8125,"mccmnc":"222-99","carrier":"WINDTRE","connectiontype":1},"app":{"bundle":"com.Meteosolutions.Meteo3b","ver":"4.4.6 debug","name":"3BMeteo","publisher":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"ext":{"prebid":{"source":"prebid-mobile","version":"1.11"}}},"user":{"gender":"O","ext":{**"consent"**:"CPGpBw9PGw7ZSB7D9CITBaCsAP_AAH_AAAAAH0Nf_X__b39j-_59__t0eY1f9_7_v-wzjhfdt-8N2PvX_L8X42M7PF36pq4KuR4Eu3LBIQNlHOHUTUmw6okVrTPsak2Mr7NKJ7LEinMbe2dYGHtfn91TuZKY7_78_9fz__-v_v___9f3r-3_3__59X---_e_V399zLv9__3__A-UAkw1L4ALsSxwZJo0qhRAhCsJDoBQAUUAwtE1hAwsCnZXAR6ggYAITUBGBECDEFGLAIABAIAkIiAkAPBAIgCIBAACAFSAhAARMAgsALAwCAAUA0LECKAIQJCDI4KjlMCAiRaKCeysASi72NMIQyiwAoFH9FRgIlCCBYGQkLAA"}},"regs":{"ext":{"gdpr":1}},"ext":{"prebid":{"storedrequest":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"cache":{"bids":{}},"targeting":{}}}}`


`2021-06-04 08:50:31.374 21753-23054/com.Meteosolutions.Meteo3b D/PrebidMobile: Sending request for auction 53718985-b00e-43cc-9f4d-f78633a162a3 with post data: {"id":"948899e7-20ec-4c6d-a28d-c52055122fa5","source":{"tid":"948899e7-20ec-4c6d-a28d-c52055122fa5"},"imp":[{"id":"PrebidMobile","secure":1,"banner":{"format":[{"w":320,"h":50}]},"ext":{"prebid":{"storedrequest":{"id":"2594d8f2-76b3-4e5e-bdd0-83966b977409"}}}}],"device":{"make":"OnePlus","model":"IN2023","ua":"Mozilla\/5.0 (Linux; Android 11; IN2023 Build\/RP1A.201005.001; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/91.0.4472.77 Mobile Safari\/537.36","lmt":0,"ifa":"472e5d6c-0759-4c0b-9d26-3e7104266e5a","os":"android","osv":"30","language":"it","w":384,"h":807,"pxratio":2.8125,"mccmnc":"222-99","carrier":"WINDTRE","connectiontype":1},"app":{"bundle":"com.Meteosolutions.Meteo3b","ver":"4.4.6 debug","name":"3BMeteo","publisher":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"ext":{"prebid":{"source":"prebid-mobile","version":"1.11"}}},"user":{"gender":"O","ext":{**"consent"**:"CPGpBw9PGw7ZSB7D9CITBaCsAP_AAH_AAAAAH0Nf_X__b39j-_59__t0eY1f9_7_v-wzjhfdt-8N2PvX_L8X42M7PF36pq4KuR4Eu3LBIQNlHOHUTUmw6okVrTPsak2Mr7NKJ7LEinMbe2dYGHtfn91TuZKY7_78_9fz__-v_v___9f3r-3_3__59X---_e_V399zLv9__3__A-UAkw1L4ALsSxwZJo0qhRAhCsJDoBQAUUAwtE1hAwsCnZXAR6ggYAITUBGBECDEFGLAIABAIAkIiAkAPBAIgCIBAACAFSAhAARMAgsALAwCAAUA0LECKAIQJCDI4KjlMCAiRaKCeysASi72NMIQyiwAoFH9FRgIlCCBYGQkLAA"}},"regs":{"ext":{"gdpr":1}},"ext":{"prebid":{"storedrequest":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"cache":{"bids":{}},"targeting":{}}}}`


`2021-06-04 08:50:31.547 21753-23066/com.Meteosolutions.Meteo3b D/PrebidMobile: Sending request for auction 783c7e75-478c-4a6b-b2cf-b48c02203b8e with post data: {"id":"a8ede819-3725-4a75-915a-31a923b3fd0c","source":{"tid":"a8ede819-3725-4a75-915a-31a923b3fd0c"},"imp":[{"id":"PrebidMobile","secure":1,"banner":{"format":[{"w":300,"h":250}]},"ext":{"prebid":{"storedrequest":{"id":"9ff87393-7e46-4e20-aa8d-8b9a2bcc129c"}}}}],"device":{"make":"OnePlus","model":"IN2023","ua":"Mozilla\/5.0 (Linux; Android 11; IN2023 Build\/RP1A.201005.001; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/91.0.4472.77 Mobile Safari\/537.36","lmt":0,"ifa":"472e5d6c-0759-4c0b-9d26-3e7104266e5a","os":"android","osv":"30","language":"it","w":384,"h":807,"pxratio":2.8125,"mccmnc":"222-99","carrier":"WINDTRE","connectiontype":1},"app":{"bundle":"com.Meteosolutions.Meteo3b","ver":"4.4.6 debug","name":"3BMeteo","publisher":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"ext":{"prebid":{"source":"prebid-mobile","version":"1.11"}}},"user":{"gender":"O","ext":{**"consent"**:"CPGpBw9PGw7ZSB7D9CITBaCsAP_AAH_AAAAAH0Nf_X__b39j-_59__t0eY1f9_7_v-wzjhfdt-8N2PvX_L8X42M7PF36pq4KuR4Eu3LBIQNlHOHUTUmw6okVrTPsak2Mr7NKJ7LEinMbe2dYGHtfn91TuZKY7_78_9fz__-v_v___9f3r-3_3__59X---_e_V399zLv9__3__A-UAkw1L4ALsSxwZJo0qhRAhCsJDoBQAUUAwtE1hAwsCnZXAR6ggYAITUBGBECDEFGLAIABAIAkIiAkAPBAIgCIBAACAFSAhAARMAgsALAwCAAUA0LECKAIQJCDI4KjlMCAiRaKCeysASi72NMIQyiwAoFH9FRgIlCCBYGQkLAA"}},"regs":{"ext":{"gdpr":1}},"ext":{"prebid":{"storedrequest":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"cache":{"bids":{}},"targeting":{}}}}`

**Comment by maddapper** [comment]
@3bdev i don't see an app or SDK bug since you are seeing the GDPR signals in your setup.  not sure what else to advise you other than to add more metrics surrounding your CMP opt-ins or opt-outs and track version info.

**Comment by maddapper** [comment]
sorry accidentally closed this, i re-opened to allow feedback

**Comment by maddapper** [comment]
@bszekely1 so far does not look like an issue on the client side.  i'm going to propose we close it for now unless anyone else objects to that.

**Comment by bszekely1** [comment]
If the OP no longer experiences the issue, or is not able to produce a STR we can close it. Lets wait until the OP can confirm.

**Comment by TheMediaGrid** [comment]
We are unfortunately still experiencing the issue, so we'd appreciate if it stays open. 

One new detail is that by the end of yesterday we saw two request coming in from @3bdev with the gdpr consent, both attributed to the devices with 4.4.6 debug version of the app. So not only in theory, but also in practice the consent can be passed all the way to us, the question though still remains why is not.

**Comment by 3bdev** [comment]
@maddapper is it a normal behaviour that the non debug version of the app in the log files send this without the GDPR part?

Does the SDK only send those values when in debug mode? 

`2021-06-08 17:08:27.259 30814-22035/? D/PrebidMobile: Sending request for auction 2cc7a358-d93b-4a3a-a6c1-b905a54c4cca with post data: {"id":"91e45c19-43d3-408c-a447-61953f9b708e","source":{"tid":"91e45c19-43d3-408c-a447-61953f9b708e"},"imp":[{"id":"PrebidMobile","secure":1,"banner":{"format":[{"w":300,"h":250}]},"ext":{"prebid":{"storedrequest":{"id":"9ff87393-7e46-4e20-aa8d-8b9a2bcc129c"}}}}],"device":{"make":"OnePlus","model":"IN2023","ua":"Mozilla\/5.0 (Linux; Android 11; IN2023 Build\/RP1A.201005.001; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/91.0.4472.88 Mobile Safari\/537.36","lmt":0,"ifa":"472e5d6c-0759-4c0b-9d26-3e7104266e5a","os":"android","osv":"30","language":"it","w":384,"h":807,"pxratio":2.8125,"mccmnc":"222-99","carrier":"WINDTRE","connectiontype":1},"app":{"bundle":"com.Meteosolutions.Meteo3b","ver":"4.4.6","name":"3BMeteo","publisher":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"ext":{"prebid":{"source":"prebid-mobile","version":"1.11"}}},"user":{"gender":"O"},"ext":{"prebid":{"storedrequest":{"id":"67e7b2e4-4db4-4f6f-b162-e3fc8ba402a1"},"cache":{"bids":{}},"targeting":{}}}}`

**Comment by 3bdev** [comment]
Is there any known issue with prebid and one of the following 3 compiling rules?

-             minifyEnabled true
-             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
-             zipAlignEnabled true

**Comment by maddapper** [comment]
> Does the SDK only send those values when in debug mode?

@3bdev debug mode should have no affect on whether consent is passed.  It's strange that you were seeing consent before but not seeing consent being passed now.

> Is there any known issue with prebid and one of the following 3 compiling rules?

Not that I'm aware, but if you find a reproducible bug there let us know.

**Comment by 3bdev** [comment]
I just found this searching on google

https://docs.prebid.org/prebid-mobile/legacy/android/code-integration-android.html#proguard-support

So I'm pretty sure the issue is Proguard. We don't have the code suggested in the proguard file.

**Comment by 3bdev** [comment]
Looks like the issue is related to the Proguard Minify and the CMP SDK.

We forwarded the issue to Iubenda.

**Comment by 3bdev** [comment]
@TheMediaGrid can you please confirm that the issue is only on Android?

Or you see the same issue on iOS even if this task is only related to Android. Just to confirm that we need to check only Android.

**Comment by TheMediaGrid** [comment]
@3bdev Yes, we can confirm that the issue is only related to Android. We see maybe up to 0.5 % of the traffic on IOS without consent, but that is not a problem at all

**Comment by 3bdev** [comment]
We compiled the app with some exclusion on proguard related to Iubenda and looks like now the string is passing.

**Comment by 3bdev** [comment]
Can you confirm @TheMediaGrid you have received one non debug versione with the consent?
I tested a non debug version on my OnePlus with the prebid sdk 1.12

**Comment by TheMediaGrid** [comment]
<img width="580" alt="Italia Online Android Consent" src="https://user-images.githubusercontent.com/44166371/121437113-690c0f80-c98a-11eb-9a9d-46ae07c1fc14.png">
Here's a screenshot from our logs that are compressed with approximately 1:1000 sampling ratio.

Looks like we were able to track a super small amount from non-debug version 4.4.6 with the consent being present on Android! This is awesome! Any plans to roll it out fully?

Confirming that for 3bmeteo app we were only seeing this issue on Android so you probably don't have to investigate this on the iOS 3bmeteo bundle. However for other italia online app bundles we were also seeing the issue, e.g. it.italiaonline.mail. Is this something that you are in charge of as well? Or we should work with some other teams?

<br class="Apple-interchange-newline">

**Comment by 3bdev** [comment]
Great to know. We will release it with gradual rollout in the next few days. 

Regarding the italiaonline app I'm not in charge of that, but I can forward this topic to them, but I think we can close this issue cause finally we discovered that it is not a Prebid SDK Issue.

Thanks to all.

**Comment by TheMediaGrid** [comment]
@maddapper sorry to re-open but what if there are other app publishers that are getting the same issue? Can we double-check somehow? Or update the documentation here? https://docs.prebid.org/prebid-mobile/legacy/android/code-integration-android.html#proguard-support It is super unclear how come this missing piece was only affecting the GDPR piece however everything else was working fine.

Also do you think it's worth adding some debug comments to help the publishers/ssps see there is an issue with proguard/gdpr?

And thanks to all for the inveatigation again, it's a please to see this fix really helping the trading.

**Comment by maddapper** [comment]
@TheMediaGrid 

> what if there are other app publishers that are getting the same issue?

this is the first time i have heard this issue being reported.  

> Can we double-check somehow?

sure, @bszekely1, are you aware of any previously reported incompatibility between proguard rules and a publisher's CMP?

> It is super unclear how come this missing piece was only affecting the GDPR piece however everything else was working fine.

my understanding is that the root cause of this issue is more to do with the iubenda CMP and proguard minify settings, which was reported by @3bdev.  The publisher's CMP should write values to the shared storage (preferences) on the device and my best guess is that that wasn't happening due to the proguard issue.  The only thing Prebid Mobile SDK does re: GDPR is read those settings, and pass them thru into the bid request.  So if those settings do not exist, then they would be excluded from the bid request, which is what the publisher reported.  

> Also do you think it's worth adding some debug comments to help the publishers/ssps see there is an issue with proguard/gdpr?

i would suggest to the Prebid committee, is that we make a feature request to add a CMP example to the Prebid Android sample app or Dr. Prebid.  That way, the publisher can compare their CMP to the provided CMP to ensure that their CMP is functioning as expected.  The most vexing issue, IMHO, is that the debug version of the app was behaving differently than the prod version and so it was difficult to trace the issue.  In fact, it was by chance that we discovered this discrepancy in behavior.

**Comment by 3bdev** [comment]
Yes I think there can be a similar issue if for some reason the CMP uses the same name of Prebid for soma consent function and during the obfuscation it looses its mind.

It's probably safe to assume that also other CMP can face the same issue with Proguard.

Maybe they can check if Proguard is the issue also on their side.
