### ISSUE TITLE
How to collect the OAID of the mobile phone and pass it to our Prebid Server through the Prebidmobile?

### ISSUE THREAD

**Issue by wwwyyy** [prebid/prebid-mobile-android#266]
**Is your feature request related to a problem? Please describe.**

I'm debugging a adapter of  Prebid Server, and we need the OAID of the device for attribution and so on. I did not find a way to pass this parameter OAID in the code of prebidmobile. Although prebidserver has a StoredRequest method, the device OAID is always changing. Can it only be achieved by rewriting part of the prebidmobile code? Why not increase the ext replacement of device, we can get the value from here。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YuriyVelichkoOpenX** [comment]
@KostiantynTselykh can you, please, take a look?

**Comment by KostiantynTselykh** [comment]
Hi @wwwyyy,
You can try to pass OAID by using `TargetingParams` class. 
Example:
```
TargetingParams.addUserData("oaid", "123456");
```
It will be passed in user.ext.data object as shown on the screenshot below:
<img width="270" alt="Screenshot 2021-06-24 at 10 57 13" src="https://user-images.githubusercontent.com/79995965/123240213-c9519400-d4e8-11eb-9c3a-e761aed42d94.png">

Please let us know if this approach fits your needs.

**Comment by wwwyyy** [comment]
@KostiantynTselykh Thank you，I think it can help.
