### ISSUE TITLE
Can you host compiled jar files in this repo?

### ISSUE THREAD

**Issue by pboisso** [prebid/prebid-mobile-android#27]
Hi,

We would like to use prebid-mobile-sdk to implement in our apps, which are developed with Xamarin framwork.  Until prebid-mobile provides a Xamarin SDK, we can import the native SDK, but we would need the compiled version for that, the final jar files. 

Would it be possible to host the compiled version in this repo so that we don't have to set up for build when we don't need to?  

Same applies for iOS version.

Thanks and keep up the great work.

**Comment by anwzhang** [comment]
Hi @pboisso ,

Would you be able to use the Maven integration or Cocoa pods for iOS?

Best,
Wei

**Comment by pboisso** [comment]
Hi @anwzhang ,

I'm not sure.  We are still in the very early stage of making this happen.  Here are the instructions from Xamarin : https://developer.xamarin.com/guides/ios/advanced_topics/native_interop/

We would need a .A file in iOS?

For Android, looks like we need a jar file.

Thanks in advance for your help.

Patrice

**Comment by anwzhang** [comment]
Hi @pboisso ,

I looked into the link you shared, it seems like we can generate a .A file iOS. 

In the mean time, if you would like a jar file, simply run this script: https://github.com/prebid/prebid-mobile-android/blob/master/buildprebid.sh and it will output a jar file for you.

We'll work on the iOS side to add it to the build script to generate the .A file too.

Let me know if this works for you.

Best,
Wei

**Comment by pboisso** [comment]
Awesome, thanks Wei, will look into it and report any progress/issues in the next couple of weeks.

Patrice

**Comment by pboisso** [comment]
Hi @anwzhang,

I was wondering if you had time to implement the output of the .A file in the iOS build?  I can't seem to be able to find it.

We are working hard to trying binding this SDK to Xamarin.

Thanks.

Patrice

**Comment by rochapablo** [comment]
There's no `buildprebid.sh`, which file should I be running now?
