### ISSUE TITLE
Build script chugs along through failed build steps, generates confusing error messages

### ISSUE THREAD

**Issue by rmloveland** [prebid/prebid-mobile-android#3]
The build script was failing because I had the `ANDROID_HOME` environment variable pointing at the wrong directory.

However, the output of the build script (attached) references unit tests failing in nonexistent directories and some other things that made it a bit confusing to find, e.g.,

```
 [/]  -e PREBID BUILDLOG: Unit tests failed, check log in /Users/rloveland/work/code/vendor/prebid-mobile-android/out/logs/testResults.log
...
-e PREBID BUILDLOG: Assemble b [/]  -e PREBID BUILDLOG: Build failed, check log in /Users/rloveland/work/code/vendor/prebid-mobile-android/out/logs/build.log
```
Neither of these log files were ever written, nor the `logs` dir ever created.

I was able to put it together later down in the output from:

```
* What went wrong:
A problem occurred configuring root project 'DemoApp'.
> The SDK directory '/usr/local/opt/android-sdk' does not exist.
```

The script continues to chug along and tell me the demo app is in `out` but it was never built.

Would it be possible to check for the existence of necessary tools in `ANDROID_HOME` and bail with an error message about that before doing anything else?

More generally, it would be good if the script had more error checking and bailed as soon as something didn't work.

[prebid-android-output.txt](https://github.com/prebid/prebid-mobile-android/files/1191205/prebid-android-output.txt)

**Comment by anwzhang** [comment]
Hi @rmloveland 

Issues above are resolved in this PR: https://github.com/prebid/prebid-mobile-android/pull/8
Let me know if you run into these issues again.

**Comment by anwzhang** [comment]
PR #8 merged.
