### ISSUE TITLE
Function .init() not available.

### ISSUE THREAD

**Issue by jaorihuela** [prebid/prebid-mobile-android#31]
I'm using Prebid Mobile SDK through Maven **`compile 'org.prebid:prebid-mobile-sdk:[0,1)'`**
		
I have read that **Prebid.init(getApplicationContext(), adUnits, "YOUR-ACCOUNT-ID-HERE")** is deprecated, but in this compilation, **Prebid.init(getApplicationContext(), adUnits, "YOUR-ACCOUNT-ID-HERE", Prebid.AdServer.DFP);** doesn't exist.

**Comment by pedroventura** [comment]
Hi @randeepsiddhu @anwzhang 

I think that is the reason why the travis build fails: https://travis-ci.org/prebid/prebid-mobile-android/builds

Hope you have enough time to check this out,

Thank you guys!

**Comment by anwzhang** [comment]
Hi @jaorihuela,

That API is merged to master but not officially released yet. The latest maven build is still using `Prebid.init(getApplicationContext(), adUnits, "YOUR-ACCOUNT-ID-HERE")`. Sorry for the confusing part here.

Best,
Wei

**Comment by anwzhang** [comment]
Hi @pedroventura ,

The build is failing for a different reason since the app in the build builds from source, I've tested locally that it passes however it fails on travis. I'm looking into it now thanks for brining it up.

Best,
Wei

**Comment by anwzhang** [comment]
Integration tests fixed, new release will be ready by the end of this week.

**Comment by pedroventura** [comment]
Hi @anwzhang!! Will you launch today or the following days the release with this fix?

We will appreciate it.

Thank you!

**Comment by anwzhang** [comment]
Hi @pedroventura release is scheduled for next Monday Feb 5th.

Best,
Wei
