### ISSUE TITLE
Build failing on 1.13.0-beta1

### ISSUE THREAD

**Issue by christianrank** [prebid/prebid-mobile-android#316]
**Describe the bug**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDevDebugMainManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:33:5-32
  	is also present at [org.prebid:prebid-mobile-sdk-rendering:1.13.0-beta1] AndroidManifest.xml:32:18-44 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:6:5-11:19 to override.
```

**To Reproduce**

using:
  `implementation 'org.prebid:prebid-mobile-sdk:[1,2)'`
  which loads the latest 1.13.0-beta1

**Expected behavior**
Build without error.

**Workaround**
using the old version as a workaround, the build is still working:
`implementation 'org.prebid:prebid-mobile-sdk:1.12.1'`

**Comment by ValentinPostindustria** [comment]
This error was fixed. You can now update Prebid SDK to 1.13.1. Thanks for the information about the issue.

**Comment by christianrank** [comment]
thanks 🙂
