### ISSUE TITLE
No ads returned from primary ads via creative

### ISSUE THREAD

**Issue by GenarC** [prebid/prebid-mobile-android#335]
I'm having issues with primary ad server-mopub. I'm using your sample java project to test. I prepared a custom prebid server, it sends and get bid requests. However I cannot get ads on mobile, mopub sends me error code "No Ads". I only enabled huaweiads on the custom prebid server for testing and getting responses. However primary ad server does not return the winning ads (in this siituation Ionly have one response).

Should I change any property on Prebid Creative?

**Comment by YuriyVelichkoPI** [comment]
Hi @GenarC !

The first thing that you should check is the matching of targeting keywords in the bid response and in the Line Item on the MoPub.

https://docs.prebid.org/prebid-mobile/adops-line-item-setup-mopub.html

So you should verify that the bid response has a keyword like `hb_pb:0.50` and the MoPub order has a respective Line item.    

It is possible that you should use not the `hb_pb` keyword but the custom demand partner keyword. I'm not sure which keyword should be used for huaweiads.

**Comment by GenarC** [comment]
targeting":{
                        "hb_bidder":"huaweiads",
                        "hb_bidder_huaweiads":"huaweiads",
                        "hb_cache_id":"************************",
                        "hb_cache_id_huaweiad":"************************",
                        "hb_env":"mobile-app",
                        "hb_env_huaweiads":"mobile-app",
                        "hb_pb":"0.50",
                        "hb_pb_huaweiads":"0.50",
                        "hb_size":"300x250",
                        "hb_size_huaweiads":"300x250"
                     },

Tis is the targeting tag from the response, hb_pb:50 is present here. Also this is the creative script that I used
![resim](https://user-images.githubusercontent.com/20942609/148737116-b49b1975-5dbe-4fe9-b270-41ade7a83b62.png)

So It seems there is no problem but I cannot get ads from Mopub, what should I do?

**Comment by YuriyVelichkoPI** [comment]
It is strange that `hb_cache_id` and `hb_cache_id_huaweiad` are empty. It means that Prebid Unieversal Creative (PUC) won't be able to load and render the ad's creative. 

Have you set up the Prebid Cache? 

If yes, could you share the full bid request, it may omit the caching.

**Comment by GenarC** [comment]
Actually, the cache id values were present, I changed them to asterisk characters.

**Comment by YuriyVelichkoPI** [comment]
Ok. In this case, need to recheck the MoPub setup. 
Somehow MoPub doesn't target a needed line item to the ad request. 

Need to be sure that 
- Prebid's Line Item is targeted to the proper Ad Unit
- Prebid's Line Item has the correct targeting keywords hb_pb:0.50
- Prebid Line Item has the correct size - 300x250 as I see from targeting keywords
- The MpAdView has the correct size

**Comment by GenarC** [comment]
Ok, it was an ad slot target problem, because "banner" name is used in example project everywhere, I selected the type banner, changed it to medium rectangle.

Now, Banner loaded event is triggered but no ads shown on UI, but still I can get impressions on Mopub console.

What should I change in prebid creative or should I use it as it is?

![image](https://user-images.githubusercontent.com/20942609/149080810-b99040f4-e57f-4cd6-b9d4-17ac044b5bd4.png)

**Comment by YuriyVelichkoPI** [comment]
Do you see the request to prebid cache, in Charles proxy for example? I'm asking because I do not see `hb_cache_host` and` hb_cache_path` in your targeting keywords. So maybe PBC can't generate it automatically because of empty values. Or you can specify them explicitly in the creative code, like

```
  ucTagData.cacheHost = "https://my.pbc.com"

But for starter Tty to use the shorter list of params described on the integration page:

```
<script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"> </script>
<script>
   var ucTagData = {};
   ucTagData.adServerDomain = "";
   ucTagData.pubUrl = "%% KEYWORD: url %%";
   ucTagData.targetingKeywords = "%% KEYWORDS %%";
   ucTagData.hbPb = "%% KEYWORD: hb_pb %%";
    try {
     ucTag.renderAd (document, ucTagData);
   } catch (e) {
     console.log (e);
   }
</script>
```

**Comment by GenarC** [comment]
I changed to the shorter one, but did not work either. I cannot see the url targeting keyword either, is that a problem? How about "ucTagData.adServerDomain"? Should I fill the value. I installed my custom prebid server, should I fill the value with my server's ip?

**Comment by YuriyVelichkoPI** [comment]
As I know  the`adServerDomain` doesn't take part in the mobile flow:
https://github.com/prebid/prebid-universal-creative/blob/2e1cbeb7c60a7de11cd6ff54d2b64c2d409237be/src/renderingManager.js#L39

The cache `host` should be present in the targeting keywords. For instance - here are the  targeting keywords of our test unit:

```
"targeting": {
    "hb_bidder": "openx",
    "hb_bidder_openx": "openx",
    "hb_cache_host": "prebid.openx.net",
    "hb_cache_host_openx": "prebid.openx.net",
    "hb_cache_id": "6064b0b3-5d22-4724-8649-53b75c8e2a61",
    "hb_cache_id_openx": "6064b0b3-5d22-4724-8649-53b75c8e2a61",
    "hb_cache_path": "/cache",
    "hb_cache_path_openx": "/cache",
    "hb_env": "mobile-app",
    "hb_env_openx": "mobile-app",
    "hb_pb": "0.10",
    "hb_pb_openx": "0.10",
    "hb_size": "320x50",
    "hb_size_openx": "320x50"
},
```

**Comment by GenarC** [comment]
Are these targeting keywords should be sent from prebid server? How can I see these keywords? Are they from cache? What could be the reason that our keywords are missing? I know I asked too much questions but I couldn't make it work :S

**Comment by YuriyVelichkoPI** [comment]
@GenarC no worries. 

Yes, the Prebid Server sends these keywords in the bid response. You can see them using any proxy app. Or you can inspect keywords in the SDK code:

https://github.com/prebid/prebid-mobile-android/blob/fd7eef8a5febd9a3156f9612775ce8e4f92f09aa/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/DemandFetcher.java#L198

I'm not sure why needed keywords are missed. It may depend on the adapter on PBS. It may require particular configuration properties in the stored impression. If it is possible for you we can make a call you'll share a screen and I'll try to debug your setup online.

**Comment by YuriyVelichkoPI** [comment]
Hi  @GenarC ! Is this issue still relevant?

**Comment by YuriyVelichkoPI** [comment]
I'm closing this issue. Let me know if we should reopen and continue troubleshooting.
