### ISSUE TITLE
SDK Internal error: WinnerBid is null when executing on onPrebidSdkWin

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-mobile-android#371]
Hello,

I've managed to get a proper response from my Prebid server. However, no matter what the result is, this is the only error message I get. The result from Prebid server looks alright. How do I intercept onPrebidSdkWin and check what the root cause is?

Here is my source code
```
class MainActivity : AppCompatActivity() {
    private lateinit var binding: ActivityMainBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        initPrebid()
        createBanner()
        binding.btnShowAds.setOnClickListener {
            createBanner()
        }
    }

    private fun initPrebid() {
        val endpoint = "http://xx.xx.xx.xx:8000/openrtb2/auction?test=1"
        val prebidHost = org.prebid.mobile.rendering.bidding.enums.Host.CUSTOM
        prebidHost.hostUrl = endpoint
        PrebidRenderingSettings.setBidServerHost(prebidHost)
        PrebidRenderingSettings.setAccountId("test_req")
        Thread {
            val info = AdvertisingIdClient.getAdvertisingIdInfo(
                applicationContext
            )
            Targeting.addUserData("oaid", info.id)
        }.start()

    }

    private fun createBanner() {
        val bannerView = BannerView(applicationContext, "test_imp_banner", AdSize(300,250))

        bannerView.setBannerListener(object : BannerViewListener {
            override fun onAdLoaded(p0: BannerView?) {
                Toast.makeText(applicationContext, "onAdLoaded", Toast.LENGTH_SHORT).show()
            }

            override fun onAdDisplayed(p0: BannerView?) {
                Toast.makeText(applicationContext, "onAdDisplayed", Toast.LENGTH_SHORT).show()
            }

            override fun onAdFailed(p0: BannerView?, p1: AdException?) {
                Toast.makeText(applicationContext, "onAdFailed - ${p1.toString()}", Toast.LENGTH_SHORT).show()
            }

            override fun onAdClicked(p0: BannerView?) {
                Toast.makeText(applicationContext, "onAdClicked", Toast.LENGTH_SHORT).show()
            }

            override fun onAdClosed(p0: BannerView?) {
                Toast.makeText(applicationContext, "onAdClosed", Toast.LENGTH_SHORT).show()
            }
        })

        binding.adFrame.addView(bannerView)
        bannerView.loadAd()
    }
}
```

Cheers
CL

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40 can you share a bid response?

**Comment by ValentinPostindustria** [comment]
Hi. You use `applicationContext` in your createBanner() function, instead of `this@MainActivity` (simple Context). This could be the cause of the error. 
Also, you can find test examples in the [Kotlin demo app](https://github.com/prebid/prebid-mobile-android/tree/master/Example/PrebidDemoKotlin) (In-App category), or you can try our test ids for testing your app:
```
        val host = Host.CUSTOM
        host.hostUrl = "https://prebid.openx.net/openrtb2/auction"
        PrebidRenderingSettings.setBidServerHost(host)
        PrebidRenderingSettings.setAccountId("0689a263-318d-448b-a3d4-b02e8a709d9d")
```
And config id for video banner: `9007b76d-c73c-49c6-b0a8-1c7890a84b33`.

**Comment by clho40** [comment]
> Hi @clho40 can you share a bid response?

Hello @YuriyVelichkoPI , this is one of my sample responses
`2022-03-03 11:05:48.258 27060-27060/com.prebid.mobile.javatest D/BaseNetworkTask: Result: {"id":"333b3102-e528-4278-ae21-a69b21ce8a49","ext":{"debug":{"httpcalls":{"huaweiads":[{"uri":"http://xx.xx.xxx.xxx:3022/ppsadx/getResult","requestbody":"{\"version\":\"3.4\",\"multislot\":[{\"slotid\":\"z176nqbh4j\",\"adtype\":8,\"test\":1,\"format\":[{\"w\":300,\"h\":250}]}],\"app\":{\"version\":\"1.0\",\"name\":\"PrebidMobile\",\"pkgname\":\"com.prebid.mobile.javatest\",\"lang\":\"en\",\"country\":\"ZA\"},\"device\":{\"useragent\":\"Mozilla/5.0 (Linux; Android 10; ELS-AN00 Build/HUAWEIELS-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36\",\"os\":\"Android\",\"version\":\"10\",\"maker\":\"HUAWEI\",\"model\":\"ELS-AN00\",\"width\":1200,\"height\":2640,\"language\":\"en\",\"pxratio\":3.3125,\"oaid\":\"9498e452-16a5-4e9d-a72a-20d2033e72ab\",\"localeCountry\":\"ZA\",\"belongCountry\":\"ZA\",\"clientTime\":\"\",\"ip\":\"xx.xxx.xxx.xx\"},\"network\":{\"type\":2,\"carrier\":99,\"cellInfo\":[{\"mcc\":\"262\",\"mnc\":\"03\"}]},\"regs\":{},\"geo\":{}}","requestheaders":{"Accept":["application/json"],"Content-Type":["application/json;charset=utf-8"],"User-Agent":["Mozilla/5.0 (Linux; Android 10; ELS-AN00 Build/HUAWEIELS-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36"],"X-Prebid":["pbs-go/unknown,app/unknown,prebid-mobile/1.13.0-beta2"]},"responsebody":"{\"ctrlSwitchs\":\"0\",\"dsp1cost\":25,\"dspcost\":27,\"multiad\":[{\"adtype\":8,\"brsetting\":\"N\",\"content\":[{\"clickActionList\":[1],\"contentid\":\"21.testbanners5h9c88jef0126003\",\"creativetype\":2,\"ctrlSwitchs\":\"10101100001211\",\"cur\":\"CNY\",\"endtime\":1611823633411,\"filterList\":[3],\"interactiontype\":1,\"landPageWhiteList\":\"contentcenter-drcn.dbankcdn.com,h5hosting-drcn.dbankcdn.cn\",\"metaData\":{\"adSign\":\"2\",\"apkInfo\":{\"afDlBtnText\":\"%E6%89%93%E5%BC%80\",\"appDesc\":\"%3C1+%E4%B8%87%E6%AC%A1%E5%AE%89%E8%A3%85\",\"appIcon\":\"https://lfhiapptest.hwcloudtest.cn:39443/hwmarket3/files/application/icon144/1075/c0651f6b810b43e8889204a06bb13426.png\",\"appName\":\"Zoom\",\"channelInfo\":\"mym_123test\",\"channelInfoSaveLimit\":0,\"developerName\":\"SSP-China-A1\",\"dlBtnText\":\"%E6%89%93%E5%BC%80\",\"fileSize\":6094090,\"installConfig\":{\"appBtnInstallWay\":\"0111\",\"creativeInstallWay\":\"0111\"},\"packageName\":\"com.freeSoft.phoneRing.AndDanceRt\",\"permPromptForCard\":\"0\",\"permissions\":[{\"groupDesc\":\"%E5%AD%98%E5%82%A8\",\"permissionLabel\":\"%E4%BF%AE%E6%94%B9%E6%88%96%E5%88%A0%E9%99%A4%E5%AD%98%E5%82%A8%E5%8D%A1%E4%B8%AD%E7%9A%84%E5%86%85%E5%AE%B9\",\"targetSDK\":\"0\"}],\"popNotify\":1,\"popUpAfterInstallNew\":1,\"popUpAfterInstallText\":\"%E5%AE%89%E8%A3%85%E5%AE%8C%E6%88%90%2C%E7%82%B9%E5%87%BB%E5%90%8E%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80%E5%BA%94%E7%94%A8\",\"priorInstallWay\":\"3\",\"privacyPolicy\":\"https://airjordan34.com\",\"secondUrl\":\"https://lfhiapptest.hwcloudtest.cn:39443/hwmarketmirrortest/application/apk/c0/c0651f6b810b43e8889204a06bb13426/com.xxx.xxx.xxx.2006301057.apk?sign=mw@mw1611804190818&maple=0&distOpEntity=HWSW\",\"sha256\":\"e0019a341915fed54910aa675447db690aea918fc9e3f7588b4513fd92fd5660\",\"trafficReminder\":10,\"url\":\"https://lfhiapptest.hwcloudtest.cn:39443/hwmarketmirrortest/application/apk/c0/c0651f6b810b43e8889204a06bb13426/com.freeSoft.phoneRing.AndDanceRt.2006301057.apk?sign=mw@mw1611804190818&maple=0&distOpEntity=HWSW\",\"versionCode\":\"6\",\"versionName\":\"1.6\"},\"clickUrl\":\"http://tool.chinaz.com/Tools/unixtime.aspx\",\"cta\":\"%e6%9f%a5%e7%9c%8b%e8%af%a6%e6%83%85\",\"description\":\"111111111111111112wwwWwwWWWWWWWWWW\",\"imageInfo\":[{\"height\":170,\"imageType\":\"img\",\"sha256\":\"a500003670a1e8827bbac259a01e95100b540da5381d336be0ed1b84c86e94c2\",\"url\":\"https://dimg03.c-ctrip.com/images/200g080000003947464F0_D_1080_607_Mht3.jpg\",\"width\":1080}],\"label\":\"brand\",\"privacyUrl\":\"https://airjordan34.com\",\"title\":\"wuliwwwws\"},\"monitor\":[{\"eventType\":\"imp\",\"url\":[\"https://e.cn.miaozhen.com/imp1\"`

**Comment by ValentinPostindustria** [comment]
Hi, I found another possible error. Maybe your device doesn't accept GDPR consent. 
Please try this:
```
PreferenceManager.getDefaultSharedPreferences(this).edit().apply {
            putInt("IABTCF_gdprApplies", 0)
            putInt("IABTCF_CmpSdkID", 123)
            apply()
}
```
But don't use this code in production without the real user's agreement.

**Comment by clho40** [comment]
Hello @ValentinPostindustria , sorry my bad, there was a typo in my source code. The call to https://prebid.openx.net/openrtb2/auction worked for me, and the result looked very different from what I have. Do you have any idea how I could fix my adx response?

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40 

Your request sample looks truncated. 

However, from what I see it looks like `no bids`. It means that no demand partner responded with an ad. 

In the `responsebody` I see that **huaweiads** responded with some data, but I'm not sure whether this response contains an ad.

**Comment by YuriyVelichkoPI** [comment]
@clho40 also, If you are in the EU you should try Valentin's suggestion of providing a dummy consent string.

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40! 

Have you been succeeded in receiving a bid?

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI , unfortunately not. It's still the same and I am not sure which part of the response is incorrect. I have tried setting the consent but it still doesn't work

**Comment by YuriyVelichkoPI** [comment]
It's not good :)

We'll be able to dig deeper into the problem if you share your `stored response` and `stored impression`, so we can reproduce it on our test server and try to reproduce the bug with the test app. 

If you do not want to share them publically you can send them to me via email.

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI , thanks for the kind offer! Unfortunately my instances have been terminated, it'll take some time for me to recover them. However I can send you my mocked adx response, you can hardcode the response as the response your prebid server get from the adx server.

Would that work?

**Comment by YuriyVelichkoPI** [comment]
Yep, It works for me.

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI , I've dropped you an email 🥇

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI , I've dropped you an email, are you able to simulate?

**Comment by YuriyVelichkoPI** [comment]
@clho40 does this issue still relevant?
