### ISSUE TITLE
Version 1.13.1 on MavenCentral

### ISSUE THREAD

**Issue by henningBunk** [prebid/prebid-mobile-android#372]
**Describe the bug**
MavenCentral has a version 1.13.1 which is older than version 1.12.2.  
The newest stable version should have the highest version number.

https://mvnrepository.com/artifact/org.prebid/prebid-mobile-sdk

I have the feeling 1.13.1 shouldnt be listed as stable right? It reverts some changes like moving from Android Support libraries to AndroidX. 1.13.1 is also not listed as release in this repo.

**Comment by YuriyVelichkoPI** [comment]
Hi @henningBunk! Right, the 1.13.1 was released like a hotfix for publishers who integrated the prebid SDK specifying the versions range. So they got the beta release automatically without intent to do it. It is not the best and clearest "fix" of course, but the only one that we were able to provide at that time. 1.13.1 is technically a copy (alias) of 1.12.1 and nothing more. Unfortunately, we can't extract or rewrite versions so have to live with the current situation. We plan to make the next version 1.15.0 like a GA release so the sequence will be fixed properly.

**Comment by henningBunk** [comment]
Hi Yuriy!
Thanks for the explanation.

> We plan to make the next version 1.15.0

This would be great. We upgrade manually to only stable releases so accidently gotten this one ;-) 

Since I dont think there is anything todo here I am closing the issue.
