### ISSUE TITLE
[crash] CacheManager.java:104

### ISSUE THREAD

**Issue by gubatron** [prebid/prebid-mobile-android#38]
![screen shot 2018-03-20 at 4 11 23 pm](https://user-images.githubusercontent.com/163977/37685517-5f5d0b96-2c59-11e8-84fb-0f018f3ba9ac.png)

Runtime exception can be thrown by `WebView(context)` instantiation.
![screen shot 2018-03-20 at 4 17 04 pm](https://user-images.githubusercontent.com/163977/37685734-2b5b0bee-2c5a-11e8-94e2-7c280ba20f60.png)

Not sure if maybe that Runnable's `run()` should be protected by a try/catch block and somehow make note the `WebCache` hasn't been created correctly instead of making host app crash.

Also, this class `CacheManager.java` is full of `Context` memory leaks.

Every time you create those anonymous `Runnable` instances, you're bringing with you a reference to the outer class, in this case the `CacheManager` which in turn has a `WebView dfpWebCache` property, which extends all the way from `View` and has a reference to a `Context`. If the phone is rotated or the user goes home the references are leaked and can't be cleaned by the garbage collector, which ends up in Out of memory errors left and right.

You want those `Runnable`s to be `private static` classes and have `WeakReference<...>` to the `Context` holding class.

**Comment by gubatron** [comment]
Let me know if patches are welcome :)

**Comment by anwzhang** [comment]
@gubatron thanks for submitting this issue. Patches are welcomed.

**Comment by gubatron** [comment]
@anwzhang I'm not sure if we'll be able to do anything by catching that AndroidRuntimeException, I looked at my code and I'm catching a Throwable, AndroidRuntimeException extends it.

In any case, I've sent you a pull request about something that we can do, which is, avoid Memory Leaks via anonymous Runnables with outer references to Contexts.

https://github.com/prebid/prebid-mobile-android/pull/40

**Comment by gubatron** [comment]
actually, I think we'll be able, now that I think about it, my `try/catch` never occurs since the error is thrown on the main thread. Therefore, we should indeed put a `try/catch` on that `Runnable`.

I'll wait on your decision to merge the patch I've sent to avoid `Context` leaks, and then protect the main thread from that nasty crash.

**Comment by gubatron** [comment]
I've gone ahead and submitted [the crash catching patch](https://github.com/prebid/prebid-mobile-android/pull/40/commits/9a0127eb7bfd38717b53f45141959edd72cddfc6) on top of my refactor branch.
Feel free to cherry pick the first commit if you don't like the second, or just merge both 😄

**Comment by anwzhang** [comment]
PR #40 merged.

**Comment by gubatron** [comment]
![thank you](https://user-images.githubusercontent.com/163977/37739294-4f17568a-2d1f-11e8-9d13-ef785c2d2cb3.jpg)
