### ISSUE TITLE
Error sending the request to Prebid Cache

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-mobile-android#437]
Hello,

I am trying to use the Rendering API without the need for a Prebid cache server.

This is the response I get:

`"errors":{"prebid":[{"code":999,"message":"Error sending the request to Prebid Cache: Post \"///cache\": unsupported protocol scheme \"\"; Duration=8.072µs, Items=1, Payload Size=3346"}]`

How do I config Prebid SDK to not look for the Prebid Cache server?

Many thanks
CL

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40 ! For now, the motivation to use the cache is to support the original analytic approach when publishers use the cache request as an "impression" event for internal reporting. In order not to break such reporting rendering API sends the cache field in the bid request and the cache request at the moment of rendering. We are going to introduce optional caching in the next release. 

Short question: you get an error on making the bid request, right?

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI , thanks for getting back!

So a Prebid Cache server is still needed? Am I right?

Yes I get the error after receiving a response from my Prebid Server

**Comment by YuriyVelichkoPI** [comment]
Yes, you still should install the PBC for the current SDK version.

**Comment by clho40** [comment]
Got it. Thanks @YuriyVelichkoPI . Looking forward to the next version!
