### ISSUE TITLE
GDPR consent string is always empty

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-mobile-android#458]
Hello team,

I've been trying to send the GDPR consent string to the server. Here's what I've tried:
```
TargetingParams.setSubjectToGDPR(true)
TargetingParams.setGDPRConsentString("COvFyGBOvFyGBAbAAAENAPCAAOAAAAAAAAAAAEEUACCKAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw");
```

and
```
PreferenceManager.getDefaultSharedPreferences(applicationContext).edit().apply {
            putBoolean("IABConsent_CMPPresent",true)
            putString("IABConsent_SubjectToGDPR", "1")
            putString("IABConsent_ConsentString", "COwK6gaOwK6gaFmAAAENAPCAAAAAAAAAAAAAAAAAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw" )
            apply()
        }
```
Both won't work. Here is part of the openrtb2.BidRequest I get on the server:
```
"regs":{"ext":{"gdpr":0}},
```

GDPR is always set to 0, and there's no trace of consent string. What did I do wrong?

**Comment by ValentinPostindustria** [comment]
Hello. Thanks for the issue. 

It's a bug, we will fix it and push it into a new release that will be in the next couple of weeks. 

But for now, you can fix it by calling your code with `PreferenceManager.getDefaultSharedPreferences(applicationContext) ...` before `PrebidMobile.setApplicationContext()`.

**Comment by clho40** [comment]
Hello, thanks for the info! I've tried this:
```
private fun initPrebid() {
        val endpoint = _endpoint
        val intent = Intent(applicationContext,this.javaClass)
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        val prebidHost = Host.CUSTOM
        prebidHost.hostUrl = endpoint
        PrebidMobile.setPrebidServerHost(prebidHost)
        PrebidMobile.setPrebidServerAccountId(_accountId)
        PrebidMobile.setPbsDebug(true)
        PrebidMobile.setShareGeoLocation(true)

        Thread {
            val info = AdvertisingIdClient.getAdvertisingIdInfo(applicationContext)
            TargetingParams.addUserData("oaid", info.id)
        }.start()
TargetingParams.setGDPRConsentString("COvFyGBOvFyGBAbAAAENAPCAAOAAAAAAAAAAAEEUACCKAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw");

        PreferenceManager.getDefaultSharedPreferences(applicationContext).edit().apply {
            putBoolean("IABConsent_CMPPresent",true)
            putString("IABConsent_SubjectToGDPR", "1")
            putString("IABConsent_ConsentString", "COwK6gaOwK6gaFmAAAENAPCAAAAAAAAAAAAAAAAAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw" )
            apply()
        }
        PrebidMobile.setApplicationContext(applicationContext)
    }
```

But it is still not working. Did I miss somehting?

**Comment by ValentinPostindustria** [comment]
I tried the same code and it works. 

Did you put `IABTCF_CmpSdkID` field into SharedPreferences before? If yes, try to remove it.

**Comment by clho40** [comment]
I've tried to reinstall the app, but it is still the same. This is the response
```
{"id":"c4daec19-2e00-483c-9a75-d48514c4b6f6","imp":[{"id":"c4daec19-2e00-483c-9a75-d48514c4b6f6","banner":{"format":[{"w":320,"h":50}],"api":[3,5,6,7]},"displaymanager":"prebid-mobile","displaymanagerver":"2.0.0","secure":1,"ext":{"bidder":{"publisherid":"xxx","signkey":"yyy","keyid":"1","slotid":"zzz","adtype":"banner"},"prebid":{"storedrequest":{"id":"test_imp_banner"}}}}],"app":{"name":"PrebidMobile","bundle":"com.prebid.mobile.javatest","ver":"1.0","publisher":{"id":"test_req"},"ext":{"prebid":{"source":"prebid-mobile","version":"2.0.0"}}},"device":{"ua":"Mozilla/5.0 (Linux; Android 11; xxx Build/xxx; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36","geo":{"lat":12.23,"lon":1.23,"type":1},"lmt":0,"ip":"11.111.11.11","make":"HUAWEI","model":"xxx-xxx","os":"Android","osv":"11","h":2700,"w":1228,"pxratio":3.375,"language":"en","carrier":"xx - xx","mccmnc":"111-11","connectiontype":3},"user":{"ext":{"data":{"oaid":["8ad653cb-f1d6-4c59-a8f0-fbf36ca16435"]}}},"test":1,"at":1,"source":{"tid":"c4daec19-2e00-483c-9a75-d48514c4b6f6","ext":{"omidpn":"Prebid","omidpv":"2.0.0"}},"regs":{"ext":{"gdpr":0}},"ext":{"prebid":{"cache":{"bids":{"returnCreative":null},"vastxml":null},"channel":{"name":"app","version":""},"storedrequest":{"id":"test_req"},"targeting":{"pricegranularity":{"precision":2,"ranges":[{"min":0,"max":20,"increment":0.1}]},"includewinners":true,"includebidderkeys":true,"includebrandcategory":null,"includeformat":false,"durationrangesec":null,"preferdeals":false}}}}

```

 Can you share the openrtb2.BidRequest from the server?

**Comment by ValentinPostindustria** [comment]
It's my request to the server with your settings of GDRP:
```
{
    "app": {
        "bundle": "org.prebid.mobile.prebidkotlindemo",
        "ext": {
            "prebid": {
                "source": "prebid-mobile",
                "version": "2.0.0"
            }
        },
        "name": "Prebid Kotlin Demo",
        "publisher": {
            "id": "0689a263-318d-448b-a3d4-b02e8a709d9d"
        },
        "ver": "1.0"
    },
    "device": {
        "carrier": "Android",
        "connectiontype": 2,
        "h": 2220,
        "language": "en",
        "lmt": 0,
        "make": "Google",
        "mccmnc": "310-260",
        "model": "Android SDK built for x86",
        "os": "Android",
        "osv": "8.1.0",
        "pxratio": 2.75,
        "ua": "Mozilla/5.0 (Linux; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36",
        "w": 1080
    },
    "ext": {
        "prebid": {
            "storedauctionresponse": {
                "id": "response-prebid-banner-320-50"
            },
            "storedrequest": {
                "id": "0689a263-318d-448b-a3d4-b02e8a709d9d"
            },
            "targeting": {}
        }
    },
    "id": "b0bdbcfa-7c11-4eb3-907e-78d2244fbc50",
    "imp": [
        {
            "banner": {
                "api": [
                    3,
                    5,
                    6,
                    7
                ],
                "format": [
                    {
                        "h": 50,
                        "w": 320
                    }
                ]
            },
            "clickbrowser": 0,
            "displaymanager": "prebid-mobile",
            "displaymanagerver": "2.0.0",
            "ext": {
                "prebid": {
                    "storedauctionresponse": {
                        "id": "response-prebid-banner-320-50"
                    },
                    "storedrequest": {
                        "id": "imp-prebid-banner-320-50"
                    }
                }
            },
            "id": "b0bdbcfa-7c11-4eb3-907e-78d2244fbc50",
            "instl": 0,
            "secure": 1
        }
    ],
    "regs": {
        "ext": {
            "gdpr": 1
        }
    },
    "source": {
        "ext": {
            "omidpn": "Prebid",
            "omidpv": "2.0.0"
        },
        "tid": "b0bdbcfa-7c11-4eb3-907e-78d2244fbc50"
    },
    "user": {
        "ext": {
            "consent": "COwK6gaOwK6gaFmAAAENAPCAAAAAAAAAAAAAAAAAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw"
        }
    }
}
```

**Comment by clho40** [comment]
hmm weird, I am not sure if it is working? Out of a sudden I just can't print any logs on my server adapter

**Comment by ValentinPostindustria** [comment]
Let's try debugging. Set breakpoint in the `UserConsentParameterBuilder` in method `appendGdprParameter()` (line 44) and load any ad. Maybe it will help.

**Comment by ValentinPostindustria** [comment]
I rechecked the algorithm, it doesn't matter when you set shared preferences. You can set it even after `PrebidMobile.setApplicationContext()`. But the problem with `PrebidMobile.setGDPRConsentString()` still exists. We will fix it.

**Comment by clho40** [comment]
@ValentinPostindustria Thanks. After doing what you have instructed, I can see the consent string in the request body, from my android app. 

However, the request is never sent to my prebid server. I've tried reinstalling the app, installing the app on another phone, but I am only getting the following errors:

```
2022-05-23 09:16:18.005 3142-3142/com.prebid.mobile.javatest I/PrebidBidResponse: Failed to parse bids. No winning bids were found.
2022-05-23 09:16:18.005 3142-3142/com.prebid.mobile.javatest E/PrebidBidLoader: Invalid bid response: Failed to parse bids. No winning bids were found.
```

My server adapter did not receive anything from the sdk. In fact, I've even tried to send the request to prebid's test server
```
//    // Prebid.org
val _endpoint = "https://prebid.openx.net/openrtb2/auction"
val _accountId = "0689a263-318d-448b-a3d4-b02e8a709d9d"
val _configId = "9007b76d-c73c-49c6-b0a8-1c7890a84b33"
```

**Comment by ValentinPostindustria** [comment]
If you get ` Failed to parse bids. No winning bids were found.`, it means that your app got a response, but the response doesn't have any bids or a winning bid (winning bid must have 3 keywords: `hb_pb`, `hb_bidder`, `hb_cache_id`). Maybe advertisers don't have ads for your device at this time.

**Comment by clho40** [comment]
@ValentinPostindustria Thanks. I think the solution you've provided is working well. The problem I am having right now is with my Prebid Server, it looks like I did not set up my server to properly accept GDPR requests. Do you mind to share your gdpr config, or point me to the right directions?

**Comment by YuriyVelichkoPI** [comment]
hi @clho40! Prebid Server doesn't have GDPR config. It just populates data in the request to the adapters and optionally removes personal data from the bid request, according to the consent policy.  

In our examples we always use mocked bid responses or ads, so the PBS adapter or even bidder doesn't validate the consent for real. So we always have a winning bid in test examples. 

From your [message](https://github.com/prebid/prebid-mobile-android/issues/458#issuecomment-1132832351) I see that you don't use stored responses, and probably your demand source doesn't have mocked ad. So it is possible that provided consent doesn't allow your demand source to send the bid for this request. 

However, for a better understanding of the current situation it would be great if you share actual:
- stored impression 
- bid request (with gdpr fields)

Since the request in the link above doesn't have gdpr fields.

**Comment by clho40** [comment]
hi @YuriyVelichkoPI ! The GDPR config on the server side - I am referring to this https://docs.prebid.org/prebid-server/features/pbs-privacy.html

I have added some logging statements in my adapter, and normally when I send a request from the mobile app, I'll see something printed on the console. However, as soon as I've added the consent string, my request never reaches my adapter. I mean, I have also tried sending the request to https://prebid.openx.net/openrtb2/auction and it didn't work too.

Here's my bid request (printed on Android Studio)
```
2022-05-26 08:26:20.702 5599-23968/com.prebid.mobile.javatest D/PrebidBaseNetworkTask: queryParams: {"imp":[{"id":"3cbd0475-e86f-4d27-b35d-fbffa71ba1ef","displaymanager":"prebid-mobile","displaymanagerver":"2.0.0","instl":0,"clickbrowser":0,"secure":1,"banner":{"api":[3,5,6,7],"format":[{"w":320,"h":50}]},"ext":{"prebid":{"storedrequest":{"id":"test_imp_banner"}}}}],"id":"3cbd0475-e86f-4d27-b35d-fbffa71ba1ef","app":{"name":"PrebidMobile","bundle":"com.prebid.mobile.javatest","ver":"1.0","publisher":{"id":"test_req"},"ext":{"prebid":{"source":"prebid-mobile","version":"2.0.0"}}},"device":{"ua":"Mozilla\/5.0 (Linux; Android 11; JAD-LX9 Build\/HUAWEIJAD-L29; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/88.0.4324.93 Mobile Safari\/537.36","lmt":0,"make":"HUAWEI","model":"JAD-LX9","os":"Android","osv":"11","language":"en","carrier":"Movistar","mccmnc":"214-07","h":2700,"w":1228,"connectiontype":3,"pxratio":3.375},"regs":{"ext":{"gdpr":1}},"user":{"ext":{"data":{"oaid":["8ad653cb-f1d6-4c59-a8f0-fbf36ca16432"]},"consent":"COwK6gaOwK6gaFmAAAENAPCAAAAAAAAAAAAAAAAAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw"}},"source":{"tid":"3cbd0475-e86f-4d27-b35d-fbffa71ba1ef","ext":{"omidpv":"2.0.0","omidpn":"Prebid"}},"ext":{"prebid":{"storedrequest":{"id":"test_req"},"cache":{"bids":{}},"targeting":{}}},"test":1}

2022-05-26 08:26:20.922 5599-5599/com.prebid.mobile.javatest D/PrebidBaseNetworkTask: Result: {"id":"3cbd0475-e86f-4d27-b35d-fbffa71ba1ef","nbr":2,"ext":{"debug":{"resolvedrequest":{"id":"3cbd0475-e86f-4d27-b35d-fbffa71ba1ef","imp":[{"id":"3cbd0475-e86f-4d27-b35d-fbffa71ba1ef","banner":{"format":[{"w":320,"h":50}],"api":[3,5,6,7]},"displaymanager":"prebid-mobile","displaymanagerver":"2.0.0","secure":1,"ext":{"huaweiads":{"publisherid":"477389540332405248","signkey":"2b829544e685fef19d0558e0049aa1cbd2b2a8016d9cac713cb8df306b58a24c","keyid":"1","slotid":"d9qw57bgwy","adtype":"banner"},"prebid":{"storedrequest":{"id":"test_imp_banner"}}}}],"app":{"name":"PrebidMobile","bundle":"com.prebid.mobile.javatest","ver":"1.0","publisher":{"id":"test_req"},"ext":{"prebid":{"source":"prebid-mobile","version":"2.0.0"}}},"device":{"ua":"Mozilla/5.0 (Linux; Android 11; JAD-LX9 Build/HUAWEIJAD-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36","lmt":0,"ip":"46.114.168.137","make":"HUAWEI","model":"JAD-LX9","os":"Android","osv":"11","h":2700,"w":1228,"pxratio":3.375,"language":"en","carrier":"Movistar","mccmnc":"214-07","connectiontype":3},"user":{"ext":{"consent":"COwK6gaOwK6gaFmAAAENAPCAAAAAAAAAAAAAAAAAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw","data":{"oaid":["8ad653cb-f1d6-4c59-a8f0-fbf36ca16432"]}}},"test":1,"at":1,"source":{"tid":"3cbd0475-e86f-4d27-b35d-fbffa71ba1ef","ext":{"omidpn":"Prebid","omidpv":"2.0.0"}},"regs":{"ext":{"gdpr":1}},"ext":{"prebid":{"cache":{"bids":{"returnCreative":null},"vastxml":null},"channel":{"name":"app","version":""},"storedrequest":{"id":"test_req"},"targeting":{"pricegranularity":{"precision":2,"ranges":[{"min":0,"max":20,"increment":0.1}]},"includewinners":true,"includebidderkeys":true,"includebrandcategory":null,"includeformat":false,"durationrangesec":null,"preferdeals":false}}}}},"prebid":{"auctiontimestamp":1653546380087}}}
```

And here's my stored_imp on the server
```
{
	"id": "test_imp_banner",
	"banner": {
		"format": [
		{
			"w": 300,
			"h": 250
		}
		]
	},
	"ext":
	{"huaweiads": {
		"publisherid": "xxx",
		"signkey": "xxx",
		"keyid": "5",
		"slotid": "xxx",
		"adtype": "banner",
		"IsTestAuthorization": "true"}
	}
}
```

**Comment by YuriyVelichkoPI** [comment]
@clho40, thank you for the detailed explanation. 

@bretg could you help with this issue? Please review the above comment. What can be e reason to block bid requests with `regs.ext.gdpr` and `user.ext.consent` fields?

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI @bretg , I have tried different ways, my ad request still blocked when GDPR is enabled :( 

Is there anything I can do?

**Comment by clho40** [comment]
Is there a way we can better troubleshoot this issue?

**Comment by bretg** [comment]
@clho40 - please give us more information about your environment: bid adapters, PBS host. Or better yet a test endpoint.

1) What adapter are you trying to call? GDPR consent is based on the bid adapter, not the publisher. So it's the bid adapter GVL IDs you need to have permitted in the string.
2) looking at the declared vendor purposes, 785 and 786 don't even declare purpose 2, so PBS will drop them. 788 and 789 do declare P2, but I don't see reference to those GVL IDs in any PBS bid adapter.
3) You may want to check with whoever runs your Prebid Server. There's at least one host-level GDPR setting (location of the GVL list) that could make a given PBS installation not work properly. They may be able to raise the debug level to info and get a trace of what's happening.

**Comment by clho40** [comment]
Hello @bretg , many thanks for the detailed explanation as always! 

1. I am trying to call the huaweiads adapter, here https://docs.prebid.org/dev-docs/bidders/huaweiads.html
Actually, this adapter is not GDPR TCF compatible, and I am trying to make it compatible. I have added the code to forward the consent string to the ad servers, but before I can conclude that it will work, I want to test it, that's why I have build a simple mobile app to try.
2. Ok I will remove them
3. I am hosting the server myself, and I am still checking what is wrong / missing on the server side.

**Comment by clho40** [comment]
Hello @bretg , 

1. the gvl has been set from the beginning, please look at https://github.com/prebid/prebid-server/blob/master/static/bidder-info/huaweiads.yaml 
2. I found that the https://iabtcf.com/#/encode tool is not up-to-date, there are only 791 vendors and huawei is at 856. Therefore I have done some tweaking and the vendor 856 is not in the string, with purpose 1,2,3,4 selected. Please have a look here https://iabtcf.com/?#/decode?tcstring=CPaVG0rPaVG0rAbACAENAwCAAPAAAAAAAAYgGLwAQGsAAAAA
3. Actually I am not sure if I have configured GDPR correctly at all, here's my pbs.yaml
```
gdpr:
  enabled: true
  default_value: "0"
  timeouts_ms:
    init_vendorlist_fetches: 5000
    active_vendorlist_fetch: 5000
  tcf2:
    enabled: true
stored_requests:
  filesystem: true
adapters:
  huaweiads:
    disabled: false
cache:
  host: 'xxx.xxx.xxx.xxx:xxxx'
  scheme: 'http'
```

I am using PBS-Go. Thanks once again for looking into this!

**Comment by bretg** [comment]
@SyntaxNode - could you suggest how @clho40 can raise the debug level and hopefully get more information about why PBS-Go is rejecting his request?

**Comment by clho40** [comment]
I finally managed to get it working. Here's my take away:

The tool https://iabtcf.com/#/encode is not up-to-date. The vendorlist is 48 max and vendor 856 is not in the list. Therefore, I have to change the vendorId to 856 manually, and the vendor list version to 146. I managed to get the request with these 2 settings properly populated :)))))

**Comment by bretg** [comment]
Glad to hear you fixed the issue! I'll send a note to someone at the IAB about the tool, though not sure they really support it long-term. Maybe I can get a link to the code in case a community member has time to fix it.
