### ISSUE TITLE
Added permissions that do not seem necessary

### ISSUE THREAD

**Issue by bishiboosh** [prebid/prebid-mobile-android#460]
**Describe the bug**
Since version 1.14.0, `ACCESS_FINE_LOCATION` and `WRITE_EXTERNAL_STORAGE` have been added although they do not seem necessary. This causes permission changes in our app which could hamper app update in our users.

**To Reproduce**
Add Prebid with a version of at least 1.14.0, and observe permissions have been added. Sample project can be found at https://github.com/bishiboosh/prebid-permissions-sample

**Expected behavior**
No permissions are added.

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by ValentinPostindustria** [comment]
Hi, you are right, permissions must be optional. We will check SDK stability without these permissions and will remove them for the next release.
