### ISSUE TITLE
How to get and set the device country in the request?

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-mobile-android#467]
This might not be a bug, but I am struggling to get the device country to be set in the request.

Is there already an API I could use to **get** the device country?

And is there an API for me to **set** the device country in the request? I am referring to the device.geo.country and the user.geo.country parameters in the OpenRTB protocol.

I have tried the following but I'm not getting anywhere.
`PrebidMobile.setShareGeoLocation(true)`

Thanks in advance!

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40. Prebid SDK doesn't have an API to set this property. But we can add it. So let's leave this issue open.

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI ,

We are trying to add the functionality to get the country code in the SDK. However, we have a few concerns and we would like to check with you guys.

This is our idea:
To obtain the country code, the order should go like:

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40. Sorry for the late response. Not sure if it is still required. 

I find this article very helpful for an explanation of GDPR appliance
https://www.compliancejunction.com/gdpr-frequently-asked-questions/

So it looks like GDPR appliance doesn't depend on the device. It depends on the owner. If a person is in EU (resident or visitor) or if a person is outside of EU but he or she an EU citizen, the GDPR should be applied. The origin of the device doesn't matter.

**Comment by YuriyVelichkoPI** [comment]
Looks like was reopened accidentally
