### ISSUE TITLE
Update Exoplayer dependencies

### ISSUE THREAD

**Issue by gerzalez** [prebid/prebid-mobile-android#478]
The current version of `exoplayer` (2.13.3) is incompatible with transitive dependencies brought by other libraries due to exoplayer's removal of deprecated code

Updating `exoplayer` to at least version 2.15.1 would fix these issues

**Comment by gerzalez-etermax** [comment]
I add a PR https://github.com/prebid/prebid-mobile-android/pull/482 for this issue
