### ISSUE TITLE
Shared Preferences Boolean has been changed to String - Cannot initialize SDK

### ISSUE THREAD

**Issue by cati-net** [prebid/prebid-mobile-android#492]
**Describe the bug**
Updating the SDK from version 1.13.1 to 2.0.2 makes the SDK unable to initialize because of a change in SharedPrefs. 

`E/PrebidManagersResolver: Failed to register managers: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:288)
        at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.updateConsentValue(UserConsentManager.java:116)
        at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.initConsentValuesAtStart(UserConsentManager.java:100)
        at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.init(UserConsentManager.java:83)
        at org.prebid.mobile.rendering.sdk.ManagersResolver.registerManagers(ManagersResolver.java:167)
        at org.prebid.mobile.rendering.sdk.ManagersResolver.prepare(ManagersResolver.java:178)
        at org.prebid.mobile.rendering.sdk.SdkInitializer.init(SdkInitializer.java:63)
        at org.prebid.mobile.PrebidMobile.initializeSdk(PrebidMobile.java:204)
`

**To Reproduce**
1. Build an app with 1.13.1 and setSubjectToGDPR to true and start the app
2. Update to 2.0.2 and build to the same phone and start the app

**Expected behavior**
The SDK should update the previous boolean value labeled GDPR_PREBID_SUBJECT to a string instead of trying to access the value in shared preferences as a string. 

**Additional context**
The old method looked like this:  where PBConsent_SubjectToGDPRKey = Prebid_GDPR

```
static void setPbGdprSubject(@Nullable Boolean value) throws PbContextNullException {
        SharedPreferences pref = getSharedPreferences();
        SharedPreferences.Editor editor = pref.edit();
        if (value != null) {
            editor.putBoolean(StorageUtils.PBConsent_SubjectToGDPRKey, value);
        } else {
            editor.remove(StorageUtils.PBConsent_SubjectToGDPRKey);
        }
        editor.apply();
    }
```
    
The new method is this: where GDPR_PREBID_SUBJECT = Prebid_GDPR
```
    public void setPrebidSubjectToGdpr(@Nullable Boolean value) {
        if (value != null) {
            sharedPreferences
                .edit()
                .putString(GDPR_PREBID_SUBJECT, value ? "1" : "0")
                .apply();
        } else {
            sharedPreferences
                .edit()
                .remove(GDPR_PREBID_SUBJECT)
                .apply();
        }
    }
```

**Comment by vladimirsukiasyan** [comment]
Hello! Guys, @ValentinPostindustria, please, do something with this bag!

**Comment by mbatuhanulper** [comment]
Can you tell me in which scenario this error occurs? I could not perform this in my local.

**Comment by cati-net** [comment]
I'm setting up the SDK like this in my MainActivity onCreate-method while using version 1.13.1
```
        PrebidMobile.setPrebidServerHost(Host.RUBICON)
        PrebidMobile.setPrebidServerAccountId("xxxx")
        TargetingParams.setStoreUrl("xxxx")
        TargetingParams.setBundleName("xxxx")
        TargetingParams.setDomain("xxxx")
        TargetingParams.setSubjectToGDPR(true)
```
When I start the app, the function setSubjectToGDPR(true) will use sharedPreferences to assign "Prebid_GDPR" to true as a boolean. 

Then I try to upgrade the version number of the prebid-SDK to version 2.0.2

When I then try to start the app, the function setSubjectToGDPR(true) will instead try to assign "Prebid_GDPR to "1" as a string. 

So you'll have to start the app with prebid-SDK v:1.13.1 and then update that app with prebid-SDK v:2.0.2

**Comment by YuriyVelichkoPI** [comment]
Hi @cati-net, @vladimirsukiasyan, @mbatuhanulper. Sorry for the long silence. 

Yes, it looks like a serious regression bug. We'll try to put it in the scope of the next release.

**Comment by cati-net** [comment]
Thank you! @YuriyVelichkoPI 👍

**Comment by matrad** [comment]
Workaround:

Add this code/logik before SDK initialization

```
if(!manager.contains("Prebid_GDPR_fixed")) {
            manager.edit()
                    .remove("Prebid_GDPR")
                    .putBoolean("Prebid_GDPR_fixed", true)
                    .commit();
        }
```
