### ISSUE TITLE
Mobile Ads SDK getting deprecated for the current Demo

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [prebid/prebid-mobile-android#496]
**Describe the bug**
currently we are using 20.4.0 for the Mobile sdk and in documentation its recommended as the one "we used for testing", this is getting deprecated in q1 2023
[Google's article](https://developers.google.com/admob/android/deprecation?source=email)

**Comment by YuriyVelichkoPI** [comment]
Hi @AbrahamArmasCordero, thanks for the notice! 

We've started updating the GMA SDK dependency to the latest version. Please follow #503 for the details.
