### ISSUE TITLE
How is instl value defined?

### ISSUE THREAD

**Issue by lmatha** [prebid/prebid-mobile-android#498]
The Prebid SDK currently relies on [this solution](https://github.com/prebid/prebid-server/pull/797) to determine which ad sizes should be used for in-app interstitial ad units (via the use of **MinHeightPerc** and **MinWidthPerc** parameters).
However, it is my understanding (looking at [this code](https://github.com/prebid/prebid-server/blob/957ac22c85b8633a8561b97b85158c390ac2ff88/endpoints/openrtb2/interstitial.go)) that these parameters are only included in the ad request if the **instl** parameter has value **1**.

How is the value of this parameter determined in the Prebid SDK?
The [Prebid SDK documentation](https://docs.prebid.org/prebid-mobile/pbm-api/android/pbm-bannerinterstitialadunit-android.html) doesn't mention the **instl** parameter.
I read [here](https://docs.prebid.org/prebid-mobile/pbm-api/android/pbm-adunit-android.html) that the **adType** (**banner** or **interstitial**) is set based on whether **BannerAdUnit** or **InterstitialAdUnit** is used, so I’d guess that the value of **instl** would be set to **1** if the **InterstitialAdUnit** is used, but that doesn’t seem to be the case (we still see **instl: 0** in the ad request). It’s just a guess, since the **instl** parameter is not mentioned on this page either.
![image](https://user-images.githubusercontent.com/116307110/197038080-f2a5e054-09d6-4142-bb53-144fa20c1a80.png)
Could anyone please provide more clarity on this?

**Comment by YuriyVelichkoPI** [comment]
Hi @lmatha!

Yes, the SDK should set the `instl` value based on the used API class, for example, InterstitialAdUnit.  

Could you compare your integration with a similar case in the Demo App? I see that the bid request in the Demo App Kotlin contains the proper `instl` value.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/21169695/198119737-c26e9e5e-8cf8-4a0e-b34e-f76c26e5c3fb.png">


```
...
"imp": [{
		"id": "5df4cbd9-c6cb-444e-ac38-94586a9b8445",
		"displaymanager": "prebid-mobile",
		"displaymanagerver": "2.0.3",
		"instl": 1,
		"clickbrowser": 0,
		"secure": 1,
		"banner": {
			"pos": 7,
			"format": [{
				"w": 411,
				"h": 659
			}]
		},
		"ext": {
			"prebid": {
				"storedrequest": {
					"id": "imp-prebid-display-interstitial-320-480"
				},
				"storedauctionresponse": {
					"id": "response-prebid-display-interstitial-320-480"
				}
			}
		}
	}],
	...
```

**Comment by YuriyVelichkoPI** [comment]
If you could share your integration code, I will be happy to tune it.

**Comment by matrad** [comment]
Hello,

we compared the SDK and we saw that we integrated the Android SDK `1.12.1` as it's written in the `README`.
So we thought upgrading to the newest SDK Version `2.0.3` will fix it.

But with the Version 2.0.3 we have a Issue, that the App already crashes on start.
It's probably because of a issue with the consent-part of the SDK.

```
2022-10-27 21:51:11.858 10788-10788/com.keepinmind.stol_mobile E/PrebidManagersResolver: Failed to register managers: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
        at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.updateConsentValue(UserConsentManager.java:116)
        at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.initConsentValuesAtStart(UserConsentManager.java:100)
        at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.init(UserConsentManager.java:83)
        at org.prebid.mobile.rendering.sdk.ManagersResolver.registerManagers(ManagersResolver.java:167)
        at org.prebid.mobile.rendering.sdk.ManagersResolver.prepare(ManagersResolver.java:178)
        at org.prebid.mobile.rendering.sdk.SdkInitializer.init(SdkInitializer.java:63)
        at org.prebid.mobile.PrebidMobile.initializeSdk(PrebidMobile.java:204)

```

The crash is related to this line:
```
                gdprPrebidSubject = preferences.getString(GDPR_PREBID_SUBJECT, null);
```

Maybe this issue is caused by an update from an onder SDK-Version of Prebid?
This must work - because uninstalling our App and installing it again fixes the issue - so I think it would be enough to update the `GDPR_PREBID_SUBJECT` key to another value. 

I think this is related to [this](https://github.com/prebid/prebid-mobile-android/issues/492) issue.

PS: I think the [README](https://github.com/prebid/prebid-mobile-android/blob/master/README.md) should be updated to the current version, or at least contain no version-strings that developers do not integrate an outdated - old version by fault.

**Comment by YuriyVelichkoPI** [comment]
@matrad, thanks for the investigation! We are working on fixing all these issues so the next release 2.0.4 should be reliable and proper in terms of rtb requests. 

I'll keep you posted in this thread when a new version is available.

**Comment by YuriyVelichkoPI** [comment]
@ValentinPostindustria in the scope of this ticket we should update the README file

**Comment by matrad** [comment]
@YuriyVelichkoPI fyi - the issue with the `instl`- Parameter as @lmatha said, still persist in the iOS-App.

**Comment by YuriyVelichkoPI** [comment]
@matrad thanks, I'll double check on iOS and create an issue

**Comment by matrad** [comment]
@YuriyVelichkoPI do you have any news on iOS for the instl parameter?

**Comment by YuriyVelichkoPI** [comment]
Hi @matrad, thanks for bumping it up.
Here is the respective iOS ticket: https://github.com/prebid/prebid-mobile-ios/issues/701
It really does not send the proper `instl` value.
