### ISSUE TITLE
Update SDK reliance on PBS /status endpoint

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-mobile-android#499]
**Describe the bug**
The SDK hits the Prebid Server /status endpoint and expects "ok" to be in the response. This is not guaranteed as per the [endpoint doc](https://docs.prebid.org/prebid-server/endpoints/pbs-endpoint-status.html) which says the "exact response can be configured with the status_response config option".

The PBS committee will discuss whether we can provide a query string param that will provide a consistent response. https://github.com/prebid/prebid-server/issues/2431

**To Reproduce**
1. initialize the SDK pointing to any PBS.

To get a sense of the differences, try these:

https://prebid-server.rubiconproject.com/status
https://prebid-server.h5v.eu/status
http://prebid.adnxs.com/pbs/v1/status (note the different path!)
https://prebid.admaxmedia.io/status (endpoint not avail)
https://pbserver.galaxiemedia.fr/status (my favorite results :-)

**Expected behavior**

If a check must be done, it should to be done in a flexible way. e.g. if there's a response, substring search for any of these patterns: "ok", "ready", "good", "active", "up".

Doing a brief scan of known Prebid Servers, some of them move their /status endpoint to a different location. If the SDK wants to hit a status endpoint, then it needs to be flexible in allowing the app to define a PBS-host specific path to the status endpoint.

**Comment by bretg** [comment]
FWIW - this applies to both Android and iOS. How do does this team manage cross-platform issues?

**Comment by YuriyVelichkoPI** [comment]
Thanks for the report!

Yes, it looks wrong that Android SDK waits for a particular server response. The iOS SDK just waits for 200. 

But the question of the custom /status endpoint is not considered on both platforms. 

Let me split the changes into two releases. In the nearest one (updating the GMA SDK), we'll get rid of any response expectation unless 200. Then, for the next release, we'll study how we should handle the custom /status endpoint.

**Comment by YuriyVelichkoPI** [comment]
>> How do does this team manage cross-platform issues?

We analyze platform-specific issues and make respective tickets in the companion repo if needed.

**Comment by bretg** [comment]
Ok - let's just stick with the HTTP 200 response then! I'll close the Prebid Server issue.

**Comment by ValentinPostindustria** [comment]
Hi. A client's PS returns code 204. It responds correctly. So we also should support code 204. Not only 200. 
![изображение](https://user-images.githubusercontent.com/72038591/216601768-6e2b5a67-f67e-4755-9853-229bc427876a.png)

**Comment by YuriyVelichkoPI** [comment]
## Objectives

- Introduce a new public property in the PrebidMobile object - `customStatusEndpoint`
    - SDK expects to receive the valid URL for the /status endpoint of PBS. Not only the path but the whole URL. F.e.: http://prebid.adnxs.com/pbs/v1/status
- During the SDK initialization, the given property should be used to check the PBS status.
- If the publisher didn't provide `customStatusEndpoint,` use the current approach. 

Update the process of checking server status:
- Change the `SdkInitializationListener` 
    - Deprecate `onSdkInit`
    - Deprecate `onSdkFailedToInit`
    - Introduce `onInitializationComplete(InitializationStatus status, String description)
- Introduce the enum `InitializationStatus` with values
    - `FAILED` - this status should be returned if SDK is not able to work. The _description_ of the `onInitializationComplete` should contain the error message. 
    - SUCCEEDED - this status should be returned if SDK is able to work. The _description_ of the `onInitializationComplete` should be empty or nil. 
    - SERVER_STATUS_WARNING - this status should be returned if `StatusRequester` gets an error on checking the /status endpoint. The _description_ of the `onInitializationComplete` should contain the text of the error message.
- Call the `onInitializationComplete` with the respective status and message. Keep the deprecated methods until the next release. 
- The `StatusRequester` shouldn't lead to the `FAILED` status of SDK initialization. If something goes wrong, the `SERVER_STATUS_WARNING` should be fired. 
- Change the definition of `succeeded` status in `StatusRequester`. We should treat any of `2xx` return codes as _succeeded_.

- Update the description of the `initializeSDK` method. 
    - Describe the necessity of `customStatusEndpoint` and its usage. 
    - Describe the values of `PrebidInitializationStatus`, their meaning, and how SDK continues to work each status respectively.
