### ISSUE TITLE
MoPub SDK install / usage issue

### ISSUE THREAD

**Issue by rmloveland** [prebid/prebid-mobile-android#5]
When you open the Demo App in Android Studio, it tries to build the project and fails with the following error message (atop a stack trace):

`error: package com.mopub.mobileads does not exist`

According to the [MoPub Android repo](https://github.com/mopub/mopub-android-sdk), you need to add MoPub SDK to your `build.gradle` as follows:

    repositories {
        jcenter()
    }

    dependencies {
        compile('com.mopub:mopub-sdk:4.15.0@aar') {
            transitive = true
        }
    }

Since we are already pulling from the JCenter repository, we just need to add the following to our existing 'dependencies' section so it looks like this:

    dependencies {
    compile 'com.android.support:appcompat-v7:23.1.1'
    // For aaid
    compile 'com.google.android.gms:play-services-ads:9.2.1'

    // From MoPub Android SDK docs
    compile('com.mopub:mopub-sdk:4.15.0@aar') {
    transitive = true
    }

    // Build from compiled libs
    compile fileTree(dir: 'libs', include: ['*.jar'])
    }

When re re-sync the project in Android Studio, it fails again, but differently, with the following error message:

    Error:Execution failed for task ':processDebugManifest'.
    > Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.mopub:mopub-sdk:4.15.0] /Users/rloveland/.android/build-cache/020e912c9aa50c62670f43e55499007e6bed09ee/output/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.mopub.mobileads" to force usage

I can "fix" the issue by editing the `defaultConfig` block to bump the `minSdkVersion` to 16 like so:

    defaultConfig {
    applicationId 'org.prebid.mobile.demoapp'
    minSdkVersion 16 // <--- s/14/16/
    targetSdkVersion 25
    versionCode 1
    versionName '1.0'
    }

This gets the app running on the device. However, when you click **MoPub &gt; Banner**, you get an error message:

    ERROR: YOUR MOPUB INTEGRATION IS INCOMPLETE:
    Check logcat and update your AndroidManifest.xml with the correct activities and configuration.

The instructions for updating the Android Manifest are [on the MoPub Wiki](https://github.com/mopub/mopub-android-sdk/wiki/Getting-Started#updating-your-android-manifest), so I went to follow them.

However, when I checked the Demo App's `AndroidManifest.xml` it looked like all but these two were already there:

    <activity android:name="com.mopub.mobileads.RewardedMraidActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
    <meta-data android:name="com.google.android.gms.version"
          android:value="@integer/google_play_services_version" />

When I add these two lines to the manifest, the app stops throwing the error messages in the **MoPub** submenu screens but still doesn't show any ads.

**Comment by rmloveland** [comment]
Update: Just verified that everything from the above is the same, *except* that the MoPub ads show up fine now after going through all of the steps listed above.

This is with 0.0.2 release (commit SHA is 6c06772).

Just made a PR with the fixes that get it working for me - let me know what you think!

**Comment by anwzhang** [comment]
The fixes look good to me, merged already.

**Comment by rmloveland** [comment]
Thanks @anwzhang !!!
