### ISSUE TITLE
"No bids" reported as "SERVER_ERROR"

### ISSUE THREAD

**Issue by avalanchas** [prebid/prebid-mobile-android#521]
**Describe the bug**
The SDK (the `OnCompleteListener` to be very precise) currently reports `PREBID_SERVER_ERROR` when no bids were found. 
This happens in the case where the `AdUnit` receives an error like this:
```
message: SDK internal error: Invalid bid response: Failed to parse bids. No winning bids were found.
cause: org.prebid.mobile.api.exceptions.AdException: SDK internal error: Invalid bid response: Failed to parse bids. No winning bids were found.
```

I am not 100% sure whether this is a bug since I cannot distinguish between an actual error state and missing bids, but I strongly suspect that in a recent version, the string message was changed and the parsing in `FetchDemandResult` simply gets tripped up. Let me explain why I think this is the case:
1. In `BidResponse` line 152ff the winning bid is simply null-checked, no error, no exception, simply a `null` winning bid
2. The error message is then hardcoded to "Failed to parse bids. No winning bids were found." (unfortunately I cannot trace this string back in history easily)
3. This string is then handed through the layers in the JSON and arrives at the `FetchDemandResult`
4. Here it is compared in line 80ff. with
```
if (msg.contains("No bids")) {
    return NO_BIDS;
}
```
In my opinion this check should succeed and `NO_BIDS` should be reported to the listener / client, so maybe the error message was changed recently and the word "winning" should be removed? 

**To Reproduce**
1. Launch an app with a correct server implementation but no winning bids
2. Check the logs for `AdUnit` (in this case log tag "Prebid") and note the resultCode that is passed to the listener

**Expected behavior**
When there are no bids (but no exceptional error state in the request) the `ResultCode` `NO_BIDS` should be used to allow us developers clean logging and reporting

**Screenshots**
![image](https://user-images.githubusercontent.com/6008266/202672711-f8592a22-e063-4abf-869b-bfe232c73c9e.png)

**Smartphone**
 - Device: Pixel 6 (probably all Android)
 - OS: Android 13 (probably all Android)
 - SDK Version: 2.0.4

**Comment by YuriyVelichkoPI** [comment]
Hi @avalanchas! Thanks for the report. Yep, should provide the NO_BIDS in this case. 

However, just to be on the same page, please provide a bid response that causes an issue on your side.

**Comment by YuriyVelichkoPI** [comment]
Hi @avalanchas, we make a hotfix for this case. However, the bug has shown that SDK treated server responses in not the best way, so it is really hard to understand the handling chain. 

The fix will be available in the `2.0.5` release.

But I would like to keep the issue open and correct the processing of server responses and statuses in a more proper way for both platforms. So this ticket will be the motivation for such changes.

**Comment by avalanchas** [comment]
Oh jeez I'm really really sorry for not responding with a sample earlier :(

I'm totally happy with leaving this open, do you still need an exemplary response from me? I will test 2.0.5 tomorrow at work and get you some feedback as well

Thanks again!

**Comment by YuriyVelichkoPI** [comment]
@avalanchas, no worries. 

Yes, the bid response will be helpful. We would like to see what "no bids" means in your case. Because the legal bid response for  "no bids" can be different depending on the environment, PBS setup, demand partners, etc.

2.0.5 will be released on Monday. But you can make a build from the master branch to test the behavior if you want.

**Comment by YuriyVelichkoPI** [comment]
The follow up task - #562.
