### ISSUE TITLE
Update Gradle to fix warnings during compilation

### ISSUE THREAD

**Issue by ValentinPostindustria** [prebid/prebid-mobile-android#529]
We need to update Gradle to support the latest versions of libraries and to resolve many warnings during compilation. Also, it will speed up compilation time. 
![изображение](https://user-images.githubusercontent.com/72038591/203995321-f11a682b-f3a1-47f7-b48d-f8858165d8ad.png)

**Comment by YuriyVelichkoPI** [comment]
@ValentinPostindustria, what is the status of this ticket?
