### ISSUE TITLE
Prebid Integration, Empty Response

### ISSUE THREAD

**Issue by kranthili2020** [prebid/prebid-mobile-android#54]
Hi, 
     I am new to prebid & trying to integrate it into my app. I have followed the instructions given here "http://prebid.org/prebid-mobile/code-integration-android.html"...  As I was getting empty response using the SDK & didn't know what was causing the error, I downloaded the source code & integrated it to see where the issue is... 

     I found that in "ServerConnector.java" in "doInBackground()" function, the response I am getting from server is "400" .  (Using http request, instead of the default https as I was getting the error message java.io.IOException: unexpected end of stream on Connection{prebid.adnxs.com:443, proxy=DIRECT@ hostAddress=103.243.223.145 cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 protocol=http/1.1}   )

FOR HTTP Request -------- 

      Below is the post object that was generated based on the parameters I passed. 

{"id":"b5f419b5-ed15-4697-ada6-cab93b13386d","source":{"tid":"b5f419b5-ed15-4697-ada6-cab93b13386d"},"imp":[{"id":"6e16424a7dd74a1f9b017388dc9bd41b","secure":1,"ext":{"prebid":{"storedrequest":{"id":"59394753-7d8f-4151-990a-206f36e2b087"}}},"banner":{"format":[{"w":300,"h":250}]}}],"device":{"make":"Xiaomi","model":"Redmi 3S","w":360,"h":616,"pxratio":2,"mccmnc":"405-854","carrier":"Jio 4G","connectiontype":1,"lmt":0,"os":"android","osv":"23","language":"en"},"app":{"bundle":"com.-----.debug","ver":"9.0","name":"------","privacypolicy":0,"publisher":{"id":"PREBID-ACCOUNT-ID"},"ext":{"prebid":{"source":"prebid-mobile","version":"0.3"}}},"user":{"gender":"O"},"regs":{"ext":{}},"ext":{"prebid":{"cache":{"bids":{}},"storedrequest":{"id":"PREBID-ACCOUNT-ID"}}}}

     Not sure why the request is getting failed ? I have implemented the below code 

 ArrayList<AdUnit> prebidADUnits = new ArrayList<AdUnit>();
 BannerAdUnit bau = new BannerAdUnit("ADUNIT-ID-FROM-MOPUB", "PREBID-CONFIG-ID");
 bau.addSize(300, 250);
 prebidADUnits.add(bau);

Prebid.init(getContext().getApplicationContext(), prebidADUnits, "PREBID-ACCOUNT-ID",
                        Prebid.AdServer.MOPUB, Prebid.Host.APPNEXUS);

--------------------------------------------------------------------------------------------------------------------------------------------
And in "MoPubView.BannerAdListener", I am attaching the bids as mentioned in the documentation. I AM UNABLE TO FIGURE OUT WHERE  THE LISTENER "onAttachComplete" needs to be called ? 

MoPubView moPubView = new MoPubView(context);
moPubView.setAdUnitId(adUnitId);
moPubView.setBannerAdListener(bannerAdListener);
moPubView.loadAd();

MoPubView.BannerAdListener bannerAdListener = new MoPubView.BannerAdListener() {
                    @Override
                    public void onBannerLoaded(MoPubView banner) {
                        Prebid.attachBids(banner, adUnitId, context);
                    }

                    @Override
                    public void onBannerFailed(MoPubView banner, MoPubErrorCode errorCode) {
                        Prebid.attachBids(banner, adUnitId, context);
                    }
}
----------------------------------------------------------------------------------------------------------------------------------------------
My server configuration on "prebid.adnxs.com" for the above config id is 
[
    {
        "bidder": "audienceNetwork",
        "params": {
            "placementId": "369740309766371_1955762224497497"
        }
    },
    {
        "bidder": "aerserv",
        "params": {
            "plc": "1040566"
        }
    }
]

I am unable to figure out what I am missing, which is causing the error response of 400. 

Thank you in advance, 
Kranthi

**Comment by ppuviarasu** [comment]
Hi @kranthili2020,

Do you have a valid prebid account & config id's setup. From your code I see the `PREBID-ACCOUNT-ID`, `ADUNIT-ID-FROM-MOPUB`, `PREBID-CONFIG-ID` not replaced with the actual values.

**Comment by kranthili2020** [comment]
Hi @ppuviarasu,
      
     Yes, I have a valid prebid account on "prebid.adnxs.com" with accountID : "3306c05f-6bc7-4b46-971e-d2e373592757" & a config ID "59394753-7d8f-4151-990a-206f36e2b087" which content is 

[
    {
        "params": {
            "placementId": "369740309766371_1955762224497497"
        },
        "bidder": "audienceNetwork"
    }
]
----------------------------------------------------------------------------------------------------------------------------------

I have the original values put in my request in the above message... I put textual data so that it is easy to explain what values were put by me. I have posted the POST object as is now in the below curl request.
 
I tried to request the same via POST request using curl. I removed aerserv (Have only Audience Network now) & then did a post request using curl... please find below the request object & the response... 


curl -X POST -d '{"id":"b5f419b5-ed15-4697-ada6-cab93b13386d","source":{"tid":"b5f419b5-ed15-4697-ada6-cab93b13386d"},"imp":[{"id":"6e16424a7dd74a1f9b017388dc9bd41b","secure":1,"ext":{"prebid":{"storedrequest":{"id":"59394753-7d8f-4151-990a-206f36e2b087"}}},"banner":{"format":[{"w":300,"h":250}]}}],"device":{"make":"Xiaomi","model":"Redmi 3S","w":360,"h":616,"pxratio":2,"mccmnc":"405-854","carrier":"Jio 4G","connectiontype":1,"lmt":0,"os":"android","osv":"23","language":"en"},"app":{"bundle":"com.veooz.debug","ver":"9.0","name":"NewsPlus","privacypolicy":0,"publisher":{"id":"3306c05f-6bc7-4b46-971e-d2e373592757"},"ext":{"prebid":{"source":"prebid-mobile","version":"0.3"}}},"user":{"gender":"O"},"regs":{"ext":{}},"ext":{"prebid":{"cache":{"bids":{}},"storedrequest":{"id":"3306c05f-6bc7-4b46-971e-d2e373592757"}}}}' -i "https://prebid.adnxs.com/pbs/v1/openrtb2/auction"

--------------------------------------------------------- RESPONSE -------------------------------------------------

HTTP/1.1 200 OK
Server: nginx/1.11.10
Date: Tue, 12 Jun 2018 02:48:04 GMT
Content-Type: application/json
Content-Length: 156
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Expires: 0
Pragma: no-cache
Vary: Origin

{"id":"b5f419b5-ed15-4697-ada6-cab93b13386d","ext":{"errors":{"audienceNetwork":["HTTP status 400; body: "]},"responsetimemillis":{"audienceNetwork":167}}}

**Comment by kranthili2020** [comment]
Hi @ppuviarasu 

Thank you for the quick response. I am a bit confused, because the json object wasn't created by me manually. It was JSON object that was created before calling doInBackground() in ServerConnector.java i.e. the post object via the code I have mentioned in the first post ??? Are you saying that this created object itself wasn't rightly generated ?  

Also not supporting FB server yet ? In the prebid server config we can't call audience network now ? 

----------------------------------------------------------------------------------------------------------------------------
I got the below response with json object you have sent ... 

HTTP/1.1 200 OK
Server: nginx/1.11.10
Date: Tue, 12 Jun 2018 03:38:22 GMT
Content-Type: application/json
Content-Length: 1867
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Expires: 0
Pragma: no-cache
Vary: Origin

{"id":"b5f419b5-ed15-4697-ada6-cab93b13386d","ext":{"debug":{"httpcalls":{"audienceNetwork":[{"uri":"https://an.facebook.com/placementbid.ortb","requestbody":"{\"id\":\"123\",\"imp\":[{\"id\":\"Navscreen\",\"banner\":{\"format\":[{\"w\":300,\"h\":250}],\"w\":300,\"h\":250},\"tagid\":\"369740309766371_1955762224497497\",\"secure\":1}],\"app\":{\"name\":\"NewsPlus\",\"bundle\":\"com.veooz.debug\",\"ver\":\"9.0\",\"publisher\":{\"id\":\"369740309766371\"},\"ext\":{\"prebid\":{\"source\":\"prebid-mobile\",\"version\":\"0.3\"}}},\"device\":{\"ua\":\"curl/7.47.0\",\"ip\":\"157.48.17.127\",\"make\":\"Xiaomi\",\"model\":\"Redmi 3S\",\"os\":\"android\",\"osv\":\"23\",\"h\":616,\"w\":360,\"pxratio\":2,\"language\":\"en\",\"carrier\":\"Jio 4G\",\"mccmnc\":\"405-854\",\"connectiontype\":1},\"user\":{\"gender\":\"O\"},\"at\":1,\"source\":{\"tid\":\"123\"},\"regs\":{\"ext\":{}},\"ext\":{\"platformid\":442648859414574}}\n","responsebody":"","status":400}]},"resolvedrequest":{"id":"b5f419b5-ed15-4697-ada6-cab93b13386d","imp":[{"id":"Navscreen","banner":{"format":[{"w":300,"h":250}]},"secure":1,"ext":{"audienceNetwork":{"placementId":"369740309766371_1955762224497497"},"prebid":{"storedrequest":{"id":"59394753-7d8f-4151-990a-206f36e2b087"}}}}],"app":{"name":"NewsPlus","bundle":"com.veooz.debug","ver":"9.0","publisher":{"id":"3306c05f-6bc7-4b46-971e-d2e373592757"},"ext":{"prebid":{"source":"prebid-mobile","version":"0.3"}}},"device":{"ua":"curl/7.47.0","ip":"157.48.17.127","make":"Xiaomi","model":"Redmi 3S","os":"android","osv":"23","h":616,"w":360,"pxratio":2,"language":"en","carrier":"Jio 4G","mccmnc":"405-854","connectiontype":1},"user":{"gender":"O"},"test":1,"at":1,"source":{"tid":"123"},"regs":{"ext":{}},"ext":{"prebid":{"cache":{"bids":{}}}}}},"errors":{"audienceNetwork":["HTTP status 400; body: "]},"responsetimemillis":{"audienceNetwork":167}}}

**Comment by kranthili2020** [comment]
Ok here is the actual data I put forth in my java implementation ...

ADUNIT_ID : 6e16424a7dd74a1f9b017388dc9bd41b (Got it from Mopub)
PREBID_CONFIG_ID : 59394753-7d8f-4151-990a-206f36e2b087
PREBID_ACCOUNT_ID : 3306c05f-6bc7-4b46-971e-d2e373592757

ArrayList prebidADUnits = new ArrayList();
BannerAdUnit bau = new BannerAdUnit("ADUNIT_ID", "PREBID_CONFIG_ID");
bau.addSize(300, 250);
prebidADUnits.add(bau);

Prebid.init(getContext().getApplicationContext(), prebidADUnits, "PREBID_ACCOUNT_ID",
Prebid.AdServer.MOPUB, Prebid.Host.APPNEXUS);


------------------------------------------------------------------------------------------------ 
PREBID CONFIG ID JSON IN prebid,adnxs.com :  I thought support for all there bidders is available now "http://prebid.org/dev-docs/bidders.html"

[
    {
        "params": {
            "placementId": "369740309766371_1955762224497497"
        },
        "bidder": "audienceNetwork"
    }
]

Thank you once again for the help...

**Comment by ppuviarasu** [comment]
Sorry I was talking about the adServer not the bidder. The adServer is MoPub... so you are good... 👍 

Did you actaully do this & not get a response?

ArrayList prebidADUnits = new ArrayList();
BannerAdUnit bau = new BannerAdUnit("6e16424a7dd74a1f9b017388dc9bd41b", "59394753-7d8f-4151-990a-206f36e2b087");
bau.addSize(300, 250);
prebidADUnits.add(bau);

Prebid.init(getContext().getApplicationContext(), prebidADUnits, "3306c05f-6bc7-4b46-971e-d2e373592757",
Prebid.AdServer.MOPUB, Prebid.Host.APPNEXUS);

**Comment by ppuviarasu** [comment]
also one other thing that we found was FB needs the bidder token to be set for the application.
Have you set that?
https://developers.facebook.com/docs/audience-network/advanced/ortb-bidding/

My debug log for these params show that i dont have the valid buyerId. BuyerId needs to be set as
com.facebook.ads.BidderTokenProvider.getBidderToken()

**Comment by kranthili2020** [comment]
Hi @ppuviarasu,

     Yes, I actually implemented the same with the values you have filled (Double checked it right now). & didn't get any response. As I mentioned previously was getting a response code of 400.

     This is the jsonObject I am getting. Is this request object itself wrong ??? As you mentioned prebid_config_id & publisher_id are the same ??? 

 {"id":"68dac97f-63fe-45e4-8122-92cea208b434","source":{"tid":"68dac97f-63fe-45e4-8122-92cea208b434"},"imp":[{"id":"6e16424a7dd74a1f9b017388dc9bd41b","ext":{"prebid":{"storedrequest":{"id":"59394753-7d8f-4151-990a-206f36e2b087"}}},"banner":{"format":[{"w":300,"h":250}]}}],"device":{"make":"Xiaomi","model":"Redmi 3S","w":360,"h":616,"pxratio":2,"mccmnc":"405-854","carrier":"Jio 4G","connectiontype":2,"lmt":0,"os":"android","osv":"23","language":"en"},"app":{"bundle":"com.veooz.debug","ver":"9.0","name":"NewsPlus","privacypolicy":0,"publisher":{"id":"3306c05f-6bc7-4b46-971e-d2e373592757"},"ext":{"prebid":{"source":"prebid-mobile","version":"0.3"}}},"user":{"gender":"O"},"regs":{"ext":{}},"ext":{"prebid":{"cache":{"bids":{}},"storedrequest":{"id":"3306c05f-6bc7-4b46-971e-d2e373592757"}}}}

     I haven't set anything w.r.t to FB... Will try that and update...

Thank you once again for your patience.

**Comment by ppuviarasu** [comment]
Just hardcode the values as i did & try... Your config & account id for prebid cannot be the same.

**Comment by anwzhang** [comment]
Hi @kranthili2020 ,

FB demand for mobile is not supported yet. The page you shared is for display, not for mobile.

Best,
Wei

**Comment by StarWindMoonCloud** [comment]
Hi @kranthili2020, @anwzhang , and update about this issue?

I encountered the same problem, although audienceNetwork is now supported based on below doc
http://prebid.org/dev-docs/prebid-server-bidders.html

But it's now working, and I opened an issue under prebid-mobile-android https://github.com/prebid/prebid-mobile-android/issues/200

Any chance you have figured out here?
