### ISSUE TITLE
Prebid server always returns no bids

### ISSUE THREAD

**Issue by DFilipeS** [prebid/prebid-mobile-android#55]
I am trying to run a simple demo app with the prebide-mobile-android SDK. I have the following configuration on the AppNexus Prebid Server:

```
[
    {
        "params": {
            "placementId": 13428690
        },
        "bidder": "appnexus"
    },
    {
        "params": {
            "sizes": [
                15
            ],
            "siteId": 197762,
            "accountId": 14418,
            "zoneId": 965238
        },
        "bidder": "rubicon"
    }
]
```

And my test code is:

```
ArrayList<AdUnit> adUnits = new ArrayList<>();

BannerAdUnit bannerAdUnit = new BannerAdUnit("Unit1", "ece4cec2-7c9b-4459-930d-6f6929b762a2");
bannerAdUnit.addSize(300, 250);

adUnits.add(bannerAdUnit);

try {
  Prebid.init(getApplicationContext(), adUnits, "4daf9118-1fc4-44d0-b352-0d747c757f3e", Prebid.AdServer.DFP, Prebid.Host.APPNEXUS);
} catch (PrebidException e) {
  e.printStackTrace();
}
```

But everytime I get the following error:

```
E/Prebid-BidManager: Request failed because of no_bids for AdUnit code: Unit1
```

I have tested with the accountId and configurationId from the demo app in this repository and everything works fine, bids are being received.

Is my prebid server configuration correct? Do I need to enable anything else to allow the S2S?

**Comment by anwzhang** [comment]
Hi @DFilipeS,

Your code looks correct to me. I've tested your config id and account id in my test app, it workds find and bids are returned by prebid server. 

Did you run your app in a real device or in a simulator? Sometimes the simulator doesn't have the aaid, server don't respond with ads. 

Best,
Wei

**Comment by DFilipeS** [comment]
Just tested this code on a real device and I am still getting the same error.

```
E/Prebid-BidManager: Request failed because of no_bids for AdUnit code: Unit1
```

Can you share your test app so I can try running that?

**Comment by anwzhang** [comment]
Hi @DFilipeS,

It's the demo app we have in our repo: https://github.com/prebid/prebid-mobile-android/tree/master/PrebidMobile/DemoApp

**Comment by anwzhang** [comment]
Hi @DFilipeS 
Are you able to make it work?
