### ISSUE TITLE
Prebid Demand Source

### ISSUE THREAD

**Issue by AndroidRio** [prebid/prebid-mobile-android#57]
I am having issues to use this amazing sdk. The SDK is not being able to instantiate the demand source and I am not sure why. I am currently using version 0.4.

This is the exception that is being launched.

![image](https://user-images.githubusercontent.com/5436014/43007331-6a24c5fe-8c0e-11e8-823e-48144115d91e.png)

Can you guys help me?

**Comment by anwzhang** [comment]
Hi @AndroidRio 
Are you having proguard on? You should add the following if proguard is on, documentation is being updated with this:
```
-keep class org.prebid.mobile.prebidserver.PrebidServerAdapter 
-keepnames class org.prebid.mobile.prebidserver.PrebidServerAdapter
```

**Comment by AndroidRio** [comment]
Thank you for the support!!!
