### ISSUE TITLE
Unable to proceed with the AdMob integration

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-mobile-android#580]
Hello all,

I have tried following the guide [here ](https://docs.prebid.org/prebid-mobile/modules/rendering/android-sdk-integration-admob.html#admob-integration-overview)

Here's my `MainActivity.kt`:
```
private val _endpoint = "http://xxx:8000/openrtb2/auction?test=1"
private val _accountId = "aaa"
private val _configId = "bbb"
private val _adSize = AdSize(320,50)
private val _admobAdUnitId = "ca-app-pub-1479896569354723/7408036946"

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        initPrebid()
        initGAM()
        binding.btnBannerAdMob.setOnClickListener {
            createBannerAdUnitAdmob()
        }
    }
private fun initPrebid() {
        val prebidHost = Host.CUSTOM
        prebidHost.hostUrl = _endpoint
        PrebidMobile.setPrebidServerHost(prebidHost)
        PrebidMobile.setPrebidServerAccountId(_accountId)
        PrebidMobile.setPbsDebug(true)
        PrebidMobile.useExternalBrowser = true
        PrebidMobile.setShareGeoLocation(true)
        PrebidMobile.setStoredAuctionResponse("da112623-e004-44e0-bfe8-67e4ec350c5a")
    }
private fun initGAM() {
        MobileAds.initialize(this)
    }

private fun createBannerAdUnitAdmob() {
        var bannerView = AdView(applicationContext)
        bannerView.setAdSize(com.google.android.gms.ads.AdSize.BANNER)
        bannerView.adUnitId = _admobAdUnitId

        val extras = Bundle()
        val request = AdRequest
            .Builder()
            .addNetworkExtrasBundle(PrebidInterstitialAdapter::class.java, extras)
            .build()

        val mediationUtils = AdMobMediationBannerUtils(extras, bannerView)

        val adUnit = MediationBannerAdUnit(
            applicationContext,
            _configId,
            _adSize,
            mediationUtils
        )
        adUnit.setRefreshInterval(30)

        adUnit.fetchDemand { result ->
            Toast.makeText(applicationContext, "Banner Admob - $result", Toast.LENGTH_SHORT).show()
            bannerView.loadAd(request)
        }
    }
```
When I press the button, I get `Banner Admob - SUCCESS` but no ads is shown. I have set up 6 line items which a price increment of $1.00, as follow:
![alt text](https://drive.google.com/uc?export=view&id=1UEr7ywRFMI-2V5Vv3rOGynJkgNPdxX2_)
![alt text](https://drive.google.com/uc?export=view&id=1QSBXRBV371T0DIo9YJyjwdYgd1tWeiC1)

In my `PrebidBaseNetworkTask: Result`, I see the keyword `"hb_pb":"5.09"`

What is wrong with my set up?

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40! 

The value of the `Parameter` of one of your AD SOURCEs must be the same as a keyword of the winning bid. 

"hb_pb":"5.09"

Prebid SDK Adapter will start rendering the bid on a complete match of the keyword. Try to add and AD SOURCE with "hb_pb":"5.09"

**Comment by clho40** [comment]
hello @YuriyVelichkoPI , thanks for correcting. I found that typo after posting this issue.

But really, I need to have 5.09 exactly? So the increment has to be 0.01? What happened to the rounding?

**Comment by YuriyVelichkoPI** [comment]
You can manage the price granularity on the server side
https://docs.prebid.org/adops/price-granularity.html

So the price can be rounded to .50 with `low` value. 

However, on the client side, SDK checks the exact match. 

Right now, I'm not sure whether it makes sense to make a price adjustment on the client side as well. Need to study the motivation for such a feature.

**Comment by YuriyVelichkoPI** [comment]
Have you tried config IDs from the demo app in your project? Including the server host. 

It would be great if you send us one of the following items so that we can troubleshoot the issue (sorted by priority):
- app source code
- .apk file with network_security_config settings allowed to trust the Charles certificate
- the Charles logs

**Comment by clho40** [comment]
I am not sure what do I have to do on the client side. I'm sending you the whole project :)

**Comment by clho40** [comment]
Hello @YuriyVelichkoPI , did you manage to find something?

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40 ! Not yet. The work in progress.

**Comment by clho40** [comment]
Ok got it. There are 2 problems in the documentation, I have fixed them and created a pr https://github.com/prebid/prebid.github.io/pull/4330

Here's the code, just in case if someone else needs it :)
```
private fun createBannerAdUnitAdmob() {
        var bannerView = AdView(applicationContext)
        bannerView.setAdSize(com.google.android.gms.ads.AdSize.BANNER)
        bannerView.adUnitId = _admobAdUnitId

        // add the bannerView into the view tree!
        binding.adBannerAdUnitAdMob.addView(bannerView)

        val extras = Bundle()

        //Use PrebidBannerAdapter instead of PrebidInterstitialAdapter!
        val request = AdRequest
            .Builder()
            .addNetworkExtrasBundle(PrebidBannerAdapter::class.java, extras)
            .build()

        val mediationUtils = AdMobMediationBannerUtils(extras, bannerView)

        val adUnit = MediationBannerAdUnit(
            applicationContext,
            _configId,
            _adSize,
            mediationUtils
        )
        adUnit.setRefreshInterval(30)

        adUnit.fetchDemand { result ->
            Toast.makeText(applicationContext, "Banner Admob - $result", Toast.LENGTH_SHORT).show()
            bannerView.loadAd(request)
        }
    }
```

**Comment by clho40** [comment]
But still, @YuriyVelichkoPI What I don't understand is, do I have to round the hb_pb to match the price I set on AdMob manually?

If, say, Pubmatic returns an ad with the price of $1.03, on my AdMob mediation waterfall I have 0.50,1.00,1.50,2.00, wouldn't it work?

**Comment by YuriyVelichkoPI** [comment]
Thank you @clho40. I've just merged the PR for docs. 

Can we close this ticket?

**Comment by YuriyVelichkoPI** [comment]
Sorry, haven't seen the last question. 

You should have an ad source with the same price in parameters as your winning bid has.
As for me, it is the same rule as for GAM. And yes, it is common practice to set up 100-200 line items (ad sources) for the prebid demand.  Depending on the price granularity.

**Comment by clho40** [comment]
Ok, I get it now :) 

Closing this! Cheers!
