### ISSUE TITLE
Throw Exception when AdUnit is not registered

### ISSUE THREAD

**Issue by huishan** [prebid/prebid-mobile-android#59]
Is it possible to throw and exception if the adUnit is not registered before similar to the iOS SDK behaviour?

Currently it is only printing one line of log like this: "E/Prebid-BidManager: AdUnit for code <ad-unit-code> is not registered, no bid available."

**Comment by huishan** [comment]
Alternative, if we can check if the adUnit is registered bidMap in BidManager it will be good as well.

**Comment by anwzhang** [comment]
Hi @huishan what's the goal you want to achieve with knowing the ad unit is registered or not?

**Comment by huishan** [comment]
Hi @anwzhang, business logic wants us to fallback to a default adUnit if the current one we are requesting is not registered before.

**Comment by anwzhang** [comment]
Hi @huishan 

`setBidKeywordsOnAdObject` should never be called with unregistered ad unit. I don't quite understand why you would use an unregistered ad unit in the first, and not use the default ad unit directly.
Can you provide more details on your business logic?
