### ISSUE TITLE
Build script leaves a Java process running

### ISSUE THREAD

**Issue by rmloveland** [prebid/prebid-mobile-android#6]
When I run `sh buildscript.sh` in the Terminal on Mac OS X, a Java process is started up that steals my keyboard and mouse focus from other apps and continues running after the build script finishes.

Looks like it's the gradle daemon:

```
$ pgrep -i java
rloveland        74946   0.0  0.7  5792624  60576   ??  Ss    3:38PM   2:34.42 /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java -Xmx1536m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/rloveland/.gradle/wrapper/dists/gradle-3.3-all/55gk2rcmfc6p2dg9u9ohc3hw9/gradle-3.3/lib/gradle-launcher-3.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 3.3
```

The process stays in my list of open apps when I press Cmd-Tab, and only goes away after I issue a `kill -15`.

It's somewhat unexpected behavior (at least for me), since I don't expect a build script to leave a process hanging around after it finishes.

Is there a way to run gradle without it expecting to be a daemon?  Or alternatively, to clean up the gradle process after the build?

**Comment by anwzhang** [comment]
Hi @rmloveland , 

Gradle daemon is disabled in this PR: https://github.com/prebid/prebid-mobile-android/pull/8
Let me know if you're still running into this issue.

**Comment by anwzhang** [comment]
PR #8 merged.
