### ISSUE TITLE
Prebid Server Bad Request (Status Code 400)

### ISSUE THREAD

**Issue by AndroidRio** [prebid/prebid-mobile-android#60]
Hi,

Thanks for providing this awesome SDK. We are currently facing an issue with it where the server always returns two distinct error message. Before displaying the error message, here is my configuration:

Config with id 60b721f7-bf64-49aa-8a45-8ddc56278529:
```
[
    {
        "code": "/73314699/OLX/Listing",
        "bids": [
            {
                "bidder": "appnexus",
                "params": {
                    "placement_id": 13359963
                }
            },
            {
                "params": {
                    "zoneId": 556108,
                    "siteId": 118014,
                    "accountId": 14702
                },
                "bidder": "rubicon"
            }
        ],
        "sizes": [
            [
                300,
                250
            ]
        ]
    }
]
```
And this is the json object that the SDK is building:
```
{
	"id": "989dbf01-3efd-4014-a327-6c42b4d1b4ff",
	"source": {
		"tid": "989dbf01-3efd-4014-a327-6c42b4d1b4ff"
	},
	"imp": [
		{
			"id": "\/73314699\/OLX\/Listing",
			"secure": 1,
			"ext": {
				"prebid": {
					"storedrequest": {
						"id": "60b721f7-bf64-49aa-8a45-8ddc56278529"
					}
				}
			},
			"banner": {
				"format": [
					{
						"w": 300,
						"h": 250
					}
				]
			}
		}
	],
	"device": {
		"make": "samsung",
		"model": "SM-G955F",
		"ua": "Mozilla\/5.0 (Linux; Android 7.0; SM-G955F Build\/NRD90M; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/67.0.3396.87 Mobile Safari\/537.36",
		"w": 411,
		"h": 773,
		"pxratio": 3.5,
		"mccmnc": "724-39",
		"carrier": "Nextel",
		"connectiontype": 1,
		"lmt": 0,
		"ifa": "8e8dbd04-a28d-41cb-bb5b-26ff10626bdb",
		"os": "android",
		"osv": "24",
		"language": "en"
	},
	"app": {
		"bundle": "com.schibsted.bomnegocio.androidApp.beta",
		"ver": "11.6.0.0-beta",
		"name": "OLX",
		"privacypolicy": 0,
		"publisher": {
			"id": "d2542d26-9478-474c-9c4d-ac5de5453259"
		},
		"ext": {
			"prebid": {
				"source": "prebid-mobile",
				"version": "0.4"
			}
		}
	},
	"user": {
		"gender": "O"
	},
	"regs": {
		"ext": {}
	},
	"ext": {
		"prebid": {
			"storedrequest": {
				"id": "d2542d26-9478-474c-9c4d-ac5de5453259"
			}
		}
	}
}
```

Sometimes it is giving that the configuration is not found:
![image](https://user-images.githubusercontent.com/5436014/43405681-c38b4084-93f0-11e8-8c0b-43aee4d1babb.png)

And sometimes it is stating that the placement_id is with the incorrect type which isn't:
![image](https://user-images.githubusercontent.com/5436014/43405712-d6b9e44e-93f0-11e8-97e5-55ed7730a08e.png)

**Comment by anwzhang** [comment]
Hi @AndroidRio, 

For the first issue, we checked in the Database that the json data you put in for your config id is malformatted. 

It should be something like this:
`[
  {"params":{"placementId":123456},"bidder":"appnexus"},
  {"params":{"siteID":123456,"id":"4"},"bidder":"indexExchange"},
  {"params":{"publisherId":"123456","adSlot":"39620189@300x250"},"bidder":"pubmatic"},
  {"params":{"sizes":[15],"siteId":123456,"accountId":123456,"zoneId":123456},"bidder":"rubicon"}
]`
I used 123456 for the ids for privacy. 
For the second issue, you should pass in integer type in the JSON instead of string, I gave an example above.
Let me know if you have more questions.
