### ISSUE TITLE
Requesting ad more than once on init().

### ISSUE THREAD

**Issue by huishan** [prebid/prebid-mobile-android#61]
Observe the logs to print more than once request failure when calling Prebid.init() with a list of ads. Logs attached:
[adRegisterLog.log](https://github.com/prebid/prebid-mobile-android/files/2256419/adRegisterLog.log)

**Comment by bszekely1** [comment]
Is this still an issue? We should close out the ticket if it's resolved. It's been open for over 8 months now.

**Comment by lilahunt** [comment]
It was reported on the old version of the SDK. Let's close and the issue can be reopened if it can be reproduced on the newest code base.

**Comment by anwzhang** [comment]
Close this as Prebid Mobile 1.0 does not have an init() function anymore.
