### ISSUE TITLE
Incorrect "1003 Parameters don't match" error breaks AppLovin mediation

### ISSUE THREAD

**Issue by linean** [prebid/prebid-mobile-android#624]
**Describe the bug**

There is an issue when attempting to load a Prebid ad through AppLovin mediation. During the loading process, the ad parameters are checked for compatibility using `ParametersChecker:doParametersMatch.` If AppLovin mediation has no custom parameters configured, the AppLovin SDK returns an empty Bundle, which is transformed into null by `ParametersMatcher.bundleToHashMap`. This causes the execution of the following code:

```
doParametersMatch(
   serverParameters = null
   prebidParameters = [empty HashMap]
)  // false
```

As a result, the ad fails to load. I see two possible solutions to address this issue:
1. Modify the behavior of `ParametersMatcher.bundleToHashMap` to return an empty HashMap when the Bundle is empty.
2. Modify the comparison behavior of `ParametersMatcher.doParametersMatch` to consider an empty map parameter equal to null.

**To Reproduce**
1. Configure AppLovin mediation with Prebid
3. Create new AppLovin ad unit and specify **no** parameters for Prebid network
4. Try to load Prebid ad using AppLovin mediator - specify **no** custom parameters
5. Ad is rejected because `Parameters don't match`

**Expected behavior**
Empty parameters should not affect ad loading.

**Smartphone (please complete the following information):**
 - Reproduced for SDK version 2.0.9 and 2.1.0

**Comment by YuriyVelichkoPI** [comment]
Hi @linean ! By design, prebid mediation items on MAX _must_ have a custom parameter with the bid price. Otherwise, the adapter will be triggered regardless of the bid price and even regardless of the winning

**Comment by linean** [comment]
Hi @YuriyVelichkoPI !

Thanks for the quick response 💪  I think I've missed part about [custom parameters](https://docs.prebid.org/adops/mobile-rendering-max-line-item-setup.html) in your docs. I'll try that out and let you know tomorrow.

**Comment by linean** [comment]
Yep, that was it. Let's close this issue.
