### ISSUE TITLE
Use new config ids in `InternalTestApp`

### ISSUE THREAD

**Issue by OlenaPostindustria** [prebid/prebid-mobile-android#635]
Some creatives no longer contain tracking events, win notifiers, etc, due to clean-up work in [#839](https://github.com/prebid/prebid-mobile-ios/issues/839). These removed parts are utilized in automated tests. So please, apply new config ids in InternalTestApp:

<google-sheets-html-origin>

Old | New
-- | --
prebid-demo-banner-300-250 | prebid-ita-banner-300-250
prebid-demo-banner-320-50 | prebid-ita-banner-320-50
prebid-demo-banner-native-styles | prebid-ita-banner-native-styles
prebid-demo-display-interstitial-320-480 | prebid-ita-display-interstitial-320-480
prebid-demo-video-interstitial-320-480-original-api | prebid-ita-video-interstitial-320-480-original-api
prebid-demo-video-interstitial-320-480 | prebid-ita-video-interstitial-320-480
prebid-demo-video-outstream-original-api | prebid-ita-video-outstream-original-api
prebid-demo-video-outstream | prebid-ita-video-outstream
prebid-demo-video-rewarded-320-480-original-api | prebid-ita-video-rewarded-320-480-original-api
prebid-demo-video-rewarded-320-480 | prebid-ita-video-rewarded-320-480

**Comment by ValentinPostindustria** [comment]
Something is wrong with Rewarded video config id. It shows only a black screen with the close button without any video.
