### ISSUE TITLE
VAST checker improvement

### ISSUE THREAD

**Issue by ValentinPostindustria** [prebid/prebid-mobile-android#638]
For now, VAST checker's regex ignores some cases with whitespace (around `=`):
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/c43a7c5d-1d8b-41eb-99fb-32d0661980f6)

Fix for this:
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/e970cd56-e7ce-4591-8d6c-f80086a50fac)

**Comment by OlenaPostindustria** [comment]
> @OlenaPostindustria would the tag with spaces be valid on iOS as well?

Yes, it will be valid.

See [VAST tag regex ](https://github.com/prebid/prebid-mobile-ios/blob/fad2d5b4218532cac123fd75fdf67ee37c097151/PrebidMobile/PrebidMobileRendering/AdTypes/PBMHTMLCreative.m#LL145C86-L145C120) and [unit test](https://github.com/prebid/prebid-mobile-ios/blob/fad2d5b4218532cac123fd75fdf67ee37c097151/PrebidMobileTests/RenderingTests/Tests/PBMHTMLCreativeTest.swift#L379).
