### ISSUE TITLE
Native Asset ID association issue 

### ISSUE THREAD

**Issue by GhadaSalah** [prebid/prebid-mobile-android#640]
**Describe the bug**
asset.id is not included automatically in the native object in the bid request.

**To Reproduce**
(The issue was replicated on Android already)

**Expected behavior**
It is expected that the ID of each asset is included in the native object in the bid request.

**Screenshots**
Here is the request received: 
`{
  "imp": [
    {
      "id": "075e6fea-ad7b-44cd-bc13-4454699c198c",
      "instl": 0,
      "clickbrowser": 0,
      "secure": 1,
      "native": {
        "request": "{\"ver\":\"1.2\",\"context\":2,\"contextsubtype\":20,\"plcmttype\":1,\"seq\":0,\"assets\":[{\"required\":1,\"title\":{\"len\":90}},{\"required\":1,\"img\":{\"type\":1,\"w\":20,\"wmin\":20,\"h\":20,\"hmin\":20}},{\"required\":1,\"img\":{\"type\":3,\"w\":200,\"wmin\":200,\"h\":200,\"hmin\":200}},{\"required\":1,\"data\":{\"type\":1,\"len\":90}},{\"required\":1,\"data\":{\"type\":2,\"len\":-1}},{\"required\":1,\"data\":{\"type\":12,\"len\":-1}}],\"eventtrackers\":[{\"event\":1,\"methods\":[1,2]}]}",
        "ver": "1.2"
      },
      "ext": {
        "prebid": {
          "storedrequest": {
            "id": "prebid-demo-banner-native-styles"
          }
        }
      }
    }
  ],
  "id": "075e6fea-ad7b-44cd-bc13-4454699c198c",
  "app": {
    "name": "Prebid Kotlin Demo",
    "bundle": "org.prebid.mobile.prebidkotlindemo",
    "ver": "1.0.0",
    "publisher": {
      "id": "0689a263-318d-448b-a3d4-b02e8a709d9d"
    },
    "ext": {
      "prebid": {
        "source": "prebid-mobile",
        "version": "2.1.0"
      }
    }
  },
  "device": {
    "ua": "Mozilla\/5.0 (Linux; Android 13; Pixel 7 Build\/TQ2A.230505.002; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/113.0.5672.162 Mobile Safari\/537.36",
    "lmt": 0,
    "make": "Google",
    "model": "Pixel 7",
    "os": "Android",
    "osv": "13",
    "language": "en",
    "carrier": "Proximus",
    "mccmnc": "206-01",
    "ifa": "ac463f19-87ec-4601-ae4b-f18301eaa236",
    "h": 2400,
    "w": 1080,
    "connectiontype": 3,
    "pxratio": 2.625
  },
  "regs": {
    "ext": {
      "coppa": 0,
      "gdpr": 1
    }
  },
  "user": {},
  "source": {
    "tid": "075e6fea-ad7b-44cd-bc13-4454699c198c"
  },
  "ext": {
    "prebid": {
      "storedrequest": {
        "id": "0689a263-318d-448b-a3d4-b02e8a709d9d"
      },
      "cache": {
        "bids": {}
      },
      "targeting": {}
    }
  }
}`

Response:
`{
  "id": "075e6fea-ad7b-44cd-bc13-4454699c198c",
  "seatbid": [
    {
      "bid": [
        {
          "id": "prebid-ita-response-banner-native-styles",
          "impid": "075e6fea-ad7b-44cd-bc13-4454699c198c",
          "price": 0.1,
          "adm": "{\"assets\":[{\"required\":1,\"title\":{\"text\":\"Prebid (Title)\"}},{\"id\":1,\"required\":1,\"img\":{\"type\":1,\"url\":\"https://s3.amazonaws.com/files.prebid.org/creatives/prebid120x60.png\"}},{\"id\":2,\"required\":1,\"img\":{\"type\":3,\"url\":\"https://s3.amazonaws.com/files.prebid.org/creatives/prebid728x90.png\"}},{\"id\":3,\"required\":1,\"data\":{\"type\":1,\"value\":\"Prebid (Brand)\"}},{\"id\":4,\"required\":1,\"data\":{\"type\":2,\"value\":\"Learn all about this awesome story of someone using out PrebidMobile SDK.\"}},{\"id\":5,\"required\":1,\"data\":{\"type\":12,\"value\":\"Click here to visit our site!\"}}],\"link\":{\"url\":\"https://prebid.org/\"},\"eventtrackers\":[{\"event\":555,\"method\":2,\"url\":\"https://prebid-mobile-ad-assets.s3.amazonaws.com/scripts/omid-validation-verification-script-v1.js\",\"ext\":{\"vendorKey\":\"iabtechlab.com-omid\",\"verification_parameters\":\"iabtechlab-prebid\"}}]}",
          "crid": "test-creative-id-1",
          "ext": {
            "prebid": {
              "type": "native",
              "targeting": {
                "hb_pb": "0.10",
                "hb_cache_id_prebid": "f88bc1fa-038f-481a-a65d-2cbf0a5cbc36",
                "hb_env": "mobile-app",
                "hb_cache_host_prebid": "prebid-server-test-j.prebid.org",
                "hb_pb_prebid": "0.10",
                "hb_cache_path": "/cache",
                "hb_cache_path_prebid": "/cache",
                "hb_bidder_prebid": "prebid",
                "hb_bidder": "prebid",
                "hb_cache_id": "f88bc1fa-038f-481a-a65d-2cbf0a5cbc36",
                "hb_cache_host": "prebid-server-test-j.prebid.org",
                "hb_env_prebid": "mobile-app"
              },
              "cache": {
                "bids": {
                  "url": "https://prebid-server-test-j.prebid.org/cache?uuid=f88bc1fa-038f-481a-a65d-2cbf0a5cbc36",
                  "cacheId": "f88bc1fa-038f-481a-a65d-2cbf0a5cbc36"
                }
              }
            },
            "origbidcpm": 0.1,
            "origbidcur": "USD"
          }
        }
      ],
      "seat": "prebid",
      "group": 0
    }
  ],
  "cur": "USD",
  "ext": {
    "warnings": {
      "prebid": [
        {
          "code": 999,
          "message": "WARNING: request.imp[0].ext must contain at least one valid bidder"
        }
      ]
    },
    "responsetimemillis": {
      "cache": 35,
      "prebid": 0
    },
    "tmaxrequest": 5000,
    "prebid": {
      "auctiontimestamp": 1685966885733
    }
  }
}`

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Android

**Additional context**

**Comment by YuriyVelichkoPI** [comment]
Hi @GhadaSalah ! It is an expected default behavior for the SDK since PRS assigns IDs later before sending the final request to bidders. 

 If you need to force the IDs on the client side, use `PrebidMobile.assignNativeAssetID(true)` method just after SDK initialization. 
 
 Please let me know if it resolves your issue.

**Comment by GhadaSalah** [comment]
Hi @YuriyVelichkoPI ! We've tried that and it unfortunately doesn't work. According to the client that function is declared but never used in the SDK so that might be the reason why the flag does not do anything.

**Comment by YuriyVelichkoPI** [comment]
Hi @GhadaSalah! Thanks for the info, and @avohraa, thanks for the fix. It will be available in the upcoming release early next week.
