### ISSUE TITLE
Include Winners and Include Bidders Flag Setters and Fuctionality

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [prebid/prebid-mobile-android#651]
**Is your feature request related to a problem? Please describe.**

Problem:
Yes, the problem is i can not add the flags `includewinners`  and  `includebidderkeys`  of the bidrequest in my PrebidServer because Xandr\appnexus does not support it. So i need a way to edit the bidrequest skeleton the SDK generates before sending the bid request to the server for completion.

**Describe the solution you'd like**

- This flags not included by default in the bid request skeleton or set to false (same thing), just like now, so we don't break anything for other people
- Have TWO methods one for each flag receiving a boolean as parameter.
- This Methods are located in PrebidMobile Singleton

Use Examples:
```
PrebidMobile.addIncludeWinnersFlag(true)
PrebidMobile.addIncludeBidderKeysFlag(false)
```

**Why not a pull request?**
I Haven't done a pull request because I'm in an old version (2.0.0) and i don't know if everything is in the same way for the clases that i changed but basically what i have done is in my fork is change 2 clases: 

PrebidMobile.java:
![image](https://github.com/prebid/prebid-mobile-android/assets/36243865/28d50ea7-922e-4592-9524-f5c0a20f945b)

Prebid.java
![image](https://github.com/prebid/prebid-mobile-android/assets/36243865/f416e453-2fba-48f1-b31f-2a35bcd840f2)

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

You could also have this functions in TargetingParams which for the name would make more sense but TargetingParams i think conceptually is conceived for the Targeting the App and User Privacy. Which this has nothing to do with it

**Additional context**
_Add any other context or screenshots about the feature request here._

The thing with this solution is i think in [this documentation](https://docs.prebid.org/prebid-server/use-cases/pbs-sdk.html#prebid-server-receives-the-request) I'm going to quote from that documentation:

> "The request that comes in from the SDK is more like a skeleton request. There are a number of key components missing, such as which bidders should be called.

I understand that the server is supposed to provide a way to include this flags FROM the server so this is not the responsibility of the PrebidMobile SDK, but currently Xandr/Appnexus is not providing any documentation regarding the inability of the server of only responding with the `Send All Bids` format

You can see what this flags do [here](https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#targeting).

Environment Generating the problem:
- Prebid Server = AppNexus PSP
- PrebidMobile Integration type = Original API
- Adops Configuration = Top Bids key values (can't switch)

**Comment by YuriyVelichkoPI** [comment]
Hi @AbrahamArmasCordero !  

Have you tried to set up these params in the stored request like described here:

https://docs.prebid.org/prebid-server/use-cases/pbs-sdk.html#prebid-server-resolves-the-stored-request-ids

From my understanding, support `includewinners` and `includebidderkeys` should be implemented in both servers GO and JAVA. If any of PBS doesn't support it now, it rather looks like a bug. 

Have you asked/posted an issue in the server repo regarding these flags?

**Comment by YuriyVelichkoPI** [comment]
I'm sorry if I asked the things that you have already described, but I want to make sure that:

- you tried to add `includewinners` and `includebidderkeys` to the stored request
- posted a bug report to Xandr or PBS that the server behaviour doesn't correspond to the documentation. If yes - what was their response?

**Comment by AbrahamArmasCordero** [comment]
Hi @YuriyVelichkoPI !

> Have you tried to set up these params in the stored request like described here:
> 
> https://docs.prebid.org/prebid-server/use-cases/pbs-sdk.html#prebid-server-resolves-the-stored-request-ids

Yes, Xandr does not support it right now, from their WebPage forms to configure the Server Stored Requests there are no options to add this flags values per adUnit or globally. So it is definitely a bug in their side.


> Have you asked/posted an issue in the server repo regarding these flags?

Yes. Indeed, we have been talking about this with Xandr for weeks now, and last news are that they moved it to the "integration team".

---

Since your answers makes it really clear, this is a problem of their implementation of the PBS, so I don't know how to continue with this issue. Next questions are:

- What will happen if the host provider, in this case Xandr, doesn't want to provide the PrebidMobile users with the functionality?. 
- Could we include this in the SDK until we reach a consensus for the SDK and Prebid.js at least?
- Are these Flags truly optional in the auction endpoint in the server?

---

In fairness to PBS Hosts, the Limits of what's included in the SDK "skeleton" request are very clear as the documentation **But the Limits of what MUST be included from the Server for completing the Bid Request are not that clear** (see screenshots):

![image](https://github.com/prebid/prebid-mobile-android/assets/36243865/64355980-a8e9-4b6c-840b-fe94f0a71324)

![image](https://github.com/prebid/prebid-mobile-android/assets/36243865/daa601b6-fb34-4388-93b6-cea155d224a5)

We know the server must include missing stuff but we don't know which stuff precisely, only some of them is addressed. 

Taking the SDK Limits of the skeleton and saying "everything else is from the server" is a logical assumption but is not consistent across the board, because in others documentations, for example, in the PBS+Prebid.js, the document explains how it is expected to receive those flags from the Prebid.js Skeleton see [here](https://docs.prebid.org/prebid-server/use-cases/pbs-pbjs.html#prebid-server-receives-the-request).

Also these Flags show up as optional in [here](https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#targeting) but since these flags are used to choose between the Top Bid or Send All bids in the case of PrebidMobile, I think they shouldn't be marked as optional for the Server.

Anyway this issue and your response and further feedback in the issue will make my conversation with Xandr easier.

Sorry if I extended for too long. To finish with this, some actions to take as a result are:
1. Making a consensus of what is included in the skeletons sent to PBS from PrebidMobile, Prebid.js, AMP and Long Form Video, and put it in the documentation.
2. Tell the Hosts what must be included in the WebPages that we use as users to edit the Stored Requests.


Thank you the time and the help on the issue.

**Comment by YuriyVelichkoPI** [comment]
Hi @AbrahamArmasCordero! Thanks for your detailed response! It helped to clarify everything. 

So the issue is on the UI side of the particular host company. It's good to know since PBS and SDK work as expected, and no bugs here. 

---- 

Regarding the scope and limits of the SDK's request and the Server's stored request/impressions - it is hard to tell which properties should be obligatory on each side since it depends on each particular publisher and his auction setup. And the current approach looks good - PBS compliments the client's request by adding or rewriting the properties. So the publisher can modify behavior on the flight.  

The approach of assembling the bid request on the SDK side should be changed in the way that prebid.js provides. It will give publishers much more flexibility. But it is out of the scope of the current issue, of course.

----

For the current issue, I'm totally fine to introduce the respective API properties to set `includewinners` and `includebidderkeys`, so publishers don't depend on the host's UI and configuration abilities. 

However, I highly recommend you implement changes and open respective PRs (iOS and Android or at least one platform) because currently, Prebid doesn't have enough resources. Otherwise, you will wait for the prioritization and implementation.

**Comment by AbrahamArmasCordero** [comment]
I Just did the PR For Android

**Comment by AbrahamArmasCordero** [comment]
> I'm sorry if I asked the things that you have already described, but I want to make sure that:
> 
> * you tried to add `includewinners` and `includebidderkeys` to the stored request
> * posted a bug report to Xandr or PBS that the server behaviour doesn't correspond to the documentation. If yes - what was their response?

Regarding the Response from Xander this is their response after contacting the Devs:

> • The send top vs. send all option is determined by the endpoint that's being called and is not something we can add as an option for in our UI.
> • Allowing sellers to choose at a config level whether we send all bids or top bid would likely require substantial architecture changes and has not been requested by our clients before.

and they sent this link about SDK implementation saying they will always use Send All Bids no matter what the Ad Server is configured for

https://docs.xandr.com/bundle/monetize_monetize-standard/page/topics/integrate-apps-with-psp.html
