### ISSUE TITLE
Improve the cache and memory management for Native Ads

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-android#662]
## Objectives

Deprecate Method:

```
public boolean registerView(View view, final PrebidNativeAdEventListener listener)
```

Update rename method  

```
public boolean registerViewList(View container, List<View> viewList, final PrebidNativeAdEventListener listener)
```

to: 

```
public boolean registerView(View view, List<View> clickableViews, final PrebidNativeAdEventListener listener)
```

`view` - the native ad container used to track impression
`clickableViews` - list of views that should handle click

- Don't catch the registered view `registeredView` by the strong reference in the `PrebidNativeAd`.
- Don't catch the registered view `view` by the strong reference in `VisibilityDetector`.
- Don't catch the registered views in the  `clickableViews` by the strong references.
- Ensure that destroying the `PrebidNativeAd` all listeners and registered views are destroyed as well. No memory leaks should be here.  
- Ensure that the `CacheManager` signal the respective `PrebidNativeAd` objects on the expiration event. 
- Update tests

**Comment by ValentinPostindustria** [comment]
When a user uses `registerView()` with an anonymous listener parameter in Activity or Fragment, he can create a memory leak that we can't control. To prevent it a user should use a class that extends `PrebidNativeAdEventListener`.
```
class NativeListener : PrebidNativeAdEventListener {

        override fun onAdClicked() {}

        override fun onAdImpression() {}

        override fun onAdExpired() {}

}
```
And then use:
```
nativeAd.registerView(
            binding.adContainer,
            listOf(
                binding.tvNativeTitle,
                binding.ivNativeMain,
                binding.ivNativeIcon
            ),
            NativeListener() // ***
)
```
