### ISSUE TITLE
How to use with self-hosted Prebid Server?

### ISSUE THREAD

**Issue by robertdo** [prebid/prebid-mobile-android#67]
I have a self-hosted prebid server. Prebid.init() requires you to pass the Host as a param, but it seems like the only available enum options are APPNEXUS and RUBICON. How should I setup and config Prebid mobile Android SDK to work with a self-hosted prebid server?

**Comment by littleV** [comment]
Hi @robertdo, for the temporary solution you could just build your own version of PBM and add a HOST there, in the mean time, we created a ticket internal to discuss a more robust way to set it up.

**Comment by lilahunt** [comment]
Hi @robertdo the latest SDK supports a custom HOST configuration. Providing that resolves your config, can we close this issue?

**Comment by robertdo** [comment]
closing
