### ISSUE TITLE
Getting wrong sizes for interstitial ads

### ISSUE THREAD

**Issue by huishan** [prebid/prebid-mobile-android#68]
When app requesting interstitial ads, most of the time we are getting 300x250. This is observed on the sample app as well, and according to the ads team, this shouldn't be the case.

**Comment by sajokj** [comment]
We are expecting 320x480

**Comment by ptomasroos** [comment]
If I recall from the documentation of appnexus its by standard allowing sizes up to 50% of the screen sizes in order to have better fillrate. I guess you could configure this. This is the same case on mopub for instance

**Comment by bszekely1** [comment]
Do you have a sample of the request from prebid SDK to prebid server? This can help identify what the expected size should yield. The behavior of banner interstitials is documented in this commit for the GO adapter in the file auction.md: https://github.com/prebid/prebid-server/commit/23c8df30ff94d50a10a852dbff4974bd6dde3ea5

**Comment by lilahunt** [comment]
@bszekely1 I am going to close this issue due to inactivity. I recommend upgrading to the most recent SDK and retesting as well.
