### ISSUE TITLE
Demo app ads saying "This is served by DFP. PriceCheck Line Item didn't serve"

### ISSUE THREAD

**Issue by rmloveland** [prebid/prebid-mobile-android#7]
In the DFP side of the demo app, I am consistently seeing ads for both banners and interstitials saying:

"This is served by DFP. PriceCheck line item didn't serve"

This is while running the demo app on a Pixel XL.  Screenshots attached.

![screenshot_20170808-132729_720](https://user-images.githubusercontent.com/1312291/29093520-15a76c82-7c58-11e7-8188-00f893a191c2.png)

![screenshot_20170808-133012_720](https://user-images.githubusercontent.com/1312291/29093526-19d2dd0a-7c58-11e7-8e85-9574891b660b.png)

**Comment by anwzhang** [comment]
Hi Rich,

This is probably no valid bids while you're testing, so it showed the default line items that we set up in DFP.

Best,
Wei

**Comment by rmloveland** [comment]
Makes sense, thanks @anwzhang!  Happy to close this then, just wasn't sure if bug.  Sounds like not.
