### ISSUE TITLE
Create new release 0.5.1 (android)

### ISSUE THREAD

**Issue by AntoineJac** [prebid/prebid-mobile-android#72]
@ppuviarasu or @anwzhang , can you please merge this PR:
https://github.com/prebid/prebid-mobile-android/pull/71

And create a new release.

Thanks,

**Comment by AntoineJac** [comment]
@ppuviarasu any updates on this please?

**Comment by ppuviarasu** [comment]
We will be doing the release on Friday (tomorrow) after notifying the product manager.

**Comment by ppuviarasu** [comment]
The release is completed

**Comment by AntoineJac** [comment]
Thanks a lot for the notification @ppuviarasu
