### ISSUE TITLE
hb_cache_id wrong format?

### ISSUE THREAD

**Issue by whcemyesil** [prebid/prebid-mobile-android#74]
Hi! I've updated to the latest Prebid SDK version on iOS and Android. It works fine on iOS (in combination with the deprecated pbm.js script on the ad server). However on Android it doesn't work as expected. The hb_cache_id that is returned with the winning bid seems to have the wrong format: hb_cache_id = "Prebid_ffnsyslu_1540976994267" - this cache id is inserted into the line item script as follows: pbm.showAdFromCacheId({ admCacheID: 'Prebid_ffnsyslu_1540976994267' });
As a result, the ad doesn't render at all (empty white space)
While on iOS (and in v0.1 Android, which we had previously) it looks like this: hb_cache_id = "52af29e2-8f3f-4613-8bc5-e50a294ab678" and it DOES render correctly.

**Comment by anwzhang** [comment]
Hi @whcemyesil it's not wrong format, it's supposed to be using 'Prebid_xxxxx' since Android is using local cache. However, with API 1.0, it will only use server cache: https://github.com/prebid/prebid-mobile-android/issues/73

**Comment by whcemyesil** [comment]
I've taken a deeper look into the release change logs and the code and realised that local caching is enabled by default. When working with an ad SDK other than DFP the local cache doesn't work, so the fix was to disabled the local cache based on used ad server/ad sdk.

**Comment by anwzhang** [comment]
Hi @whcemyesil 
localCache is only enabled for DFP.

**Comment by whcemyesil** [comment]
Hi @anwzhang 
localCache enabled by default - so when using another SDK other than DFP or MoPub it is enabled by default if localCache is not considered in those switch cases - that was my problem since I wasn't aware of the localCache, but all good now!

see:
https://github.com/prebid/prebid-mobile-android/blob/1080c46d2d9f54cb001a2d4fcc8694f64bcbff60/PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/Prebid.java#L44
