### ISSUE TITLE
BidResponse will never get added to the list if `hb_creative_loadtype` is missing

### ISSUE THREAD

**Issue by huishan** [prebid/prebid-mobile-android#76]
https://github.com/prebid/prebid-mobile-android/blob/179099bb153ca0e316bef2ec3bcaa7e3f8bcae7a/PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/PrebidServerAdapter.java#L142

According to:
https://github.com/prebid/prebid-server/pull/750/commits/dd8cdb8425f749694fdde0d38b27d61f36429718

loadtype is already removed, need to update for mobile as well

**Comment by anwzhang** [comment]
@huishan created a PR to fix this: https://github.com/prebid/prebid-mobile-android/pull/77
