### ISSUE TITLE
AAR file?

### ISSUE THREAD

**Issue by pboisso** [prebid/prebid-mobile-android#86]
Hi guys,

Was wondering if it would be possible to host a compiled .aar file of this library somewhere in this repository?

Thanks.

**Comment by anwzhang** [comment]
Hi @pboisso 

Currently it's not on the roadmap. Do you have a reason for the aar version?

**Comment by pboisso** [comment]
Yes, to make Xamarin Bindings development easier.  That would be great if you could consider it.

**Comment by bszekely1** [comment]
Hi @pboisso, we will add it as an item to discuss in the roadmap.

**Comment by anwzhang** [comment]
@pboisso would you be able to build the aar yourself since the project is open source?

**Comment by pboisso** [comment]
Unfortunately, we are not set up to build this project.  Xamarin is compiling our c# code into native and all it requests to bind to a native external libraries, is an AAR file.  That would be very helpful if this could be provided. Thanks for considering it.

**Comment by bszekely1** [comment]
I will be closing this issue out unless we have further follow up required. This is over a year old at this point.
