### ISSUE TITLE
ServerConnector HttpURLConnection gives TimeOut exception

### ISSUE THREAD

**Issue by niranjannewscorp** [prebid/prebid-mobile-android#9]
I was trying to implement to PreBid android sdk. `ServerConnector`'s HttpURLConnection has 500 ms as it's timeout and it's very little for an HTTP post request. 

I tried to hit same post request through Postman, it took 5-6 seconds to get response. Hence, I get `SocketTimeOutException` a lot of times. Any workaround for this exception?

Also, sometimes I get  following error sometimes in response:
> { "status": "Prebid cache failed: context deadline exceeded"}

**Comment by anwzhang** [comment]
Hi @niranjannewscorp 

I created this PR https://github.com/prebid/prebid-mobile-android/pull/10 so you're now able to adjust the timeout based on the network condition by setting the Settings.REQUEST_TIME_OUR_MILLIS

For the second error, currently prebid-server is having issues with response cache service, and the team is actively working on the issues. I'll keep you updated when the issues are resolved.

**Comment by niranjannewscorp** [comment]
@anwzhang Thank man for quickly looking into it. How do I set `Settings.REQUEST_TIME_OUR_MILLIS`
 
I am using following code to register my AdUnits
> Prebid.init(application, adUnits, PBS_ACCOUNT_ID);

And `Prebid` class internally calls `ServerConnector` AsynTask class.

**Comment by anwzhang** [comment]
Hi @niranjannewscorp 

PR #10 is closed and merged, the change can be found on the master branch. If you want it from gradle, you have to wait for our next release, which is on next Wednesday. If you want to use the feature now, you can build the lib from source.

I've added a setter for you to override the value, call the following method before `Prebid.init` should work:
`Settings.setConnectionTimeOutMillis(2000)`

Our engineers are still working on the cache failed issue at this point.

**Comment by anwzhang** [comment]
Hi @niranjannewscorp 

All problems in this issue are resolved. For the change in SDK please find it in the latest release: https://github.com/prebid/prebid-mobile-android/releases/tag/0.0.2

**Comment by basithnewscorp** [comment]
Thanks, @anwzhang for the fix. And @niranjannewscorp for making it better
