### ISSUE TITLE
Inform clients to use a stable release version in Readme

### ISSUE THREAD

**Issue by teoboonkeat** [prebid/prebid-mobile-android#99]
Hi,

I think informing users to do
`compile 'org.prebid:prebid-mobile-sdk:[1,2)'`

is kind of dangerous? Users will end up using all versions from 1.0 to pre-2.0 without them knowing. It will save them much headache to know that your version change was one of the changes they made.

Propose to tell users to download your latest stable version.
`implementation 'org.prebid:prebid-mobile-sdk:1.0'`

**Comment by anwzhang** [comment]
Hi @teoboonkeat,

Thanks for the suggestion. Currently we only have 1.0 between 1-2. Will be more specific next time updating the repo.

**Comment by anwzhang** [comment]
Updated README.md in release 1.1
